import { describe, expect, it } from "vitest";

import {
    discoverSupportedModules,
    missingBackendBehavior,
    parseArgs,
    renderContractAssertions,
    renderDtoFile,
    resolveFullPath,
} from "../../scripts/sdk-contract-codegen.mjs";

describe("sdk-contract-codegen", () => {
    it("discovers all public contract modules from CONTRACT_INDEX, including low-coverage surfaces", () => {
        const modules = discoverSupportedModules();
        const basenames = new Set(modules.map((module) => module.docBasename));

        expect(basenames.has("background-update")).toBe(true);
        expect(basenames.has("feature-flags")).toBe(true);
        expect(basenames.has("event-report")).toBe(true);
        expect(basenames.has("worker-admin")).toBe(true);
    });

    it("renders DTO declarations from json request and response examples", () => {
        const text = `
### 2.3 更新特性开关
**请求体**:
\`\`\`json
{
  "enabled": true
}
\`\`\`

**响应**: \`200 OK\`
\`\`\`json
{}
\`\`\`
`;
        const output = renderDtoFile(
            {
                ledgerModule: "feature_flags",
                docBasename: "feature-flags",
                typePrefix: "FeatureFlags",
            },
            text,
        );

        expect(output).toContain("export interface FeatureFlagsRequestDto");
        expect(output).toContain("enabled: boolean;");
        expect(output).toContain("export type FeatureFlagsResponseDto = Record<string, never>;");
    });

    it("renders executable assertion metadata for status, typed errors, and errcodes", () => {
        const assertions = renderContractAssertions(
            {
                ledgerModule: "dm",
                constName: "DM_ROUTES",
                typePrefix: "Dm",
            },
            [],
            2,
            `
| 状态码 | 说明 |
| ------ | ---- |
| \`200\` | 请求成功 |
| \`401\` | Token 无效 |

| 场景 | HTTP / errcode | SDK 统一错误类型 | 调用方建议 |
| ---- | -------------- | ---------------- | ---------- |
| 未认证 | \`401 / M_UNKNOWN_TOKEN\` | \`AuthError\` | 重新登录 |

| errcode | 常见 HTTP | 说明 |
| ------- | --------- | ---- |
| \`M_UNKNOWN_TOKEN\` | \`401\` | token 失效 |
`,
        );

        expect(assertions).toContain("export const DM_ROUTES_STATUS_SCENARIOS = [");
        expect(assertions).toContain('{ status: 401, note: "Token 无效" }');
        expect(assertions).toContain('sdkErrorType: "AuthError"');
        expect(assertions).toContain('errcode: "M_UNKNOWN_TOKEN"');
    });

    it("ignores synced auto-generated snippet blocks when extracting DTO declarations", () => {
        const text = `
## 代码生成产物

\`\`\`ts
/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 */
export interface FeatureFlagsResponse {
// ... truncated (22 more lines)
\`\`\`

### 2.3 更新特性开关
**请求体**:
\`\`\`json
{
  "enabled": true
}
\`\`\`
`;
        const output = renderDtoFile(
            {
                ledgerModule: "feature_flags",
                docBasename: "feature-flags",
                typePrefix: "FeatureFlags",
            },
            text,
        );

        expect(output).toContain("export interface FeatureFlagsRequestDto");
        expect(output).not.toContain("export interface FeatureFlagsResponse {\n// ... truncated");
    });
});

describe("resolveFullPath", () => {
    const emptyLookups = { backend: new Map<string, string>(), sdk: new Map<string, string>() };

    it("honours the doc's own absolute prefix instead of re-prefixing from the sdk dir", () => {
        // 回归守卫（F-A1-04）：media 目录承载的文档条目，若原文已声明 client 前缀，不得被改写成
        // media 前缀。历史缺陷链路：normalizeResourcePath 先把 `/_matrix/client/v3` 剥掉，
        // resolveFullPath 只检查归一化后的 `/upload/provider`，于是按 sdkDir === "media" 拼出了
        // 后端并不服务的 `/_matrix/media/v3/upload/provider`（该路由实际由 assembly.rs 通过
        // `.nest("/_matrix/client/v3", media::create_upload_provider_router())` 注册）。
        expect(
            resolveFullPath("GET", "/upload/provider", "media", emptyLookups, "/_matrix/client/v3/upload/provider"),
        ).toBe("/_matrix/client/v3/upload/provider");
        expect(resolveFullPath("POST", "/upload/token", "media", emptyLookups, "/_matrix/client/v3/upload/token")).toBe(
            "/_matrix/client/v3/upload/token",
        );
    });

    it("still prefixes relative doc paths that carry no absolute form", () => {
        expect(resolveFullPath("POST", "/upload", "media", emptyLookups)).toBe("/_matrix/media/v3/upload");
        expect(resolveFullPath("GET", "/capabilities", "room", emptyLookups)).toBe("/_matrix/client/v3/capabilities");
    });

    it("prefers canonical lookup hits over the doc's raw path", () => {
        // 归一化查找是刻意的版本纠偏机制（文档写 v3、后端实际服务 v1 时以 ledger 为准），
        // rawPath 只在查找落空时兜底，不得抢先覆盖。
        const backend = new Map([["GET /upload/provider", "/_matrix/client/v1/upload/provider"]]);
        expect(
            resolveFullPath(
                "GET",
                "/upload/provider",
                "media",
                { backend, sdk: new Map() },
                "/_matrix/client/v3/upload/provider",
            ),
        ).toBe("/_matrix/client/v1/upload/provider");
    });
});

/**
 * `--strict` / 无后端契约时的降级语义（2026-10-09）。
 *
 * 背景：CI 是 SDK-only checkout（runner 上没有 `../synapse-rust`），原先脚本在契约缺失时
 * 硬 `return 2` ⇒ `quality:contracts` 在 CI 上**必红**（fork 上 Quality Gate 从未绿过，
 * 10-06 与 10-09 两个 run 同一条 `Entrypoint contract gates`）。现改为默认 skip、
 * `--strict` 才 fail，与 check-sdk-contract-alignment.mjs 既有的同款降级一致。
 */
describe("sdk-contract-codegen CLI 契约（缺后端仓的降级）", () => {
    it("parseArgs 认 --check / --strict，默认非 strict，未知参数即抛", () => {
        expect(parseArgs(["node", "x", "--check"])).toEqual({ mode: "check", help: false, strict: false });
        expect(parseArgs(["node", "x", "--check", "--strict"])).toEqual({
            mode: "check",
            help: false,
            strict: true,
        });
        expect(() => parseArgs(["node", "x", "--nope"])).toThrow(/unknown argument/);
    });

    it("无后端契约时默认 skip（exit 0）—— CI 布局不该常红", () => {
        expect(missingBackendBehavior({ strict: false })).toEqual({ action: "skip", exitCode: 0 });
        expect(missingBackendBehavior({})).toEqual({ action: "skip", exitCode: 0 });
        expect(missingBackendBehavior()).toEqual({ action: "skip", exitCode: 0 });
    });

    it("--strict 时 fail（exit 2）—— 工作区/release 布局缺兄弟仓就该红", () => {
        expect(missingBackendBehavior({ strict: true })).toEqual({ action: "fail", exitCode: 2 });
    });
});
