import { describe, expect, it } from "vitest";

import {
    discoverSupportedModules,
    renderContractAssertions,
    renderDtoFile,
} from "../../scripts/sdk-contract-codegen.mjs";

describe("sdk-contract-codegen", () => {
    it("discovers all public contract modules from CONTRACT_INDEX, including low-coverage surfaces", () => {
        const modules = discoverSupportedModules();
        const basenames = new Set(modules.map((module) => module.docBasename));

        expect(basenames.has("background-update")).toBe(true);
        expect(basenames.has("feature-flags")).toBe(true);
        expect(basenames.has("event-report")).toBe(true);
        expect(basenames.has("worker-admin")).toBe(true);
    });

    it("renders DTO declarations from json request and response examples", () => {
        const text = `
### 2.3 更新特性开关
**请求体**:
\`\`\`json
{
  "enabled": true
}
\`\`\`

**响应**: \`200 OK\`
\`\`\`json
{}
\`\`\`
`;
        const output = renderDtoFile(
            {
                ledgerModule: "feature_flags",
                docBasename: "feature-flags",
                typePrefix: "FeatureFlags",
            },
            text,
        );

        expect(output).toContain("export interface FeatureFlagsRequestDto");
        expect(output).toContain("enabled: boolean;");
        expect(output).toContain("export type FeatureFlagsResponseDto = Record<string, never>;");
    });

    it("renders executable assertion metadata for status, typed errors, and errcodes", () => {
        const assertions = renderContractAssertions(
            {
                ledgerModule: "dm",
                constName: "DM_ROUTES",
                typePrefix: "Dm",
            },
            [],
            2,
            `
| 状态码 | 说明 |
| ------ | ---- |
| \`200\` | 请求成功 |
| \`401\` | Token 无效 |

| 场景 | HTTP / errcode | SDK 统一错误类型 | 调用方建议 |
| ---- | -------------- | ---------------- | ---------- |
| 未认证 | \`401 / M_UNKNOWN_TOKEN\` | \`AuthError\` | 重新登录 |

| errcode | 常见 HTTP | 说明 |
| ------- | --------- | ---- |
| \`M_UNKNOWN_TOKEN\` | \`401\` | token 失效 |
`,
        );

        expect(assertions).toContain("export const DM_ROUTES_STATUS_SCENARIOS = [");
        expect(assertions).toContain('{ status: 401, note: "Token 无效" }');
        expect(assertions).toContain('sdkErrorType: "AuthError"');
        expect(assertions).toContain('errcode: "M_UNKNOWN_TOKEN"');
    });

    it("ignores synced auto-generated snippet blocks when extracting DTO declarations", () => {
        const text = `
## 代码生成产物

\`\`\`ts
/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 */
export interface FeatureFlagsResponse {
// ... truncated (22 more lines)
\`\`\`

### 2.3 更新特性开关
**请求体**:
\`\`\`json
{
  "enabled": true
}
\`\`\`
`;
        const output = renderDtoFile(
            {
                ledgerModule: "feature_flags",
                docBasename: "feature-flags",
                typePrefix: "FeatureFlags",
            },
            text,
        );

        expect(output).toContain("export interface FeatureFlagsRequestDto");
        expect(output).not.toContain("export interface FeatureFlagsResponse {\n// ... truncated");
    });
});
