/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/widget.json
 */

import { WIDGET_ROUTES } from "./route-table";

export const WIDGET_ROUTES_ENTRY_COUNT = 18 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _WidgetEntryCountAssertion: 18 = WIDGET_ROUTES.length;
void _WidgetEntryCountAssertion;

export const WIDGET_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "widget 与 room 不匹配，或请求体字段不合法" },
    { status: 401, note: "需认证的 widget / session / 房间级接口缺少或使用无效令牌" },
    { status: 403, note: "已登录但无 widget 访问权限，或不是房间成员且非管理员" },
    { status: 404, note: "房间、widget 或 session 不存在" },
    { status: 500, note: "存储层或 service 层内部错误" },
] as const;

export type WidgetStatusScenario = (typeof WIDGET_ROUTES_STATUS_SCENARIOS)[number];

export const WIDGET_ROUTES_ERROR_SCENARIOS = [
] as const;

export type WidgetErrorScenario = (typeof WIDGET_ROUTES_ERROR_SCENARIOS)[number];

export const WIDGET_ROUTES_ERRCODES = [
] as const;

export type WidgetErrcode = (typeof WIDGET_ROUTES_ERRCODES)[number];
