// Auto-generated by contract:codegen. Do not edit manually.

/** A widget as stored/returned by the server. */
export interface WidgetDto {
    widget_id: string;
    room_id: string | null;
    user_id: string;
    type: string;
    url: string;
    name: string;
    data: Record<string, unknown>;
    creator: string;
    active: boolean;
}

/** GET /_matrix/client/v1/widgets/{widgetId} or POST /_matrix/client/v1/widgets response wrapper. */
export interface WidgetResponseDto {
    widget: WidgetDto;
}

/** POST /_matrix/client/v1/widgets request body. */
export interface CreateWidgetRequestDto {
    room_id?: string;
    widget_type: string;
    url: string;
    name: string;
    data?: Record<string, unknown>;
}

/** PUT /_matrix/client/v1/widgets/{widgetId} request body. */
export interface UpdateWidgetRequestDto {
    url?: string;
    name?: string;
    data?: Record<string, unknown>;
}

/** GET /_matrix/client/v1/rooms/{roomId}/widgets response. */
export interface RoomWidgetsResponseDto {
    widgets: WidgetDto[];
}

/** POST /_matrix/client/v1/widgets/{widgetId}/permissions request body. */
export interface WidgetPermissionsRequestDto {
    user_id: string;
    permissions: string[];
}

/** GET /_matrix/client/v1/widgets/{widgetId}/permissions response. */
export interface WidgetPermissionsResponseDto {
    user_id?: string;
    permissions?: string[];
    [key: string]: unknown;
}

/** POST /_matrix/client/v1/widgets/{widgetId}/sessions request body. */
export interface WidgetSessionCreateRequestDto {
    widget_id?: string;
    device_id?: string;
    expires_in_ms?: number;
}

/** GET /_matrix/client/v1/widgets/{widgetId}/sessions response. */
export interface WidgetSessionsResponseDto {
    sessions: WidgetSessionDto[];
    [key: string]: unknown;
}

/** A widget session. */
export interface WidgetSessionDto {
    session_id: string;
    widget_id: string;
    device_id?: string;
    created_ts: number;
    expires_ts?: number;
    [key: string]: unknown;
}

/** GET /_matrix/client/v1/widgets/{widgetId}/config response. */
export interface WidgetConfigResponseDto {
    [key: string]: unknown;
}

/** GET /_matrix/client/v1/rooms/{roomId}/widgets/jitsi/config response. */
export interface WidgetJitsiConfigResponseDto {
    [key: string]: unknown;
}
