/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Widget 模块契约
 * Source:        docs/api-contract/generated/modules/widget.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  52743253bdca3fa83ea774744e15c917ae07bbfd
 */

/** Routes served by the synapse-rust `widget` module. */
export const WIDGET_ROUTES = [
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/widgets" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/widgets/jitsi/config" },
    { method: "POST", path: "/_matrix/client/v1/widgets" },
    { method: "DELETE", path: "/_matrix/client/v1/widgets/sessions/{session_id}" },
    { method: "GET", path: "/_matrix/client/v1/widgets/sessions/{session_id}" },
    { method: "DELETE", path: "/_matrix/client/v1/widgets/{widget_id}" },
    { method: "GET", path: "/_matrix/client/v1/widgets/{widget_id}" },
    { method: "PUT", path: "/_matrix/client/v1/widgets/{widget_id}" },
    { method: "GET", path: "/_matrix/client/v1/widgets/{widget_id}/config" },
    { method: "GET", path: "/_matrix/client/v1/widgets/{widget_id}/permissions" },
    { method: "POST", path: "/_matrix/client/v1/widgets/{widget_id}/permissions" },
    { method: "DELETE", path: "/_matrix/client/v1/widgets/{widget_id}/permissions/{user_id}" },
    { method: "GET", path: "/_matrix/client/v1/widgets/{widget_id}/sessions" },
    { method: "POST", path: "/_matrix/client/v1/widgets/{widget_id}/sessions" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/widgets/{widget_id}/capabilities" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/widgets/{widget_id}/capabilities" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/widgets/{widget_id}/send" },
    { method: "POST", path: "/_matrix/client/v3/widgets/create" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `WIDGET_ROUTES`. */
export type WidgetRoute = (typeof WIDGET_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type WidgetMethod = WidgetRoute["method"];

/** Path templates referenced by this module. */
export type WidgetPath = WidgetRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type WidgetReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${WidgetReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type WidgetPathPattern = WidgetReplaceBraces<WidgetPath>;
