/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/device.json
 */

import { DEVICE_ROUTES } from "./route-table";

export const DEVICE_ROUTES_ENTRY_COUNT = 12 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _DeviceEntryCountAssertion: 12 = DEVICE_ROUTES.length;
void _DeviceEntryCountAssertion;

export const DEVICE_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "缺少 display_name 或 device_ids/users 格式错误" },
    { status: 404, note: "设备不存在" },
] as const;

export type DeviceStatusScenario = (typeof DEVICE_ROUTES_STATUS_SCENARIOS)[number];

export const DEVICE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type DeviceErrorScenario = (typeof DEVICE_ROUTES_ERROR_SCENARIOS)[number];

export const DEVICE_ROUTES_ERRCODES = [
] as const;

export type DeviceErrcode = (typeof DEVICE_ROUTES_ERRCODES)[number];
