// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/device.md

// ─── Device Info ──────────────────────────────────────────────

/** Device information */
export interface DeviceInfo {
    /** Device ID */
    device_id: string;
    /** Display name of the device */
    display_name?: string;
    /** IP address of the device's last session */
    last_seen_ip?: string;
    /** Timestamp of the device's last activity (ms) */
    last_seen_ts?: number;
    /** User ID that owns the device */
    user_id?: string;
}

// ─── Device List ──────────────────────────────────────────────

/** Response from GET /devices */
export interface DeviceListResponse {
    /** List of devices */
    devices: DeviceInfo[];
}

// ─── Update Device ────────────────────────────────────────────

/** Request body for PUT /devices/{deviceId} */
export interface UpdateDeviceRequest {
    /** New display name for the device */
    display_name?: string;
}

// ─── Delete Device ────────────────────────────────────────────

/** UIA auth dictionary for device deletion */
export interface AuthDict {
    /** Auth type (e.g. "m.login.password") */
    type: string;
    /** UIA session token */
    session?: string;
    /** Additional auth fields */
    [key: string]: unknown;
}

/** Request body for DELETE /devices/{deviceId} */
export interface DeleteDeviceRequest {
    /** UIA auth data (required for the first request, optional on retry with session) */
    auth?: AuthDict;
}

// ─── Batch Delete Devices ─────────────────────────────────────

/** Request body for POST /delete_devices */
export interface DeleteDevicesRequest {
    /** List of device IDs to delete */
    devices: string[];
    /** UIA auth data */
    auth?: AuthDict;
}

// ─── Device List Updates ──────────────────────────────────────

/** Device data in a list update */
export interface DeviceData {
    /** Display name */
    display_name?: string;
    /** Last seen timestamp */
    last_seen_ts?: number;
    /** Last seen IP */
    last_seen_ip?: string;
}

/** A single device change entry */
export interface DeviceChange {
    /** User ID */
    user_id: string;
    /** Device ID */
    device_id: string;
    /** Updated device data */
    device_data: DeviceData;
}

/** Request body for POST /keys/device_list_updates */
export interface DeviceListUpdatesRequest {
    /** User IDs to query for device list changes */
    users: string[];
}

/** Response from POST /keys/device_list_updates */
export interface DeviceListUpdatesResponse {
    /** Devices that have changed */
    changed: DeviceChange[];
    /** Users who have left */
    left: string[];
}
