/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { PRESENCE_ROUTES } from "./route-table";

export const PRESENCE_ROUTES_ENTRY_COUNT = 11 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _PresenceEntryCountAssertion: 11 = PRESENCE_ROUTES.length;
void _PresenceEntryCountAssertion;

export const PRESENCE_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "presence 状态值不合法或消息过长" },
    { status: 401, note: "Token 无效或缺失" },
    { status: 403, note: "尝试读取/修改其他用户状态，或读取他人订阅表" },
    { status: 404, note: "GET /presence/{user_id}/status 的目标用户不存在" },
] as const;

export type PresenceStatusScenario = (typeof PRESENCE_ROUTES_STATUS_SCENARIOS)[number];

export const PRESENCE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type PresenceErrorScenario = (typeof PRESENCE_ROUTES_ERROR_SCENARIOS)[number];

export const PRESENCE_ROUTES_ERRCODES = [
] as const;

export type PresenceErrcode = (typeof PRESENCE_ROUTES_ERRCODES)[number];
