/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Presence 模块契约
 * Source:        docs/api-contract/generated/modules/presence.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  4ea2cc71c82770204c71aba66cead18f43c74b8e
 */

/** Routes served by the synapse-rust `presence` module. */
export const PRESENCE_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/presence/{user_id}/status" },
    { method: "POST", path: "/_matrix/client/r0/presence/{user_id}/status" },
    { method: "PUT", path: "/_matrix/client/r0/presence/{user_id}/status" },
    { method: "GET", path: "/_matrix/client/v1/presence/{user_id}/status" },
    { method: "POST", path: "/_matrix/client/v1/presence/{user_id}/status" },
    { method: "PUT", path: "/_matrix/client/v1/presence/{user_id}/status" },
    { method: "POST", path: "/_matrix/client/v3/presence/list" },
    { method: "GET", path: "/_matrix/client/v3/presence/list/{user_id}" },
    { method: "GET", path: "/_matrix/client/v3/presence/{user_id}/status" },
    { method: "POST", path: "/_matrix/client/v3/presence/{user_id}/status" },
    { method: "PUT", path: "/_matrix/client/v3/presence/{user_id}/status" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `PRESENCE_ROUTES`. */
export type PresenceRoute = (typeof PRESENCE_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type PresenceMethod = PresenceRoute["method"];

/** Path templates referenced by this module. */
export type PresencePath = PresenceRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type PresenceReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${PresenceReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type PresencePathPattern = PresenceReplaceBraces<PresencePath>;
