/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/worker.json
 */

import { WORKER_ADMIN_ROUTES } from "./route-table";

export const WORKER_ADMIN_ROUTES_ENTRY_COUNT = 15 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _WorkerAdminEntryCountAssertion: 15 = WORKER_ADMIN_ROUTES.length;
void _WorkerAdminEntryCountAssertion;

export const WORKER_ADMIN_ROUTES_STATUS_SCENARIOS = [
] as const;

export type WorkerAdminStatusScenario = (typeof WORKER_ADMIN_ROUTES_STATUS_SCENARIOS)[number];

export const WORKER_ADMIN_ROUTES_ERROR_SCENARIOS = [
] as const;

export type WorkerAdminErrorScenario = (typeof WORKER_ADMIN_ROUTES_ERROR_SCENARIOS)[number];

export const WORKER_ADMIN_ROUTES_ERRCODES = [
] as const;

export type WorkerAdminErrcode = (typeof WORKER_ADMIN_ROUTES_ERRCODES)[number];
