/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/worker-admin.md
 */

/**
 * DTO snippets extracted from the contract doc for `worker-admin`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export type WorkerAdminContractDtoPlaceholder = never;
