/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Worker Admin 模块契约
 * Source:        docs/api-contract/generated/modules/worker.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  b3c5153fc5fa969a2caa04d8e506b18655b349a6
 */

/** Routes served by the synapse-rust `worker` module. */
export const WORKER_ADMIN_ROUTES = [
    { method: "POST", path: "/_synapse/worker/v1/register" },
    { method: "GET", path: "/_synapse/worker/v1/select/{task_type}" },
    { method: "GET", path: "/_synapse/worker/v1/statistics" },
    { method: "GET", path: "/_synapse/worker/v1/statistics/types" },
    { method: "GET", path: "/_synapse/worker/v1/tasks" },
    { method: "POST", path: "/_synapse/worker/v1/tasks" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/claim/{worker_id}" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/{task_id}/claim/{worker_id}" },
    { method: "GET", path: "/_synapse/worker/v1/workers" },
    { method: "GET", path: "/_synapse/worker/v1/workers/type/{worker_type}" },
    { method: "DELETE", path: "/_synapse/worker/v1/workers/{worker_id}" },
    { method: "GET", path: "/_synapse/worker/v1/workers/{worker_id}" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/commands" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `WORKER_ADMIN_ROUTES`. */
export type WorkerAdminRoute = (typeof WORKER_ADMIN_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type WorkerAdminMethod = WorkerAdminRoute["method"];

/** Path templates referenced by this module. */
export type WorkerAdminPath = WorkerAdminRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type WorkerAdminReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${WorkerAdminReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type WorkerAdminPathPattern = WorkerAdminReplaceBraces<WorkerAdminPath>;
