/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Worker Admin 模块契约
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       26 (authoritative set mirrored from the backend contract)
 */

/** Routes served by the synapse-rust `worker-admin` module (mirrored from the backend contract). */
export const WORKER_ADMIN_ROUTES = [
    { method: "POST", path: "/_synapse/worker/v1/register" },
    { method: "GET", path: "/_synapse/worker/v1/select/{task_type}" },
    { method: "GET", path: "/_synapse/worker/v1/statistics" },
    { method: "GET", path: "/_synapse/worker/v1/statistics/types" },
    { method: "GET", path: "/_synapse/worker/v1/tasks" },
    { method: "POST", path: "/_synapse/worker/v1/tasks" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/claim/{worker_id}" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/{task_id}/claim/{worker_id}" },
    { method: "GET", path: "/_synapse/worker/v1/topology" },
    { method: "GET", path: "/_synapse/worker/v1/topology/validate" },
    { method: "GET", path: "/_synapse/worker/v1/workers" },
    { method: "GET", path: "/_synapse/worker/v1/workers/type/{worker_type}" },
    { method: "DELETE", path: "/_synapse/worker/v1/workers/{worker_id}" },
    { method: "GET", path: "/_synapse/worker/v1/workers/{worker_id}" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/commands" },
    { method: "GET", path: "/_synapse/worker/v1/events" },
    { method: "GET", path: "/_synapse/worker/v1/replication/{worker_id}/position" },
    { method: "GET", path: "/_synapse/worker/v1/workers/{worker_id}/commands" },
    { method: "POST", path: "/_synapse/worker/v1/commands/{command_id}/complete" },
    { method: "POST", path: "/_synapse/worker/v1/commands/{command_id}/fail" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/{task_id}/complete" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/{task_id}/fail" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/connect" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/disconnect" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/heartbeat" },
    { method: "PUT", path: "/_synapse/worker/v1/replication/{worker_id}/{stream_name}" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `WORKER_ADMIN_ROUTES`. */
export type WorkerAdminRoute = (typeof WORKER_ADMIN_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type WorkerAdminMethod = WorkerAdminRoute["method"];

/** Path templates referenced by this module. */
export type WorkerAdminPath = WorkerAdminRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type WorkerAdminReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${WorkerAdminReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type WorkerAdminPathPattern = WorkerAdminReplaceBraces<WorkerAdminPath>;
