/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/guest.json
 */

import { GUEST_ROUTES } from "./route-table";

export const GUEST_ROUTES_ENTRY_COUNT = 3 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _GuestEntryCountAssertion: 3 = GUEST_ROUTES.length;
void _GuestEntryCountAssertion;

export const GUEST_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "访客注册成功" },
    { status: 400, note: "注册参数、请求体或 kind 查询参数非法" },
    { status: 403, note: "服务器禁用访客注册" },
    { status: 429, note: "访客注册被限流" },
] as const;

export type GuestStatusScenario = (typeof GUEST_ROUTES_STATUS_SCENARIOS)[number];

export const GUEST_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "访客注册参数不合法",
        httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM",
        sdkErrorType: "ApiError",
        handling: "修正注册请求体或确保 kind=guest 后重试",
    },
    {
        scenario: "服务器禁用访客注册",
        httpOrErrcode: "403 / M_FORBIDDEN",
        sdkErrorType: "ApiError",
        handling: "改走普通注册或联系服务器管理员开启 guest 模式",
    },
    {
        scenario: "访客注册触发限流",
        httpOrErrcode: "429 / M_LIMIT_EXCEEDED",
        sdkErrorType: "RetryableError",
        handling: "按 retry_after_ms 退避后重试",
    },
] as const;

export type GuestErrorScenario = (typeof GUEST_ROUTES_ERROR_SCENARIOS)[number];

export const GUEST_ROUTES_ERRCODES = [
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "访客注册请求体结构不合法" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "注册参数或 kind 查询参数非法" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "服务器禁用访客注册" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "访客注册被限流" },
] as const;

export type GuestErrcode = (typeof GUEST_ROUTES_ERRCODES)[number];
