/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/guest.json
 */

import { GUEST_ROUTES } from "./route-table";

export const GUEST_ROUTES_ENTRY_COUNT = 3 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _GuestEntryCountAssertion: 3 = GUEST_ROUTES.length;
void _GuestEntryCountAssertion;

export const GUEST_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "升级请求参数不合法，例如用户名或密码长度校验失败" },
    { status: 403, note: "服务器禁用注册，或当前用户不是 guest" },
    { status: 409, note: "升级为正式账号时用户名已存在" },
    { status: 500, note: "创建 guest 用户、设备或 token 失败" },
] as const;

export type GuestStatusScenario = (typeof GUEST_ROUTES_STATUS_SCENARIOS)[number];

export const GUEST_ROUTES_ERROR_SCENARIOS = [
    { scenario: "服务器禁用注册", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "改走普通注册或联系管理员开启注册" },
    { scenario: "当前用户不是 guest", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "不要对正式账号调用 guest 升级接口" },
    { scenario: "升级参数校验失败", httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "修正 username / password 后重试" },
    { scenario: "升级用户名冲突", httpOrErrcode: "409 / M_CONFLICT", sdkErrorType: "ApiError", handling: "更换用户名" },
] as const;

export type GuestErrorScenario = (typeof GUEST_ROUTES_ERROR_SCENARIOS)[number];

export const GUEST_ROUTES_ERRCODES = [
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "升级请求体结构不合法或校验失败" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "用户名或密码不符合要求" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "服务器禁用注册或当前用户不是 guest" },
    { errcode: "M_CONFLICT", httpStatus: "409", note: "用户名已存在" },
] as const;

export type GuestErrcode = (typeof GUEST_ROUTES_ERRCODES)[number];
