/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        访客契约
 * Source:        docs/api-contract/generated/modules/guest.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  52743253bdca3fa83ea774744e15c917ae07bbfd
 */

/** Routes served by the synapse-rust `guest` module. */
export const GUEST_ROUTES = [
    { method: "GET", path: "/_matrix/client/v3/account/guest" },
    { method: "POST", path: "/_matrix/client/v3/account/guest/upgrade" },
    { method: "POST", path: "/_matrix/client/v3/register/guest" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `GUEST_ROUTES`. */
export type GuestRoute = (typeof GUEST_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type GuestMethod = GuestRoute["method"];

/** Path templates referenced by this module. */
export type GuestPath = GuestRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type GuestReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${GuestReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type GuestPathPattern = GuestReplaceBraces<GuestPath>;
