// AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.

import { AI_CONNECTION_ROUTES } from "./route-table";

export const AI_CONNECTION_ROUTES_ENTRY_COUNT = 6;
const _AiConnectionEntryCountAssertion: 6 = AI_CONNECTION_ROUTES.length;
void _AiConnectionEntryCountAssertion;
