/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/ai_connection.json
 */

import { AI_CONNECTION_ROUTES } from "./route-table";

export const AI_CONNECTION_ROUTES_ENTRY_COUNT = 12 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _AiConnectionEntryCountAssertion: 12 = AI_CONNECTION_ROUTES.length;
void _AiConnectionEntryCountAssertion;

export const AI_CONNECTION_ROUTES_STATUS_SCENARIOS = [
    { status: 202, note: "修正文档中错误的路径前缀、字段命名与 MCP 请求/响应口径，并补充 SDK 生成路由绑定说明 | 修复长期文档漂移" },
    { status: 202, note: "初版 | -" },
] as const;

export type AiConnectionStatusScenario = (typeof AI_CONNECTION_ROUTES_STATUS_SCENARIOS)[number];

export const AI_CONNECTION_ROUTES_ERROR_SCENARIOS = [
] as const;

export type AiConnectionErrorScenario = (typeof AI_CONNECTION_ROUTES_ERROR_SCENARIOS)[number];

export const AI_CONNECTION_ROUTES_ERRCODES = [
] as const;

export type AiConnectionErrcode = (typeof AI_CONNECTION_ROUTES_ERRCODES)[number];
