/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/ai-connection.md
 */

/**
 * DTO snippets extracted from the contract doc for `ai_connection`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface AIConnectionConfig {
    api_key?: string;
    model_id?: string;
    base_url?: string;
    max_tokens?: number;
    temperature?: number;
    [key: string]: unknown;
}

export interface AIConnection {
    id: string;
    user_id: string;
    provider: string;
    config: AIConnectionConfig | null;
    is_active: boolean;
    created_ts: number;
    updated_ts: number | null;
}

export interface CreateConnectionOptions {
    provider: string;
    config?: AIConnectionConfig;
}

export interface McpToolCallRequest {
    provider: string;
    tool_name: string;
    arguments: Record<string, string | number | boolean | null>;
}
