// AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.

export interface AiConnectionDto {
    id: string;
    user_id: string;
    provider: string;
    config?: Record<string, unknown>;
    is_active: boolean;
    created_ts: number;
    updated_ts?: number;
}

export interface CreateConnectionRequestDto {
    provider: string;
    config?: Record<string, unknown>;
}

export interface McpToolCallRequestDto {
    provider: string;
    tool_name: string;
    arguments: Record<string, unknown>;
}
