/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        AI Connection
 * Source:        docs/api-contract/generated/modules/ai_connection.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  4ea2cc71c82770204c71aba66cead18f43c74b8e
 */

/** Routes served by the synapse-rust `ai_connection` module. */
export const AI_CONNECTION_ROUTES = [
    { method: "GET", path: "/_matrix/client/v1/ai/connections" },
    { method: "POST", path: "/_matrix/client/v1/ai/connections" },
    { method: "DELETE", path: "/_matrix/client/v1/ai/connections/{id}" },
    { method: "GET", path: "/_matrix/client/v1/ai/connections/{id}" },
    { method: "GET", path: "/_matrix/client/v1/ai/mcp/tools" },
    { method: "POST", path: "/_matrix/client/v1/ai/mcp/tools/call" },
    { method: "GET", path: "/_matrix/client/v3/ai/connections" },
    { method: "POST", path: "/_matrix/client/v3/ai/connections" },
    { method: "DELETE", path: "/_matrix/client/v3/ai/connections/{id}" },
    { method: "GET", path: "/_matrix/client/v3/ai/connections/{id}" },
    { method: "GET", path: "/_matrix/client/v3/ai/mcp/tools" },
    { method: "POST", path: "/_matrix/client/v3/ai/mcp/tools/call" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `AI_CONNECTION_ROUTES`. */
export type AiConnectionRoute = (typeof AI_CONNECTION_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type AiConnectionMethod = AiConnectionRoute["method"];

/** Path templates referenced by this module. */
export type AiConnectionPath = AiConnectionRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type AiConnectionReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${AiConnectionReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type AiConnectionPathPattern = AiConnectionReplaceBraces<AiConnectionPath>;
