// AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.

export const AI_CONNECTION_ROUTES = [
    { method: "GET", path: "/connections" },
    { method: "POST", path: "/connections" },
    { method: "GET", path: "/connections/{id}" },
    { method: "DELETE", path: "/connections/{id}" },
    { method: "GET", path: "/mcp/tools" },
    { method: "POST", path: "/mcp/tools/call" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

export type AiConnectionRoute = (typeof AI_CONNECTION_ROUTES)[number];
export type AiConnectionMethod = AiConnectionRoute["method"];
export type AiConnectionPath = AiConnectionRoute["path"];
export type AiConnectionReplaceBraces<P extends string> = P extends `${infer Before}{${infer _Param}}${infer After}`
    ? `${Before}${string}${AiConnectionReplaceBraces<After>}`
    : P;
export type AiConnectionPathPattern = AiConnectionReplaceBraces<AiConnectionPath>;
