/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { PUSH_ROUTES } from "./route-table";

export const PUSH_ROUTES_ENTRY_COUNT = 37 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _PushEntryCountAssertion: 37 = PUSH_ROUTES.length;
void _PushEntryCountAssertion;

export const PUSH_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "请求体不合法" },
    { status: 401, note: "Token 无效或缺失" },
    { status: 404, note: "规则或通知不存在" },
] as const;

export type PushStatusScenario = (typeof PUSH_ROUTES_STATUS_SCENARIOS)[number];

export const PUSH_ROUTES_ERROR_SCENARIOS = [
    { scenario: "未认证或 token 失效", httpOrErrcode: "401 / M_UNKNOWN_TOKEN", sdkErrorType: "AuthError", handling: "触发登录态恢复流程，不继续提交规则写入" },
    { scenario: "规则或通知不存在", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "视为目标已不存在，刷新本地规则快照" },
    { scenario: "参数或规则定义非法", httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "修正 actions/conditions/pattern 后重试" },
    { scenario: "无权限修改目标规则", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "终止重试并提示权限不足" },
    { scenario: "限流或短暂服务异常", httpOrErrcode: "429 / M_LIMIT_EXCEEDED，5xx", sdkErrorType: "RetryableError", handling: "使用指数退避重试" },
    { scenario: "其他 API 错误", httpOrErrcode: "其他 4xx/5xx", sdkErrorType: "ApiError", handling: "按 code 与 statusCode 处理兜底" },
] as const;

export type PushErrorScenario = (typeof PUSH_ROUTES_ERROR_SCENARIOS)[number];

export const PUSH_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "access token 无效、过期或缺失" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "push rule 或 notification 不存在" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "无权限写入或删除规则" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "请求体结构不合法" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "参数取值非法或规则字段冲突" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "触发限流" },
] as const;

export type PushErrcode = (typeof PUSH_ROUTES_ERRCODES)[number];
