// Auto-generated by contract:codegen. Do not edit manually.

/** GET /_matrix/client/v3/pushers response — wrapper containing the pusher list. */
export interface PushersResponse {
    pushers: Pusher[];
}

/** A single pusher as returned by the server. */
export interface Pusher {
    pushkey: string;
    kind: string | null;
    app_id: string;
    app_display_name: string;
    device_display_name: string;
    profile_tag?: string;
    lang: string;
    data?: PusherData;
    enabled?: boolean;
    device_id?: string;
}

/** Pusher data payload (platform-specific). */
export interface PusherData {
    url?: string;
    format?: string;
    default_payload?: Record<string, unknown>;
    [key: string]: unknown;
}

/** POST /_matrix/client/v3/pushers/set request body. */
export interface PusherRequest {
    pushkey: string;
    kind?: string | null;
    app_id: string;
    app_display_name: string;
    device_display_name: string;
    profile_tag?: string;
    lang: string;
    data?: PusherData;
    append?: boolean;
}

/** GET /_matrix/client/v3/pushrules response — the full push ruleset. */
export interface PushRulesResponse {
    global?: PushRuleSet;
    device?: PushRuleSet;
}

/** A set of push rule collections grouped by kind. */
export interface PushRuleSet {
    override?: PushRule[];
    content?: PushRule[];
    room?: PushRule[];
    sender?: PushRule[];
    underride?: PushRule[];
}

/** A single push rule. */
export interface PushRule {
    rule_id: string;
    default: boolean;
    enabled: boolean;
    pattern?: string;
    conditions?: PushRuleCondition[];
    actions: PushRuleAction[];
}

/** Push rule action — either a named action or a tweak. */
export type PushRuleAction = PushRuleActionName | PushRuleTweak;

/** Named push rule actions. */
export type PushRuleActionName = "notify" | "dont_notify" | "coalesce";

/** A tweak action within a push rule. */
export interface PushRuleTweak {
    set_tweak: string;
    value?: unknown;
}

/** A condition that must hold for a push rule to apply. */
export interface PushRuleCondition {
    kind: string;
    key?: string;
    pattern?: string;
    is?: string;
    [key: string]: unknown;
}

/** POST /_matrix/client/v3/pushrules/{scope}/{kind}/{ruleId} request body for creating a rule. */
export interface CreatePushRuleRequest {
    actions: PushRuleAction[];
    conditions?: PushRuleCondition[];
    pattern?: string;
    before?: string;
    after?: string;
}

/** PUT /_matrix/client/v3/pushrules/{scope}/{kind}/{ruleId} request body for updating a rule. */
export interface UpdatePushRuleRequest {
    actions: PushRuleAction[];
    conditions?: PushRuleCondition[];
    pattern?: string;
}

/** GET /_matrix/client/v3/pushrules/{scope}/{kind}/{ruleId}/enabled response. */
export interface PushRuleEnabledResponse {
    enabled: boolean;
}

/** PUT /_matrix/client/v3/pushrules/{scope}/{kind}/{ruleId}/actions request body. */
export interface SetPushRuleActionsRequest {
    actions: PushRuleAction[];
}

/** GET /_matrix/client/v3/notifications response. */
export interface NotificationsResponse {
    notifications: Notification[];
    next_token?: string;
}

/** A single notification entry. */
export interface Notification {
    event_id: string;
    room_id: string;
    ts: number;
    profile_tag?: string;
    read: boolean;
    event?: Record<string, unknown>;
}
