/*
Copyright 2024 The Matrix.org Foundation C.I.C.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/**
 * Manager Extensions - 统一的 Manager 初始化入口
 *
 * 提供统一的接口来初始化所有或部分的 Manager 扩展
 * 使用方式：
 *
 * @example
 * // 初始化所有核心 Manager
 * import { extendMatrixClientWithManagers } from "./manager-extensions";
 * extendMatrixClientWithManagers();
 *
 * const client = createClient({ ... });
 * const admin = client.getAdminManager();
 * const dm = client.getDirectMessageManager();
 *
 * THIS FILE IS AUTO-GENERATED by scripts/generate-manager-extensions.mjs.
 * DO NOT EDIT MANUALLY. To add a new manager extension, edit the script instead.
 */

import type { ManagerExtensionsOptions, ManagerExtensionsLifecycleEvent, ManagerExtensionsLifecycleListener } from "./types.js";

const MANAGER_EXTENSION_MODULES: Array<{
    option: Exclude<keyof ManagerExtensionsOptions, "includeAll">;
    module: string;
}> = [
    { option: "includeAdmin", module: "admin" },
    { option: "includeAccount", module: "account" },
    { option: "includeAccountData", module: "account-data" },
    { option: "includeAuth", module: "auth" },
    { option: "includeCapabilities", module: "capabilities" },
    { option: "includeCryptoKeys", module: "crypto-keys" },
    { option: "includeKeyVerification", module: "key-verification" },
    { option: "includeDeviceTrust", module: "device-trust" },
    { option: "includeDiscovery", module: "discovery" },
    { option: "includeGlobalLogout", module: "global-logout" },
    { option: "includeDm", module: "dm" },
    { option: "includeGuest", module: "guest" },
    { option: "includeInviteBlocklist", module: "invite-blocklist" },
    { option: "includeMedia", module: "media" },
    { option: "includePush", module: "push" },
    { option: "includeQrLogin", module: "qr-login" },
    { option: "includeRoom", module: "room" },
    { option: "includeRoomKeySharing", module: "room-key-sharing" },
    { option: "includeRoomSummary", module: "room-summary" },
    { option: "includeRoomList", module: "room-list" },
    { option: "includeSecurity", module: "security" },
    { option: "includeStickyEvent", module: "sticky-event" },
    { option: "includeFriend", module: "friend" },
    { option: "includeSpace", module: "space" },
    { option: "includeSending", module: "sending" },
    { option: "includePresence", module: "presence" },
    { option: "includeFederation", module: "federation" },
    { option: "includeDevice", module: "device" },
    { option: "includeProfile", module: "profile" },
    { option: "includeSecureBackup", module: "secure-backup" },
    { option: "includeThirdParty", module: "thirdparty" },
    { option: "includeOidc", module: "oidc" },
    { option: "includeTelemetry", module: "telemetry" },
    { option: "includeRendezvous", module: "rendezvous" },
    { option: "includeTyping", module: "typing" },
    { option: "includeUser", module: "user" },
    { option: "includeUserReport", module: "user-report" },
    { option: "includeThreePids", module: "threepids" },
    { option: "includeIdentityServer", module: "identity-server" },
    { option: "includePasswordReset", module: "password-reset" },
    { option: "includeThreading", module: "threading" },
    { option: "includeStateSend", module: "state-send" },
    { option: "includeRelations", module: "relations" },
    { option: "includeTimeline", module: "timeline" },
    { option: "includeModeration", module: "moderation" },
    { option: "includeKeyRotation", module: "key-rotation" },
    { option: "includeKeyBackup", module: "key-backup" },
    { option: "includeFeatureFlag", module: "feature-flags" },
    { option: "includeEventReport", module: "event-report" },
    { option: "includeBurnAfterRead", module: "burn-after-read" },
    { option: "includeVerification", module: "verification" },
    { option: "includeE2EE", module: "e2ee" },
    { option: "includeWorkerBody", module: "worker-body" },
    { option: "includeAiConnection", module: "ai-connection" },
    { option: "includeOpenClaw", module: "openclaw" },
    { option: "includeVoice", module: "voice" },
    { option: "includeSamlAuth", module: "saml" },
    { option: "includeCredentials", module: "credentials" },
    { option: "includeCas", module: "cas" },
    { option: "includeExternalService", module: "external-service" },
    { option: "includeDehydratedDevice", module: "dehydrated-device" },
    { option: "includeThread", module: "thread" },
    { option: "includeWidget", module: "widget" },

    { option: "includeServerCapabilities", module: "server-capabilities" },
    { option: "includeSyncManagement", module: "sync-management" },
    { option: "includeFilter", module: "filter" },
    { option: "includeToDevice", module: "to-device" },
    { option: "includeTurnServer", module: "turn-server" },
    { option: "includeSearch", module: "search" },
    { option: "includeReporting", module: "reporting" },
    { option: "includeReadReceipts", module: "read-receipts" },
    { option: "includeNotifications", module: "notifications" },
    { option: "includeCryptoBackup", module: "crypto-backup" },
    { option: "includeTagsManagement", module: "tags-management" },
    { option: "includeSecretStorage", module: "secret-storage" },
    { option: "includeCrossSigning", module: "cross-signing" },
    { option: "includeRoomSettings", module: "room-settings" },
    { option: "includeRoomState", module: "room-state" },
    { option: "includeServerTime", module: "server-time" },
    { option: "includeVoipCalls", module: "voip-calls" },
    { option: "includeRoomAccountData", module: "room-account-data" },
    { option: "includeBackgroundUpdate", module: "background-update" },
    { option: "includeUserDirectory", module: "user-directory" },
];

const DEFAULT_CORE_EXTENSIONS: ManagerExtensionsOptions = {
    includeAdmin: true,
    includeAccount: true,
    includeAccountData: true,
    includeAuth: true,
    includeCapabilities: true,
    includeCryptoKeys: true,
    includeKeyVerification: true,
    includeDeviceTrust: true,
    includeDiscovery: true,
    includeGlobalLogout: true,
    includeDm: true,
    includeGuest: true,
    includeInviteBlocklist: true,
    includeMedia: true,
    includePush: true,
    includeQrLogin: true,
    includeRoom: true,
    includeRoomKeySharing: true,
    includeRoomSummary: true,
    includeRoomList: true,
    includeSecurity: true,
    includeStickyEvent: true,
    includeFriend: true,
    includeSpace: true,
    includeSending: true,
    includePresence: true,
    includeFederation: true,
    includeDevice: true,
    includeProfile: true,
    includeSecureBackup: true,
    includeThirdParty: true,
    includeOidc: true,
    includeTelemetry: true,
    includeRendezvous: true,
    includeTyping: true,
    includeUser: true,
    includeUserReport: true,
    includeThreePids: true,
    includeIdentityServer: true,
    includePasswordReset: true,
    includeThreading: true,
    includeStateSend: true,
    includeRelations: true,
    includeTimeline: true,
    includeModeration: true,
    includeKeyRotation: true,
    includeKeyBackup: true,
    includeFeatureFlag: true,
    includeEventReport: true,
    includeBurnAfterRead: true,
    includeVerification: true,
    includeE2EE: true,
    includeWorkerBody: true,
    includeAiConnection: true,
    includeOpenClaw: true,
    includeVoice: true,
    includeSamlAuth: true,
    includeCredentials: true,
    includeCas: true,
    includeExternalService: true,
    includeDehydratedDevice: true,
    includeThread: true,
    includeWidget: true,

    includeServerCapabilities: true,
    includeSyncManagement: true,
    includeFilter: true,
    includeToDevice: true,
    includeTurnServer: true,
    includeSearch: true,
    includeReporting: true,
    includeReadReceipts: true,
    includeNotifications: true,
    includeCryptoBackup: true,
    includeTagsManagement: true,
    includeSecretStorage: true,
    includeCrossSigning: true,
    includeRoomSettings: true,
    includeRoomState: true,
    includeServerTime: true,
    includeVoipCalls: true,
    includeRoomAccountData: true,
    includeBackgroundUpdate: true,
    includeUserDirectory: true,
};

let isInitialized = false;
let currentOptions: ManagerExtensionsOptions = {};
let initializationPromise: Promise<void> | null = null;
const lifecycleListeners = new Set<ManagerExtensionsLifecycleListener>();

function emitLifecycleEvent(event: ManagerExtensionsLifecycleEvent): void {
    for (const listener of lifecycleListeners) {
        try {
            listener(event);
        } catch {
            continue;
        }
    }
}

/**
 * Wraps a dynamic import promise to gracefully handle EnvironmentTeardownError
 * that can occur when Vitest tears down the test environment before the import
 * resolves. Returns undefined instead of throwing in that case.
 */
function safeDynamicImport<T>(importPromise: Promise<T>): Promise<T | undefined> {
    return importPromise.catch((error: unknown) => {
        if (error instanceof Error && error.name === "EnvironmentTeardownError") {
            return undefined;
        }
        throw error;
    });
}

function getEnabledModules(options: ManagerExtensionsOptions): string[] {
    const all = options.includeAll ?? false;
    return MANAGER_EXTENSION_MODULES.filter(({ option }) => all || options[option]).map(({ module }) => module);
}

export function onManagerExtensionsLifecycle(listener: ManagerExtensionsLifecycleListener): () => void {
    lifecycleListeners.add(listener);
    return () => offManagerExtensionsLifecycle(listener);
}

export function offManagerExtensionsLifecycle(listener: ManagerExtensionsLifecycleListener): void {
    lifecycleListeners.delete(listener);
}

export async function extendMatrixClientWithManagers(
    options: ManagerExtensionsOptions = DEFAULT_CORE_EXTENSIONS,
): Promise<void> {
    if (isInitialized) {
        return;
    }
    if (initializationPromise) {
        return initializationPromise;
    }

    initializationPromise = (async (): Promise<void> => {
        currentOptions = { ...DEFAULT_CORE_EXTENSIONS, ...options };
        const all = currentOptions.includeAll ?? false;
        const enabledModules = getEnabledModules(currentOptions);
        emitLifecycleEvent({ phase: "register", status: "success", modules: enabledModules });
        emitLifecycleEvent({ phase: "init", status: "begin", modules: enabledModules });

        const promises: Promise<void | undefined>[] = [];

        try {
            // manager() accessor — must load first so the prototype method exists
            // before any registerManagerClass calls from other extendMatrixClient functions
            promises.push(safeDynamicImport(import("../client-infra/manager-accessor.js").then((m) => m?.extendMatrixClient())));

            if (currentOptions.includeAdmin || all) {
                promises.push(safeDynamicImport(import("../admin/index.js").then((m) => m?.extendMatrixClient())));
                promises.push(safeDynamicImport(import("../background-update/index.js").then((m) => m?.extendMatrixClient())));
                promises.push(safeDynamicImport(import("../worker-admin/index.js").then((m) => m?.extendMatrixClient())));
                promises.push(safeDynamicImport(import("../worker-body/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeAccount || all) {
                promises.push(safeDynamicImport(import("../account/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeAccountData || all) {
                promises.push(safeDynamicImport(import("../account-data/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeAuth || all) {
                promises.push(safeDynamicImport(import("../auth/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeCapabilities || all) {
                promises.push(safeDynamicImport(import("../capabilities/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeCryptoKeys || all) {
                promises.push(safeDynamicImport(import("../crypto-keys/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeKeyVerification || all) {
                promises.push(safeDynamicImport(import("../key-verification/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeDeviceTrust || all) {
                promises.push(safeDynamicImport(import("../device-trust/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeDiscovery || all) {
                promises.push(safeDynamicImport(import("../discovery/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeGlobalLogout || all) {
                promises.push(safeDynamicImport(import("../auth/global-logout.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeDm || all) {
                promises.push(safeDynamicImport(import("../dm/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeGuest || all) {
                promises.push(safeDynamicImport(import("../guest/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeInviteBlocklist || all) {
                promises.push(safeDynamicImport(import("../invite-blocklist/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeMedia || all) {
                promises.push(safeDynamicImport(import("../media/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includePush || all) {
                promises.push(safeDynamicImport(import("../push/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeQrLogin || all) {
                promises.push(safeDynamicImport(import("../qr-login/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRoom || all) {
                promises.push(safeDynamicImport(import("../room/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRoomKeySharing || all) {
                promises.push(safeDynamicImport(import("../room-key-sharing/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRoomSummary || all) {
                promises.push(safeDynamicImport(import("../room-summary/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRoomList || all) {
                promises.push(safeDynamicImport(import("../room-list/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeSecurity || all) {
                promises.push(safeDynamicImport(import("../security/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeStickyEvent || all) {
                promises.push(safeDynamicImport(import("../sticky-event/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeFriend || all) {
                promises.push(safeDynamicImport(import("../friend/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeSpace || all) {
                promises.push(safeDynamicImport(import("../space/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeSending || all) {
                promises.push(safeDynamicImport(import("../sending/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includePresence || all) {
                promises.push(safeDynamicImport(import("../presence/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeFederation || all) {
                promises.push(safeDynamicImport(import("../federation/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeDevice || all) {
                promises.push(safeDynamicImport(import("../device/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeProfile || all) {
                promises.push(safeDynamicImport(import("../profile/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeSecureBackup || all) {
                promises.push(safeDynamicImport(import("../secure-backup/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeThirdParty || all) {
                promises.push(safeDynamicImport(import("../third-party/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeOidc || all) {
                promises.push(safeDynamicImport(import("../oidc/manager.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeTelemetry || all) {
                promises.push(safeDynamicImport(import("../telemetry/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRendezvous || all) {
                promises.push(safeDynamicImport(import("../rendezvous/RendezvousManager.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeTyping || all) {
                promises.push(safeDynamicImport(import("../typing/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeUser || all) {
                promises.push(safeDynamicImport(import("../user/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeUserReport || all) {
                promises.push(safeDynamicImport(import("../user-report/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeThreePids || all) {
                promises.push(safeDynamicImport(import("../three-pids/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeIdentityServer || all) {
                promises.push(safeDynamicImport(import("../identity-server/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includePasswordReset || all) {
                promises.push(safeDynamicImport(import("../password-reset/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeThreading || all) {
                promises.push(safeDynamicImport(import("../threading/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeStateSend || all) {
                promises.push(safeDynamicImport(import("../state-send/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRelations || all) {
                promises.push(safeDynamicImport(import("../relations/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeTimeline || all) {
                promises.push(safeDynamicImport(import("../timeline/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeModeration || all) {
                promises.push(safeDynamicImport(import("../moderation/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeKeyRotation || all) {
                promises.push(safeDynamicImport(import("../key-rotation/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeKeyBackup || all) {
                promises.push(safeDynamicImport(import("../key-backup/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeFeatureFlag || all) {
                promises.push(safeDynamicImport(import("../feature-flags/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeEventReport || all) {
                promises.push(safeDynamicImport(import("../event-report/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeBurnAfterRead || all) {
                promises.push(safeDynamicImport(import("../burn-after-read/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeVerification || all) {
                promises.push(safeDynamicImport(import("../verification/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeE2EE || all) {
                promises.push(safeDynamicImport(import("../e2ee/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeAiConnection || all) {
                promises.push(safeDynamicImport(import("../ai-connection/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeOpenClaw || all) {
                promises.push(safeDynamicImport(import("../open-claw/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeVoice || all) {
                promises.push(safeDynamicImport(import("../voice/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeCredentials || all) {
                promises.push(safeDynamicImport(import("../credentials/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeCas || all) {
                promises.push(safeDynamicImport(import("../cas/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeExternalService || all) {
                promises.push(safeDynamicImport(import("../external-service/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeDehydratedDevice || all) {
                promises.push(safeDynamicImport(import("../dehydrated-device/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeThread || all) {
                promises.push(safeDynamicImport(import("../thread/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeWidget || all) {
                promises.push(safeDynamicImport(import("../widget/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeServerCapabilities || all) {
                promises.push(safeDynamicImport(import("../server-capabilities/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeSyncManagement || all) {
                promises.push(safeDynamicImport(import("../sync-management/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeFilter || all) {
                promises.push(safeDynamicImport(import("../filter/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeToDevice || all) {
                promises.push(safeDynamicImport(import("../to-device/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeTurnServer || all) {
                promises.push(safeDynamicImport(import("../turn-server/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeSearch || all) {
                promises.push(safeDynamicImport(import("../search/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeReporting || all) {
                promises.push(safeDynamicImport(import("../reporting/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeReadReceipts || all) {
                promises.push(safeDynamicImport(import("../read-receipts/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeNotifications || all) {
                promises.push(safeDynamicImport(import("../notifications/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeCryptoBackup || all) {
                promises.push(safeDynamicImport(import("../crypto-backup/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeTagsManagement || all) {
                promises.push(safeDynamicImport(import("../tags-management/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeSecretStorage || all) {
                promises.push(safeDynamicImport(import("../secret-storage/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeCrossSigning || all) {
                promises.push(safeDynamicImport(import("../cross-signing/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRoomSettings || all) {
                promises.push(safeDynamicImport(import("../room-settings/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRoomState || all) {
                promises.push(safeDynamicImport(import("../room-state/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeServerTime || all) {
                promises.push(safeDynamicImport(import("../server-time/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeVoipCalls || all) {
                promises.push(safeDynamicImport(import("../voip-calls/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeRoomAccountData || all) {
                promises.push(safeDynamicImport(import("../room-account-data/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeBackgroundUpdate || all) {
                promises.push(safeDynamicImport(import("../background-update/index.js").then((m) => m?.extendMatrixClient())));
            }

            if (currentOptions.includeUserDirectory || all) {
                promises.push(safeDynamicImport(import("../user-directory/index.js").then((m) => m?.extendMatrixClient())));
            }

            await Promise.all(promises);
            emitLifecycleEvent({ phase: "init", status: "success", modules: enabledModules });
            isInitialized = true;
            emitLifecycleEvent({ phase: "start", status: "success", modules: enabledModules });
        } catch (error) {
            emitLifecycleEvent({ phase: "init", status: "error", modules: enabledModules, error });
            throw error;
        }
    })();

    try {
        await initializationPromise;
    } finally {
        if (!isInitialized) {
            initializationPromise = null;
        }
    }
}

export function isManagerExtensionsInitialized(): boolean {
    return isInitialized;
}

export function resetManagerExtensions(): void {
    const enabledModules = getEnabledModules(currentOptions);
    emitLifecycleEvent({ phase: "stop", status: "success", modules: enabledModules });
    isInitialized = false;
    currentOptions = {};
    initializationPromise = null;
}

export { DEFAULT_CORE_EXTENSIONS };

export type {
    ManagerExtensionsOptions,
    ManagerExtensionsLifecyclePhase,
    ManagerExtensionsLifecycleStatus,
    ManagerExtensionsLifecycleEvent,
    ManagerExtensionsLifecycleListener,
} from "./types.js";
