/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/cas.json
 */

import { CAS_ROUTES } from "./route-table";

export const CAS_ROUTES_ENTRY_COUNT = 16 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _CasEntryCountAssertion: 16 = CAS_ROUTES.length;
void _CasEntryCountAssertion;

export const CAS_ROUTES_STATUS_SCENARIOS = [
] as const;

export type CasStatusScenario = (typeof CAS_ROUTES_STATUS_SCENARIOS)[number];

export const CAS_ROUTES_ERROR_SCENARIOS = [
] as const;

export type CasErrorScenario = (typeof CAS_ROUTES_ERROR_SCENARIOS)[number];

export const CAS_ROUTES_ERRCODES = [
] as const;

export type CasErrcode = (typeof CAS_ROUTES_ERRCODES)[number];
