/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/cas.json
 */

import { CAS_ROUTES } from "./route-table";

export const CAS_ROUTES_ENTRY_COUNT = 16 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _CasEntryCountAssertion: 16 = CAS_ROUTES.length;
void _CasEntryCountAssertion;

export const CAS_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "服务验证、代理验证或管理查询成功" },
    { status: 302, note: "登录或登出流程发生重定向" },
    { status: 400, note: "service、ticket 或管理查询参数不合法" },
    { status: 401, note: "CAS ticket 无效、过期或缺失" },
    { status: 403, note: "管理端点权限不足" },
    { status: 404, note: "目标用户属性或服务配置不存在" },
    { status: 202, note: "初版 | -" },
] as const;

export type CasStatusScenario = (typeof CAS_ROUTES_STATUS_SCENARIOS)[number];

export const CAS_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "CAS ticket 无效或失效",
        httpOrErrcode: "401 / M_UNKNOWN_TOKEN",
        sdkErrorType: "AuthError",
        handling: "重新发起 CAS 登录获取新 ticket",
    },
    {
        scenario: "服务地址或校验参数不合法",
        httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM",
        sdkErrorType: "ApiError",
        handling: "修正 service、ticket 等查询参数",
    },
    {
        scenario: "管理接口越权",
        httpOrErrcode: "403 / M_FORBIDDEN",
        sdkErrorType: "ApiError",
        handling: "仅使用具备 CAS 管理权限的账号调用",
    },
    {
        scenario: "目标用户属性或服务不存在",
        httpOrErrcode: "404 / M_NOT_FOUND",
        sdkErrorType: "NotFoundError",
        handling: "核对用户、服务注册信息后重试",
    },
] as const;

export type CasErrorScenario = (typeof CAS_ROUTES_ERROR_SCENARIOS)[number];

export const CAS_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "CAS ticket 无效、过期或不可复用" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "CAS 请求参数结构不合法" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "service、ticket 或管理查询参数非法" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "当前账号无权访问 CAS 管理接口" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "目标服务配置或用户属性不存在" },
] as const;

export type CasErrcode = (typeof CAS_ROUTES_ERRCODES)[number];
