// Auto-generated by contract:codegen. Do not edit manually.

/** GET /_synapse/admin/v1/cas/services response — list of CAS service entries. */
export interface CasServicesResponse {
    services: CasService[];
}

/** A single CAS service configuration. */
export interface CasService {
    service_id: string;
    service_url: string;
    display_name?: string;
    redirect_url?: string;
    [key: string]: unknown;
}

/** POST /_synapse/admin/v1/cas/services request body — create or update a CAS service. */
export interface CasServiceCreateRequest {
    service_url: string;
    display_name?: string;
    redirect_url?: string;
    [key: string]: unknown;
}

/** POST /_synapse/admin/v1/cas/services response. */
export interface CasServiceCreateResponse {
    service_id: string;
    [key: string]: unknown;
}

/** GET /_synapse/admin/v1/cas/users/{user_id}/attributes response. */
export interface CasUserAttributesResponse {
    user_id: string;
    attributes: CasAttribute[];
}

/** A CAS user attribute key-value pair. */
export interface CasAttribute {
    key: string;
    value: string;
}

/** POST /_synapse/admin/v1/cas/users/{user_id}/attributes request body. */
export interface CasUserAttributesUpdateRequest {
    attributes: CasAttribute[];
}

/** CAS redirect response for SSO login. */
export interface CasRedirectResponse {
    redirect_url: string;
    service_url?: string;
}

/** CAS logout response. */
export interface CasLogoutResponse {
    logged_out: boolean;
    redirect_url?: string;
}

/** CAS serviceValidate / proxyValidate response. */
export interface CasServiceValidateResponse {
    success: boolean;
    user?: string;
    attributes?: CasAttribute[];
    proxy_granting_ticket?: string;
    proxies?: string[];
}
