/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        CAS Authentication
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       12 (既有条目 ∪ ledger 清单 ∪ ROUTE_CONTRACT.md，按 (method, path) 去重)
 */

/** Routes served by the synapse-rust `cas` module (mirrored from the backend contract). */
export const CAS_ROUTES = [
    { method: "GET", path: "/_synapse/admin/v1/cas/services" },
    { method: "POST", path: "/_synapse/admin/v1/cas/services" },
    { method: "DELETE", path: "/_synapse/admin/v1/cas/services/{service_id}" },
    { method: "GET", path: "/_synapse/admin/v1/cas/users/{user_id}/attributes" },
    { method: "POST", path: "/_synapse/admin/v1/cas/users/{user_id}/attributes" },
    { method: "GET", path: "/_matrix/client/v3/login/sso/redirect/cas" },
    { method: "GET", path: "/_synapse/cas/login" },
    { method: "GET", path: "/_synapse/cas/logout" },
    { method: "GET", path: "/_synapse/cas/p3/serviceValidate" },
    { method: "GET", path: "/_synapse/cas/proxy" },
    { method: "GET", path: "/_synapse/cas/proxyValidate" },
    { method: "GET", path: "/_synapse/cas/serviceValidate" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `CAS_ROUTES`. */
export type CasRoute = (typeof CAS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type CasMethod = CasRoute["method"];

/** Path templates referenced by this module. */
export type CasPath = CasRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type CasReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${CasReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type CasPathPattern = CasReplaceBraces<CasPath>;
