/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        CAS Authentication
 * Source:        docs/api-contract/generated/modules/cas.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  b3c5153fc5fa969a2caa04d8e506b18655b349a6
 */

/** Routes served by the synapse-rust `cas` module. */
export const CAS_ROUTES = [
    { method: "GET", path: "/_synapse/admin/v1/cas/services" },
    { method: "POST", path: "/_synapse/admin/v1/cas/services" },
    { method: "DELETE", path: "/_synapse/admin/v1/cas/services/{service_id}" },
    { method: "GET", path: "/_synapse/admin/v1/cas/users/{user_id}/attributes" },
    { method: "POST", path: "/_synapse/admin/v1/cas/users/{user_id}/attributes" },
    { method: "GET", path: "/admin/services" },
    { method: "POST", path: "/admin/services" },
    { method: "DELETE", path: "/admin/services/{service_id}" },
    { method: "GET", path: "/admin/users/{user_id}/attributes" },
    { method: "POST", path: "/admin/users/{user_id}/attributes" },
    { method: "GET", path: "/login" },
    { method: "GET", path: "/logout" },
    { method: "GET", path: "/p3/serviceValidate" },
    { method: "GET", path: "/proxy" },
    { method: "GET", path: "/proxyValidate" },
    { method: "GET", path: "/serviceValidate" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `CAS_ROUTES`. */
export type CasRoute = (typeof CAS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type CasMethod = CasRoute["method"];

/** Path templates referenced by this module. */
export type CasPath = CasRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type CasReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${CasReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type CasPathPattern = CasReplaceBraces<CasPath>;
