/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/module.json
 */

import { MODULE_ROUTES } from "./route-table";

export const MODULE_ROUTES_ENTRY_COUNT = 27 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _ModuleEntryCountAssertion: 27 = MODULE_ROUTES.length;
void _ModuleEntryCountAssertion;

export const MODULE_ROUTES_STATUS_SCENARIOS = [
    { status: 202, note: "按后端 ledger 重写为 27 条 admin 路由口径，补充 AdminManager 实际封装映射，并修正配置更新/启用请求体语义 | 修复长期文档与 SDK 漂移" },
    { status: 202, note: "初版 | -" },
] as const;

export type ModuleStatusScenario = (typeof MODULE_ROUTES_STATUS_SCENARIOS)[number];

export const MODULE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type ModuleErrorScenario = (typeof MODULE_ROUTES_ERROR_SCENARIOS)[number];

export const MODULE_ROUTES_ERRCODES = [
] as const;

export type ModuleErrcode = (typeof MODULE_ROUTES_ERRCODES)[number];
