/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Module System
 * Source:        docs/api-contract/generated/modules/module.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  52743253bdca3fa83ea774744e15c917ae07bbfd
 */

/** Routes served by the synapse-rust `module` module. */
export const MODULE_ROUTES = [
    { method: "GET", path: "/_synapse/admin/v1/account_data_callbacks" },
    { method: "POST", path: "/_synapse/admin/v1/account_data_callbacks" },
    { method: "POST", path: "/_synapse/admin/v1/account_validity" },
    { method: "GET", path: "/_synapse/admin/v1/account_validity/{user_id}" },
    { method: "POST", path: "/_synapse/admin/v1/account_validity/{user_id}/renew" },
    { method: "GET", path: "/_synapse/admin/v1/media_callbacks" },
    { method: "POST", path: "/_synapse/admin/v1/media_callbacks" },
    { method: "GET", path: "/_synapse/admin/v1/media_callbacks/{callback_type}" },
    { method: "GET", path: "/_synapse/admin/v1/modules" },
    { method: "POST", path: "/_synapse/admin/v1/modules" },
    { method: "POST", path: "/_synapse/admin/v1/modules/check_spam" },
    { method: "POST", path: "/_synapse/admin/v1/modules/check_third_party_rule" },
    { method: "GET", path: "/_synapse/admin/v1/modules/logs/{module_name}" },
    { method: "GET", path: "/_synapse/admin/v1/modules/spam_check/sender/{sender}" },
    { method: "GET", path: "/_synapse/admin/v1/modules/spam_check/{event_id}" },
    { method: "GET", path: "/_synapse/admin/v1/modules/third_party_rule/{event_id}" },
    { method: "GET", path: "/_synapse/admin/v1/modules/type/{module_type}" },
    { method: "DELETE", path: "/_synapse/admin/v1/modules/{module_name}" },
    { method: "GET", path: "/_synapse/admin/v1/modules/{module_name}" },
    { method: "PUT", path: "/_synapse/admin/v1/modules/{module_name}/config" },
    { method: "POST", path: "/_synapse/admin/v1/modules/{module_name}/enable" },
    { method: "GET", path: "/_synapse/admin/v1/password_auth_providers" },
    { method: "POST", path: "/_synapse/admin/v1/password_auth_providers" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `MODULE_ROUTES`. */
export type ModuleRoute = (typeof MODULE_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type ModuleMethod = ModuleRoute["method"];

/** Path templates referenced by this module. */
export type ModulePath = ModuleRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type ModuleReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${ModuleReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type ModulePathPattern = ModuleReplaceBraces<ModulePath>;
