/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/saml.json
 */

import { SAML_ROUTES } from "./route-table";

export const SAML_ROUTES_ENTRY_COUNT = 16 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _SamlEntryCountAssertion: 16 = SAML_ROUTES.length;
void _SamlEntryCountAssertion;

export const SAML_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "元数据读取、回调解析或登出回调成功" },
    { status: 302, note: "重定向到 SAML IdP 或返回登出跳转" },
    { status: 400, note: "SAMLResponse 缺失、元数据不完整或请求格式非法" },
    { status: 401, note: "响应签名校验失败、请求已过期或未知用户被阻止" },
    { status: 403, note: "身份提供方拒绝认证或当前配置不允许现有用户复用" },
    { status: 404, note: "登出会话不存在" },
    { status: 429, note: "触发限流" },
] as const;

export type SamlStatusScenario = (typeof SAML_ROUTES_STATUS_SCENARIOS)[number];

export const SAML_ROUTES_ERROR_SCENARIOS = [
    { scenario: "SAML 请求已过期或响应校验失败", httpOrErrcode: "401 / M_UNKNOWN_TOKEN", sdkErrorType: "AuthError", handling: "重新发起 SSO 流程，不复用旧 RelayState" },
    { scenario: "SAML 断言或元数据格式不合法", httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "检查 SAMLResponse、RelayState 与 IdP 元数据配置" },
    { scenario: "身份映射被策略拒绝", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "提示用户联系管理员确认账号映射策略" },
    { scenario: "登出会话不存在", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "将本地会话视为已失效并刷新登录态" },
    { scenario: "限流或短暂服务异常", httpOrErrcode: "429 / M_LIMIT_EXCEEDED", sdkErrorType: "RetryableError", handling: "使用退避重试" },
    { scenario: "其他 API 错误", httpOrErrcode: "其他 4xx/5xx", sdkErrorType: "ApiError", handling: "按 code 与 statusCode 做兜底处理" },
] as const;

export type SamlErrorScenario = (typeof SAML_ROUTES_ERROR_SCENARIOS)[number];

export const SAML_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "SAML 请求已过期、签名校验失败或响应已失效" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "SAMLResponse 或元数据结构不合法" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "RelayState、Issuer、Audience 或时间窗口校验失败" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "当前映射策略拒绝登录或提供方拒绝认证" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "登出回调引用的会话不存在" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "SAML 登录链路触发限流" },
] as const;

export type SamlErrcode = (typeof SAML_ROUTES_ERRCODES)[number];
