// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/saml.md

// ─── SAML Login ───────────────────────────────────────────────

/** Response from POST /login/sso/redirect/saml */
export interface SamlLoginResponse {
    /** URL to redirect the user to the IdP */
    redirect_url: string;
}

/** Result of SAML callback authentication */
export interface SamlAuthResult {
    /** Authenticated user ID */
    user_id: string;
    /** Access token for the session */
    access_token: string;
    /** Device ID for the session */
    device_id: string;
    /** Token expiry in seconds (optional) */
    expires_in?: number;
    /** Refresh token (optional) */
    refresh_token?: string;
}

// ─── SAML Logout ──────────────────────────────────────────────

/** Response from GET /logout/saml */
export interface SamlLogoutResponse {
    /** URL to redirect for IdP logout (optional) */
    redirect_url?: string;
}

// ─── SAML Metadata ────────────────────────────────────────────

/** SAML IdP metadata (XML-based, dynamic structure) */
export interface SamlMetadata {
    /** Entity ID of the IdP */
    entity_id?: string;
    /** SSO URL */
    sso_url?: string;
    /** SLO URL */
    slo_url?: string;
    /** X509 certificates */
    x509_certificates?: string[];
    /** Name ID format */
    nameid_format?: string;
    /** Raw XML metadata */
    xml?: string;
}

/** SAML SP metadata */
export interface SamlSpMetadata {
    /** SP metadata as XML */
    xml: string;
}

// ─── SAML Admin Config ────────────────────────────────────────

/** SAML admin configuration */
export interface SamlAdminConfig {
    /** Whether SAML auth is enabled */
    enabled: boolean;
    /** IdP metadata URL */
    metadata_url?: string;
    /** SP entity ID */
    sp_entity_id?: string;
    /** SP Assertion Consumer Service URL */
    sp_acs_url?: string;
    /** SP Single Logout Service URL */
    sp_sls_url?: string;
    /** NameID format */
    nameid_format?: string;
    /** Allow existing users to log in via SAML */
    allow_existing_users?: boolean;
    /** Block unknown users from logging in */
    block_unknown_users?: boolean;
    /** Template for generating user IDs from SAML attributes */
    user_id_template?: string;
    /** Whether to sign SAML requests */
    sign_requests?: boolean;
    /** Whether the IdP response must be signed */
    want_response_signed?: boolean;
    /** Whether assertions must be signed */
    want_assertions_signed?: boolean;
    /** Whether assertions must be encrypted */
    want_assertions_encrypted?: boolean;
    /** Mapping of SAML attributes to user profile fields */
    attribute_mapping?: {
        uid?: string;
        displayname?: string;
        email?: string;
    };
    /** Session lifetime in seconds */
    session_lifetime?: number;
    /** Metadata refresh interval in seconds */
    metadata_refresh_interval?: number;
    /** Allowed IdP entity IDs */
    allowed_idp_entity_ids?: string[];
    /** Request timeout in seconds */
    timeout?: number;
}

// ─── SAML User Mappings ───────────────────────────────────────

/** A SAML user mapping entry */
export interface SamlUserMapping {
    /** SAML NameID */
    name_id: string;
    /** Matrix user ID */
    user_id: string;
    /** Display name from SAML */
    displayname?: string;
    /** Email from SAML */
    email?: string;
    /** Creation timestamp */
    created_at?: number;
    /** Last update timestamp */
    updated_at?: number;
}

/** Paginated list of SAML user mappings */
export interface SamlUserMappingPage {
    /** Mapping entries */
    mappings: SamlUserMapping[];
    /** Total number of mappings */
    total?: number;
    /** Token for the next page */
    next_token?: string;
}

// ─── SAML Refresh ─────────────────────────────────────────────

/** Result of refreshing SAML metadata */
export interface SamlRefreshResult {
    /** Refresh status */
    status: string;
    /** Updated entity ID (if changed) */
    entity_id?: string;
    /** Timestamp of the refresh */
    refreshed_at?: number;
    /** Error message if refresh failed */
    error?: string;
}
