/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        SAML 契约
 * Source:        docs/api-contract/generated/modules/saml.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  0d3198b10fe246040e2d18ae540d7aea461c8e3f
 */

/** Routes served by the synapse-rust `saml` module. */
export const SAML_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/login/saml/callback" },
    { method: "POST", path: "/_matrix/client/r0/login/saml/callback" },
    { method: "GET", path: "/_matrix/client/r0/login/sso/redirect/saml" },
    { method: "POST", path: "/_matrix/client/r0/login/sso/redirect/saml" },
    { method: "GET", path: "/_matrix/client/r0/logout/saml" },
    { method: "GET", path: "/_matrix/client/r0/logout/saml/callback" },
    { method: "GET", path: "/_matrix/client/r0/saml/metadata" },
    { method: "GET", path: "/_matrix/client/r0/saml/sp_metadata" },
    { method: "GET", path: "/_synapse/admin/v1/saml/config" },
    { method: "PUT", path: "/_synapse/admin/v1/saml/config" },
    { method: "POST", path: "/_synapse/admin/v1/saml/logout" },
    { method: "DELETE", path: "/_synapse/admin/v1/saml/mapping/{name_id}" },
    { method: "GET", path: "/_synapse/admin/v1/saml/mapping/{name_id}" },
    { method: "PUT", path: "/_synapse/admin/v1/saml/mapping/{name_id}" },
    { method: "GET", path: "/_synapse/admin/v1/saml/mappings" },
    { method: "POST", path: "/_synapse/admin/v1/saml/metadata/refresh" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `SAML_ROUTES`. */
export type SamlRoute = (typeof SAML_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type SamlMethod = SamlRoute["method"];

/** Path templates referenced by this module. */
export type SamlPath = SamlRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type SamlReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${SamlReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type SamlPathPattern = SamlReplaceBraces<SamlPath>;
