// Auto-generated by contract:codegen. Do not edit manually.

/** Tag content — the value stored under each tag name in room account data. */
export interface TagContentDto {
    order?: number;
    [key: string]: unknown;
}

/** GET /_matrix/client/v3/user/{userId}/rooms/{roomId}/tags response. */
export interface TagsResponseDto {
    tags?: RoomTagsDto;
}

/** A map of tag names to their content. */
export interface RoomTagsDto {
    [tagName: string]: TagContentDto;
}

/** PUT /_matrix/client/v3/user/{userId}/rooms/{roomId}/tags/{tag} request body. */
export interface TagSetRequestDto {
    order?: number;
    [key: string]: unknown;
}

/** Room account data wrapper (includes tags). */
export interface RoomAccountDataDto {
    tags?: RoomTagsDto;
    [key: string]: unknown;
}
