/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        标签契约
 * Source:        docs/api-contract/generated/modules/tags.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  52743253bdca3fa83ea774744e15c917ae07bbfd
 */

/** Routes served by the synapse-rust `tags` module. */
export const TAGS_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/user/{user_id}/rooms/{room_id}/tags" },
    { method: "DELETE", path: "/_matrix/client/r0/user/{user_id}/rooms/{room_id}/tags/{tag}" },
    { method: "PUT", path: "/_matrix/client/r0/user/{user_id}/rooms/{room_id}/tags/{tag}" },
    { method: "GET", path: "/_matrix/client/r0/user/{user_id}/tags" },
    { method: "GET", path: "/_matrix/client/v3/user/{user_id}/rooms/{room_id}/tags" },
    { method: "DELETE", path: "/_matrix/client/v3/user/{user_id}/rooms/{room_id}/tags/{tag}" },
    { method: "PUT", path: "/_matrix/client/v3/user/{user_id}/rooms/{room_id}/tags/{tag}" },
    { method: "GET", path: "/_matrix/client/v3/user/{user_id}/tags" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `TAGS_ROUTES`. */
export type TagsRoute = (typeof TAGS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type TagsMethod = TagsRoute["method"];

/** Path templates referenced by this module. */
export type TagsPath = TagsRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type TagsReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${TagsReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type TagsPathPattern = TagsReplaceBraces<TagsPath>;
