/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/voice.json
 */

import { VOICE_ROUTES } from "./route-table";

export const VOICE_ROUTES_ENTRY_COUNT = 18 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _VoiceEntryCountAssertion: 18 = VOICE_ROUTES.length;
void _VoiceEntryCountAssertion;

export const VOICE_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "base64 无效、音频 MIME 非法、duration_ms 不合法、参数缺失，或 convert / optimize 当前未启用" },
    { status: 401, note: "需认证接口缺少或使用无效令牌" },
    { status: 403, note: "跨用户读取用户级语音数据、非成员向他人房间上传语音、无权读取房间/消息级语音内容，或非所有者删除语音时被拒绝" },
    { status: 404, note: "语音消息不存在" },
    { status: 500, note: "service 层或存储层内部错误" },
] as const;

export type VoiceStatusScenario = (typeof VOICE_ROUTES_STATUS_SCENARIOS)[number];

export const VOICE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type VoiceErrorScenario = (typeof VOICE_ROUTES_ERROR_SCENARIOS)[number];

export const VOICE_ROUTES_ERRCODES = [
] as const;

export type VoiceErrcode = (typeof VOICE_ROUTES_ERRCODES)[number];
