// Auto-generated by contract:codegen. Do not edit manually.

/** GET /_matrix/client/v3/voice/stats response — global voice message statistics. */
export interface VoiceStatsResponse {
    total_messages: number;
    total_duration_ms: number;
    average_duration_ms: number;
    storage_used_bytes: number;
}

/** GET /_matrix/client/v3/voice/room/{roomId}/stats response. */
export interface VoiceRoomStatsResponse {
    room_id: string;
    message_count: number;
    total_duration_ms: number;
}

/** GET /_matrix/client/v3/voice/user/{userId}/stats response. */
export interface VoiceUserStatsResponse {
    user_id: string;
    message_count: number;
    total_duration_ms: number;
}

/** GET /_matrix/client/v3/voice/config response. */
export interface VoiceConfigResponse {
    max_upload_size_bytes: number;
    allowed_content_types: string[];
    auto_transcribe: boolean;
    retention_days: number;
}

/** POST /_matrix/client/v3/voice/upload request body. */
export interface VoiceUploadRequest {
    content: string;
    content_type: string;
    room_id?: string;
    filename?: string;
}

/** POST /_matrix/client/v3/voice/upload response. */
export interface VoiceUploadResponse {
    message_id: string;
    url: string;
    mxc_url: string;
    content_type: string;
    size_bytes: number;
    duration_ms: number;
}

/** GET /_matrix/client/v3/voice/{messageId} response. */
export interface VoiceMessageResponse {
    message_id: string;
    url: string;
    mxc_url: string;
    content_type: string;
    size_bytes: number;
    duration_ms: number;
    created_ts: number;
}

/** DELETE /_matrix/client/v3/voice/{messageId} response. */
export interface VoiceDeleteResponse {
    message_id: string;
    deleted: boolean;
}

/** POST /_matrix/client/v3/voice/convert request body (deprecated per MSC3245). */
export interface VoiceConvertRequest {
    message_id: string;
    target_content_type: string;
}

/** POST /_matrix/client/v3/voice/optimize request body (deprecated per MSC3245). */
export interface VoiceOptimizeRequest {
    message_id: string;
    target_bitrate?: number;
    target_sample_rate?: number;
}

/** POST /_matrix/client/v3/voice/transcribe request body (deprecated per MSC3245). */
export interface VoiceTranscriptionRequest {
    message_id: string;
    language?: string;
}

/** POST /_matrix/client/v3/voice/transcribe response (deprecated per MSC3245). */
export interface VoiceTranscriptionResponse {
    message_id: string;
    text: string;
    language: string;
    confidence: number;
}
