/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Voice 模块契约
 * Source:        docs/api-contract/generated/modules/voice.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  ef9bd5d4d22c35afba65b2b5452278f6a0a28115
 */

/** Routes served by the synapse-rust `voice` module. */
export const VOICE_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/voice/config" },
    { method: "POST", path: "/_matrix/client/r0/voice/upload" },
    { method: "GET", path: "/_matrix/client/v1/voice/config" },
    { method: "GET", path: "/_matrix/client/v1/voice/room/{room_id}/stats" },
    { method: "GET", path: "/_matrix/client/v1/voice/stats" },
    { method: "POST", path: "/_matrix/client/v1/voice/upload" },
    { method: "GET", path: "/_matrix/client/v1/voice/user/{user_id}/stats" },
    { method: "GET", path: "/_matrix/client/v3/voice/config" },
    { method: "GET", path: "/_matrix/client/v3/voice/room/{room_id}" },
    { method: "GET", path: "/_matrix/client/v3/voice/room/{room_id}/stats" },
    { method: "GET", path: "/_matrix/client/v3/voice/stats" },
    { method: "POST", path: "/_matrix/client/v3/voice/upload" },
    { method: "GET", path: "/_matrix/client/v3/voice/user/{user_id}" },
    { method: "GET", path: "/_matrix/client/v3/voice/user/{user_id}/stats" },
    { method: "GET", path: "/_matrix/client/v3/voice/{media_id}" },
    { method: "POST", path: "/_matrix/client/v3/voice/{media_id}/convert" },
    { method: "POST", path: "/_matrix/client/v3/voice/{media_id}/optimize" },
    { method: "POST", path: "/_matrix/client/v3/voice/{media_id}/transcription" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `VOICE_ROUTES`. */
export type VoiceRoute = (typeof VOICE_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type VoiceMethod = VoiceRoute["method"];

/** Path templates referenced by this module. */
export type VoicePath = VoiceRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type VoiceReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${VoiceReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type VoicePathPattern = VoiceReplaceBraces<VoicePath>;
