/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/openclaw.json
 */

import { OPENCLAW_ROUTES } from "./route-table";

export const OPENCLAW_ROUTES_ENTRY_COUNT = 23 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _OpenclawEntryCountAssertion: 23 = OPENCLAW_ROUTES.length;
void _OpenclawEntryCountAssertion;

export const OPENCLAW_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "OpenClaw 动作参数或请求体格式非法" },
    { status: 401, note: "Token 无效或缺失" },
    { status: 403, note: "当前账号无权执行 OpenClaw 动作" },
    { status: 404, note: "OpenClaw 配置或目标动作资源不存在" },
] as const;

export type OpenclawStatusScenario = (typeof OPENCLAW_ROUTES_STATUS_SCENARIOS)[number];

export const OPENCLAW_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "未认证或 token 失效",
        httpOrErrcode: "401 / M_UNKNOWN_TOKEN",
        sdkErrorType: "AuthError",
        handling: "引导重新登录",
    },
    {
        scenario: "OpenClaw 请求参数不合法",
        httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM",
        sdkErrorType: "ApiError",
        handling: "修正动作类型、payload 或请求体后重试",
    },
    {
        scenario: "权限不足",
        httpOrErrcode: "403 / M_FORBIDDEN",
        sdkErrorType: "ApiError",
        handling: "提示用户当前账号无权执行该动作",
    },
    {
        scenario: "配置或目标资源不存在",
        httpOrErrcode: "404 / M_NOT_FOUND",
        sdkErrorType: "NotFoundError",
        handling: "刷新配置并核对目标资源状态",
    },
] as const;

export type OpenclawErrorScenario = (typeof OPENCLAW_ROUTES_ERROR_SCENARIOS)[number];

export const OPENCLAW_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "access token 无效、过期或缺失" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "OpenClaw 请求体结构不合法" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "动作参数、payload 或查询字段非法" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "无权读取配置或执行目标动作" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "OpenClaw 配置或目标资源不存在" },
] as const;

export type OpenclawErrcode = (typeof OPENCLAW_ROUTES_ERRCODES)[number];
