/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/openclaw.md
 */

/**
 * DTO snippets extracted from the contract doc for `openclaw`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface OpenClawConnection {
    id: number;
    name: string;
    provider: string;
    base_url: string;
    has_api_key: boolean;
    config?: Record<string, unknown>;
    is_default: boolean;
    is_active: boolean;
    created_ts: number;
    updated_ts: number;
}

export interface CreateOpenClawConnectionRequest {
    name: string;
    provider: string;
    base_url: string;
    api_key?: string;
    config?: Record<string, unknown>;
    is_default?: boolean;
}

export interface UpdateOpenClawConnectionRequest {
    name?: string;
    base_url?: string;
    api_key?: string;
    config?: Record<string, unknown>;
    is_default?: boolean;
    is_active?: boolean;
}

export interface ConnectionTestResult {
    healthy: boolean;
    latency_ms: number;
    provider: string;
    base_url: string;
}

export interface OpenClawConversation {
    id: number;
    connection_id?: number;
    title?: string;
    model_id?: string;
    system_prompt?: string;
    temperature?: number;
    max_tokens?: number;
    is_pinned: boolean;
    created_ts: number;
    updated_ts: number;
}

export interface CreateOpenClawConversationRequest {
    connection_id?: number;
    title?: string;
    model_id?: string;
    system_prompt?: string;
    temperature?: number;
    max_tokens?: number;
}

export interface UpdateOpenClawConversationRequest {
    title?: string;
    system_prompt?: string;
    temperature?: number;
    max_tokens?: number;
    is_pinned?: boolean;
}

export interface OpenClawMessage {
    id: number;
    conversation_id: number;
    role: string;
    content: string;
    token_count?: number;
    tool_calls?: Record<string, unknown>;
    created_ts: number;
}

export interface SendMessageRequest {
    content: string;
    role?: string;
    tool_calls?: Record<string, unknown>;
    tool_call_id?: string;
}

export interface OpenClawGeneration {
    id: number;
    conversation_id?: number;
    type: string;
    prompt: string;
    result_url?: string;
    result_mxc?: string;
    status: string;
    error_message?: string;
    created_ts: number;
    completed_ts?: number;
}

export interface CreateGenerationRequest {
    conversation_id?: number;
    type: string;
    prompt: string;
}

export interface OpenClawChatRole {
    id: number;
    name: string;
    description?: string;
    system_message: string;
    model_id?: string;
    avatar_url?: string;
    category?: string;
    temperature?: number;
    max_tokens?: number;
    is_public: boolean;
    created_ts: number;
    updated_ts: number;
}

export interface CreateChatRoleRequest {
    name: string;
    description?: string;
    system_message: string;
    model_id?: string;
    avatar_url?: string;
    category?: string;
    temperature?: number;
    max_tokens?: number;
    is_public?: boolean;
}

export interface UpdateChatRoleRequest {
    name?: string;
    description?: string;
    system_message?: string;
    model_id?: string;
    avatar_url?: string;
    category?: string;
    temperature?: number;
    max_tokens?: number;
    is_public?: boolean;
}

export interface PaginatedResponse<T> {
    items: T[];
    total: number;
    limit: number;
    offset: number;
    next_batch?: string;
}

export interface PaginationParams {
    limit?: number;
    offset?: number;
    from?: string;
    before?: number;
    type?: string;
}
