/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { ACCOUNT_DATA_ROUTES } from "./route-table";

export const ACCOUNT_DATA_ROUTES_ENTRY_COUNT = 26 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _AccountDataEntryCountAssertion: 26 = ACCOUNT_DATA_ROUTES.length;
void _AccountDataEntryCountAssertion;

export const ACCOUNT_DATA_ROUTES_STATUS_SCENARIOS = [
] as const;

export type AccountDataStatusScenario = (typeof ACCOUNT_DATA_ROUTES_STATUS_SCENARIOS)[number];

export const ACCOUNT_DATA_ROUTES_ERROR_SCENARIOS = [
] as const;

export type AccountDataErrorScenario = (typeof ACCOUNT_DATA_ROUTES_ERROR_SCENARIOS)[number];

export const ACCOUNT_DATA_ROUTES_ERRCODES = [
] as const;

export type AccountDataErrcode = (typeof ACCOUNT_DATA_ROUTES_ERRCODES)[number];
