// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/account-data.md

// ─── Account Data Event Types ────────────────────────────────

/** Well-known account data event types */
export type AccountDataEventType =
    | "m.direct"
    | "m.push_rules"
    | "m.ignored_user_list"
    | "m.tag"
    | "m.fully_read"
    | "m.widgets"
    | "m.secret_storage.key"
    | "m.cross_signing.master"
    | "m.cross_signing.self_signing"
    | "m.cross_signing.user_signing"
    | (string & {});

// ─── Set Account Data ────────────────────────────────────────

/** Request body for PUT /user/{userId}/account_data/{type} */
export interface AccountDataRequest {
    /** Arbitrary account data content, serialized size must be ≤ 64KB */
    [key: string]: unknown;
}

/** Response from PUT /user/{userId}/account_data/{type} (empty on success) */
export interface AccountDataResponse {}

// ─── List Account Data ───────────────────────────────────────

/** Response from GET /user/{userId}/account_data */
export interface AccountDataListResponse {
    /** Map of event type → content */
    account_data: Record<string, unknown>;
}

// ─── Room Account Data ───────────────────────────────────────

/** Request body for PUT /user/{userId}/rooms/{roomId}/account_data/{type} */
export interface RoomAccountDataRequest {
    /** Arbitrary room-scoped account data content, serialized size must be ≤ 64KB */
    [key: string]: unknown;
}

/** Response from PUT /user/{userId}/rooms/{roomId}/account_data/{type} (empty on success) */
export interface RoomAccountDataResponse {}
