/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Account Data 模块契约
 * Source:        docs/api-contract/generated/modules/account_data.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  4ea2cc71c82770204c71aba66cead18f43c74b8e
 */

/** Routes served by the synapse-rust `account_data` module. */
export const ACCOUNT_DATA_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/user/{user_id}/account_data/" },
    { method: "DELETE", path: "/_matrix/client/r0/user/{user_id}/account_data/{type}" },
    { method: "GET", path: "/_matrix/client/r0/user/{user_id}/account_data/{type}" },
    { method: "PUT", path: "/_matrix/client/r0/user/{user_id}/account_data/{type}" },
    { method: "POST", path: "/_matrix/client/r0/user/{user_id}/filter" },
    { method: "PUT", path: "/_matrix/client/r0/user/{user_id}/filter" },
    { method: "DELETE", path: "/_matrix/client/r0/user/{user_id}/filter/{filter_id}" },
    { method: "GET", path: "/_matrix/client/r0/user/{user_id}/filter/{filter_id}" },
    { method: "GET", path: "/_matrix/client/r0/user/{user_id}/openid/request_token" },
    { method: "POST", path: "/_matrix/client/r0/user/{user_id}/openid/request_token" },
    { method: "DELETE", path: "/_matrix/client/r0/user/{user_id}/rooms/{room_id}/account_data/{type}" },
    { method: "GET", path: "/_matrix/client/r0/user/{user_id}/rooms/{room_id}/account_data/{type}" },
    { method: "PUT", path: "/_matrix/client/r0/user/{user_id}/rooms/{room_id}/account_data/{type}" },
    { method: "GET", path: "/_matrix/client/v3/user/{user_id}/account_data/" },
    { method: "DELETE", path: "/_matrix/client/v3/user/{user_id}/account_data/{type}" },
    { method: "GET", path: "/_matrix/client/v3/user/{user_id}/account_data/{type}" },
    { method: "PUT", path: "/_matrix/client/v3/user/{user_id}/account_data/{type}" },
    { method: "POST", path: "/_matrix/client/v3/user/{user_id}/filter" },
    { method: "PUT", path: "/_matrix/client/v3/user/{user_id}/filter" },
    { method: "DELETE", path: "/_matrix/client/v3/user/{user_id}/filter/{filter_id}" },
    { method: "GET", path: "/_matrix/client/v3/user/{user_id}/filter/{filter_id}" },
    { method: "GET", path: "/_matrix/client/v3/user/{user_id}/openid/request_token" },
    { method: "POST", path: "/_matrix/client/v3/user/{user_id}/openid/request_token" },
    { method: "DELETE", path: "/_matrix/client/v3/user/{user_id}/rooms/{room_id}/account_data/{type}" },
    { method: "GET", path: "/_matrix/client/v3/user/{user_id}/rooms/{room_id}/account_data/{type}" },
    { method: "PUT", path: "/_matrix/client/v3/user/{user_id}/rooms/{room_id}/account_data/{type}" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `ACCOUNT_DATA_ROUTES`. */
export type AccountDataRoute = (typeof ACCOUNT_DATA_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type AccountDataMethod = AccountDataRoute["method"];

/** Path templates referenced by this module. */
export type AccountDataPath = AccountDataRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type AccountDataReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${AccountDataReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type AccountDataPathPattern = AccountDataReplaceBraces<AccountDataPath>;
