/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { AUTH_ROUTES } from "./route-table";

export const AUTH_ROUTES_ENTRY_COUNT = 158 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _AuthEntryCountAssertion: 158 = AUTH_ROUTES.length;
void _AuthEntryCountAssertion;

export const AUTH_ROUTES_STATUS_SCENARIOS = [
] as const;

export type AuthStatusScenario = (typeof AUTH_ROUTES_STATUS_SCENARIOS)[number];

export const AUTH_ROUTES_ERROR_SCENARIOS = [
] as const;

export type AuthErrorScenario = (typeof AUTH_ROUTES_ERROR_SCENARIOS)[number];

export const AUTH_ROUTES_ERRCODES = [
] as const;

export type AuthErrcode = (typeof AUTH_ROUTES_ERRCODES)[number];
