/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/assembly.json
 */

import { AUTH_ROUTES } from "./route-table";

export const AUTH_ROUTES_ENTRY_COUNT = 152 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _AuthEntryCountAssertion: 152 = AUTH_ROUTES.length;
void _AuthEntryCountAssertion;

export const AUTH_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "参数错误或请求体格式非法" },
    { status: 401, note: "未授权，Token 无效或过期" },
    { status: 403, note: "禁止访问，权限不足" },
    { status: 409, note: "冲突，如用户名已被占用" },
    { status: 429, note: "触发限流" },
] as const;

export type AuthStatusScenario = (typeof AUTH_ROUTES_STATUS_SCENARIOS)[number];

export const AUTH_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "未认证或 token 失效",
        httpOrErrcode: "401 / M_UNKNOWN_TOKEN",
        sdkErrorType: "AuthError",
        handling: "引导重新登录或刷新凭据",
    },
    {
        scenario: "资源冲突",
        httpOrErrcode: "409 / M_USER_IN_USE",
        sdkErrorType: "ApiError",
        handling: "提示用户更换输入（如用户名）",
    },
    {
        scenario: "参数不合法",
        httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM",
        sdkErrorType: "ApiError",
        handling: "修正请求参数后重试",
    },
    {
        scenario: "限流或短暂服务异常",
        httpOrErrcode: "429 / M_LIMIT_EXCEEDED",
        sdkErrorType: "RetryableError",
        handling: "使用退避重试",
    },
    {
        scenario: "其他 API 错误",
        httpOrErrcode: "其他 4xx/5xx",
        sdkErrorType: "ApiError",
        handling: "按 code 与 statusCode 做兜底",
    },
] as const;

export type AuthErrorScenario = (typeof AUTH_ROUTES_ERROR_SCENARIOS)[number];

export const AUTH_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "access token 无效、过期或缺失" },
    { errcode: "M_USER_IN_USE", httpStatus: "409", note: "用户名已被占用" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "请求体结构不符合接口要求" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "参数类型或取值非法" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "触发限流，需延迟重试" },
] as const;

export type AuthErrcode = (typeof AUTH_ROUTES_ERRCODES)[number];
