/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Auth / Account / Discovery 契约
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       104 (既有条目 ∪ ledger 清单 ∪ ROUTE_CONTRACT.md，按 (method, path) 去重)
 */

/** Routes served by the synapse-rust `auth` module (mirrored from the backend contract). */
export const AUTH_ROUTES = [
    { method: "GET", path: "/" },
    { method: "GET", path: "/.well-known/matrix/client" },
    { method: "GET", path: "/.well-known/matrix/server" },
    { method: "GET", path: "/.well-known/matrix/support" },
    { method: "GET", path: "/_health" },
    { method: "GET", path: "/_matrix/client/unstable/org.matrix.msc2965/auth_metadata" },
    { method: "DELETE", path: "/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device" },
    { method: "GET", path: "/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device" },
    { method: "PUT", path: "/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device" },
    { method: "GET", path: "/_matrix/client/unstable/org.matrix.msc4143/rtc/transports" },
    { method: "GET", path: "/_matrix/client/unstable/uk.tcpip.msc4133/profile/{user_id}" },
    { method: "DELETE", path: "/_matrix/client/unstable/uk.tcpip.msc4133/profile/{user_id}/{key_name}" },
    { method: "GET", path: "/_matrix/client/unstable/uk.tcpip.msc4133/profile/{user_id}/{key_name}" },
    { method: "PUT", path: "/_matrix/client/unstable/uk.tcpip.msc4133/profile/{user_id}/{key_name}" },
    { method: "GET", path: "/_matrix/client/v1/account/3pid" },
    { method: "POST", path: "/_matrix/client/v1/account/3pid" },
    { method: "POST", path: "/_matrix/client/v1/account/3pid/add" },
    { method: "POST", path: "/_matrix/client/v1/account/3pid/bind" },
    { method: "POST", path: "/_matrix/client/v1/account/3pid/delete" },
    { method: "POST", path: "/_matrix/client/v1/account/3pid/email/requestToken" },
    { method: "POST", path: "/_matrix/client/v1/account/3pid/email/submitToken" },
    { method: "POST", path: "/_matrix/client/v1/account/3pid/unbind" },
    { method: "POST", path: "/_matrix/client/v1/account/deactivate" },
    { method: "POST", path: "/_matrix/client/v1/account/password" },
    { method: "POST", path: "/_matrix/client/v1/account/password/email/requestToken" },
    { method: "POST", path: "/_matrix/client/v1/account/password/email/submitToken" },
    { method: "GET", path: "/_matrix/client/v1/account/whoami" },
    { method: "GET", path: "/_matrix/client/v1/config/client" },
    { method: "GET", path: "/_matrix/client/v1/media/config" },
    { method: "GET", path: "/_matrix/client/v1/profile/{user_id}" },
    { method: "GET", path: "/_matrix/client/v1/profile/{user_id}/avatar_url" },
    { method: "PUT", path: "/_matrix/client/v1/profile/{user_id}/avatar_url" },
    { method: "GET", path: "/_matrix/client/v1/profile/{user_id}/displayname" },
    { method: "PUT", path: "/_matrix/client/v1/profile/{user_id}/displayname" },
    { method: "GET", path: "/_matrix/client/v3/account/3pid" },
    { method: "POST", path: "/_matrix/client/v3/account/3pid" },
    { method: "POST", path: "/_matrix/client/v3/account/3pid/add" },
    { method: "POST", path: "/_matrix/client/v3/account/3pid/bind" },
    { method: "POST", path: "/_matrix/client/v3/account/3pid/delete" },
    { method: "POST", path: "/_matrix/client/v3/account/3pid/email/requestToken" },
    { method: "POST", path: "/_matrix/client/v3/account/3pid/email/submitToken" },
    { method: "POST", path: "/_matrix/client/v3/account/3pid/unbind" },
    { method: "POST", path: "/_matrix/client/v3/account/deactivate" },
    { method: "POST", path: "/_matrix/client/v3/account/password" },
    { method: "POST", path: "/_matrix/client/v3/account/password/email/requestToken" },
    { method: "POST", path: "/_matrix/client/v3/account/password/email/submitToken" },
    { method: "GET", path: "/_matrix/client/v3/account/whoami" },
    { method: "GET", path: "/_matrix/client/v3/capabilities" },
    { method: "GET", path: "/_matrix/client/v3/directory/list/room/{room_id}" },
    { method: "PUT", path: "/_matrix/client/v3/directory/list/room/{room_id}" },
    { method: "DELETE", path: "/_matrix/client/v3/directory/room/{room_alias}" },
    { method: "GET", path: "/_matrix/client/v3/directory/room/{room_alias}" },
    { method: "PUT", path: "/_matrix/client/v3/directory/room/{room_alias}" },
    { method: "GET", path: "/_matrix/client/v3/login" },
    { method: "POST", path: "/_matrix/client/v3/login" },
    { method: "POST", path: "/_matrix/client/v3/logout" },
    { method: "POST", path: "/_matrix/client/v3/logout/all" },
    { method: "GET", path: "/_matrix/client/v3/media/config" },
    { method: "GET", path: "/_matrix/client/v3/profile/{user_id}" },
    { method: "GET", path: "/_matrix/client/v3/profile/{user_id}/avatar_url" },
    { method: "PUT", path: "/_matrix/client/v3/profile/{user_id}/avatar_url" },
    { method: "GET", path: "/_matrix/client/v3/profile/{user_id}/displayname" },
    { method: "PUT", path: "/_matrix/client/v3/profile/{user_id}/displayname" },
    { method: "GET", path: "/_matrix/client/v3/publicRooms" },
    { method: "POST", path: "/_matrix/client/v3/publicRooms" },
    { method: "GET", path: "/_matrix/client/v3/pushrules/" },
    { method: "GET", path: "/_matrix/client/v3/pushrules/global/" },
    { method: "POST", path: "/_matrix/client/v3/refresh" },
    { method: "GET", path: "/_matrix/client/v3/register" },
    { method: "POST", path: "/_matrix/client/v3/register" },
    { method: "GET", path: "/_matrix/client/v3/register/available" },
    { method: "POST", path: "/_matrix/client/v3/register/email/requestToken" },
    { method: "POST", path: "/_matrix/client/v3/register/email/submitToken" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/call/{call_id}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/send/m.call.answer/{txn_id}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/send/m.call.candidates/{txn_id}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/send/m.call.hangup/{txn_id}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/send/m.call.invite/{txn_id}" },
    { method: "POST", path: "/_matrix/client/v3/user_directory/list" },
    { method: "GET", path: "/_matrix/client/v3/user_directory/profiles/{user_id}" },
    { method: "POST", path: "/_matrix/client/v3/user_directory/search" },
    { method: "GET", path: "/_matrix/client/v3/versions" },
    { method: "GET", path: "/_matrix/client/v3/voip/config" },
    { method: "GET", path: "/_matrix/client/v3/voip/turnServer" },
    { method: "POST", path: "/_matrix/client/v3/voip/turnServer" },
    { method: "GET", path: "/_matrix/client/v3/voip/turnServer/guest" },
    { method: "GET", path: "/_matrix/client/versions" },
    { method: "GET", path: "/_matrix/server_version" },
    { method: "GET", path: "/_matrix/static/client/login/" },
    { method: "GET", path: "/health" },
    { method: "POST", path: "/_matrix/client/unstable/org.matrix.msc3720/account_status" },
    { method: "GET", path: "/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device/status" },
    { method: "GET", path: "/_matrix/client/unstable/org.matrix.msc3814.v1/dehydrated_device/{device_id}/events" },
    { method: "GET", path: "/_matrix/client/v1/auth_metadata" },
    { method: "POST", path: "/_matrix/client/v1/login/qr_token" },
    { method: "GET", path: "/_matrix/client/v3/auth/{auth_type}/fallback/web" },
    { method: "GET", path: "/_matrix/client/v3/directory/room/{room_id}/alias" },
    { method: "DELETE", path: "/_matrix/client/v3/directory/room/{room_id}/alias/{room_alias}" },
    { method: "PUT", path: "/_matrix/client/v3/directory/room/{room_id}/alias/{room_alias}" },
    { method: "DELETE", path: "/_matrix/client/v3/profile/{user_id}/{key_name}" },
    { method: "GET", path: "/_matrix/client/v3/profile/{user_id}/{key_name}" },
    { method: "PUT", path: "/_matrix/client/v3/profile/{user_id}/{key_name}" },
    { method: "GET", path: "/_matrix/client/v3/upload/provider" },
    { method: "POST", path: "/_matrix/client/v3/upload/token" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `AUTH_ROUTES`. */
export type AuthRoute = (typeof AUTH_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type AuthMethod = AuthRoute["method"];

/** Path templates referenced by this module. */
export type AuthPath = AuthRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type AuthReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${AuthReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type AuthPathPattern = AuthReplaceBraces<AuthPath>;
