/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/ephemeral.json
 */

import { EPHEMERAL_ROUTES } from "./route-table";

export const EPHEMERAL_ROUTES_ENTRY_COUNT = 1 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _EphemeralEntryCountAssertion: 1 = EPHEMERAL_ROUTES.length;
void _EphemeralEntryCountAssertion;

export const EPHEMERAL_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 401, note: "Token 无效或缺失" },
    { status: 403, note: "非房间成员，或无权查看目标房间的临时事件" },
    { status: 404, note: "房间不存在" },
    { status: 202, note: "初版 | -" },
] as const;

export type EphemeralStatusScenario = (typeof EPHEMERAL_ROUTES_STATUS_SCENARIOS)[number];

export const EPHEMERAL_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "未认证或 token 失效",
        httpOrErrcode: "401 / M_UNKNOWN_TOKEN",
        sdkErrorType: "AuthError",
        handling: "引导重新登录",
    },
    {
        scenario: "房间访问越权",
        httpOrErrcode: "403 / M_FORBIDDEN",
        sdkErrorType: "ApiError",
        handling: "提示用户需要先加入对应房间",
    },
    {
        scenario: "房间不存在",
        httpOrErrcode: "404 / M_NOT_FOUND",
        sdkErrorType: "NotFoundError",
        handling: "刷新房间列表并确认房间 ID",
    },
] as const;

export type EphemeralErrorScenario = (typeof EPHEMERAL_ROUTES_ERROR_SCENARIOS)[number];

export const EPHEMERAL_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "access token 无效、过期或缺失" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "无权读取该房间的临时事件" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "房间不存在或已不可访问" },
] as const;

export type EphemeralErrcode = (typeof EPHEMERAL_ROUTES_ERRCODES)[number];
