/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/ephemeral.md
 */

/**
 * DTO snippets extracted from the contract doc for `ephemeral`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface EphemeralEventContent {
    /** For m.typing events: list of user IDs currently typing */
    user_ids?: string[];
    /** For m.receipt events: map of event_id → receipt data */
    [eventId: string]: unknown;
}

export interface EphemeralEvent {
    type: string;
    sender: string;
    content: EphemeralEventContent;
    origin_server_ts: number;
    stream_id: number;
    event_id: string;
}

export interface EphemeralEventsResponse {
    chunk: EphemeralEvent[];
    start?: string;
    end?: string;
}
