/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Ephemeral Events
 * Source:        docs/api-contract/generated/modules/ephemeral.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  b3c5153fc5fa969a2caa04d8e506b18655b349a6
 */

/** Routes served by the synapse-rust `ephemeral` module. */
export const EPHEMERAL_ROUTES = [
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/ephemeral" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `EPHEMERAL_ROUTES`. */
export type EphemeralRoute = (typeof EPHEMERAL_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type EphemeralMethod = EphemeralRoute["method"];

/** Path templates referenced by this module. */
export type EphemeralPath = EphemeralRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type EphemeralReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${EphemeralReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type EphemeralPathPattern = EphemeralReplaceBraces<EphemeralPath>;
