// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/verification.md

// ─── Verification Start ───────────────────────────────────────

/** Request body for POST /keys/device_signing/verify_start */
export interface VerificationStartRequest {
    /** Device ID of the initiator */
    from_device: string;
    /** Target user ID */
    to_user: string;
    /** Target device ID (optional; all devices if omitted) */
    to_device?: string;
    /** Transaction ID (optional; server generates if omitted) */
    transaction_id?: string;
    /** Verification method (default: "m.sas.v1") */
    method?: string;
}

/** Response from POST /keys/device_signing/verify_start */
export interface VerificationStartResponse {
    /** Server-assigned transaction ID */
    transaction_id: string;
    /** Agreed verification method */
    method: string;
    /** Supported key agreement protocols */
    key_agreement_protocol: string[];
    /** Supported hash algorithms */
    hash: string[];
    /** Supported short authentication string methods */
    short_authentication_string: string[];
}

// ─── Verification Accept ──────────────────────────────────────

/** Request body for PUT /keys/device_signing/verify_accept */
export interface VerificationAcceptRequest {
    /** Transaction ID from the start response */
    transaction_id: string;
    /** Selected key agreement protocol */
    key_agreement_protocol: string;
    /** Selected hash algorithm */
    hash: string;
    /** Commitment hash (optional) */
    commitment?: string;
}

/** Response from PUT /keys/device_signing/verify_accept */
export interface VerificationAcceptResponse extends VerificationStartResponse {
    /** Commitment hash from the acceptor */
    commitment?: string;
}

// ─── Key Agreement ────────────────────────────────────────────

/** Request body for POST /keys/device_signing/verify_key_agreement */
export interface VerificationKeyAgreementRequest {
    /** Transaction ID */
    transaction_id: string;
    /** Curve25519 public key (base64) */
    pubkey: string;
}

/** Response from POST /keys/device_signing/verify_key_agreement */
export interface VerificationKeyAgreementResponse {
    /** Transaction ID */
    transaction_id: string;
    /** Whether the key was confirmed */
    confirmed: boolean;
    /** SAS short authentication string representation */
    short_authentication_string: {
        /** Emoji SAS characters */
        emoji?: string[];
        /** Decimal SAS representation */
        decimal?: { points: number[] };
    };
}

// ─── MAC Verification ─────────────────────────────────────────

/** Request body for POST /keys/device_signing/verify_mac */
export interface VerificationMacRequest {
    /** Transaction ID */
    transaction_id: string;
    /** MAC digest (base64) */
    mac: string;
}

/** Response from POST /keys/device_signing/verify_mac */
export interface VerificationMacResponse {
    /** Transaction ID */
    transaction_id: string;
    /** Whether MAC verification succeeded */
    verified: boolean;
}

// ─── Verification Done ────────────────────────────────────────

/** Request body for POST /keys/device_signing/verify_done */
export interface VerificationDoneRequest {
    /** Transaction ID */
    transaction_id: string;
    /** Final MAC confirmation */
    mac: string;
}

/** Response from POST /keys/device_signing/verify_done */
export interface VerificationDoneResponse {
    /** Transaction ID */
    transaction_id: string;
}

// ─── Verification Cancel ──────────────────────────────────────

/** Request body for POST /keys/device_signing/verify_cancel */
export interface VerificationCancelRequest {
    /** Transaction ID */
    transaction_id: string;
    /** Error code (e.g. "m.user") */
    code: string;
    /** Human-readable reason */
    reason: string;
}

/** Response from POST /keys/device_signing/verify_cancel */
export interface VerificationCancelResponse {
    /** Transaction ID */
    transaction_id: string;
    /** Cancelled state marker */
    state: "cancelled";
    /** Error code */
    code: string;
    /** Human-readable reason */
    reason: string;
}

// ─── List Verification Requests ───────────────────────────────

/** A single verification request entry */
export interface VerificationRequestEntry {
    /** Transaction ID */
    transaction_id: string;
    /** User ID of the initiator */
    from_user: string;
    /** Device ID of the initiator */
    from_device: string;
    /** Target user ID */
    to_user: string;
    /** Target device ID */
    to_device?: string;
    /** Verification method */
    method: string;
    /** Current state of the request */
    state: string;
    /** Timestamp when the request was created */
    created_ts: number;
    /** Timestamp when the request was last updated */
    updated_ts: number;
}

/** Response from GET /keys/device_signing/requests */
export interface ListVerificationRequestsResponse {
    /** List of pending verification requests */
    requests: VerificationRequestEntry[];
}

// ─── QR Code ──────────────────────────────────────────────────

/** Response from GET /keys/qr_code/show */
export interface QrCodeShowResponse {
    /** Transaction ID this QR code belongs to */
    transaction_id: string;
    /** Server name encoded in the QR code */
    server_name: string;
    /** User ID encoded in the QR code */
    user_id: string;
    /** Device ID encoded in the QR code */
    device_id: string;
    /** Ed25519 device key (base64) */
    device_ed25519_key: string;
    /** Curve25519 device key (base64) */
    device_curve25519_key: string;
}

/** Request body for POST /keys/qr_code/scan */
export interface ScanQrCodeRequest {
    /** Transaction ID to associate with the scan */
    transaction_id: string;
    /** Server name decoded from the QR code */
    server_name: string;
    /** User ID decoded from the QR code */
    user_id: string;
    /** Device ID decoded from the QR code */
    device_id: string;
    /** Ed25519 key decoded from the QR code */
    device_ed25519_key: string;
    /** Curve25519 key decoded from the QR code */
    device_curve25519_key: string;
}

/** Response from POST /keys/qr_code/scan */
export interface ScanQrCodeResponse {
    /** Transaction ID */
    transaction_id: string;
    /** Resulting verification state */
    state: "pending" | "verified" | "cancelled";
}
