/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Verification 契约
 * Source:        docs/api-contract/generated/modules/verification_routes.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  52743253bdca3fa83ea774744e15c917ae07bbfd
 */

/** Routes served by the synapse-rust `verification_routes` module. */
export const VERIFICATION_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/keys/device_signing/requests" },
    { method: "PUT", path: "/_matrix/client/r0/keys/device_signing/verify_accept" },
    { method: "POST", path: "/_matrix/client/r0/keys/device_signing/verify_cancel" },
    { method: "POST", path: "/_matrix/client/r0/keys/device_signing/verify_done" },
    { method: "POST", path: "/_matrix/client/r0/keys/device_signing/verify_key_agreement" },
    { method: "POST", path: "/_matrix/client/r0/keys/device_signing/verify_mac" },
    { method: "POST", path: "/_matrix/client/r0/keys/device_signing/verify_start" },
    { method: "POST", path: "/_matrix/client/r0/keys/qr_code/scan" },
    { method: "GET", path: "/_matrix/client/r0/keys/qr_code/show" },
    { method: "POST", path: "/_matrix/client/r0/keys/verification/request" },
    { method: "GET", path: "/_matrix/client/r0/keys/verification/{transaction_id}" },
    { method: "POST", path: "/_matrix/client/r0/keys/verification/{transaction_id}/cancel" },
    { method: "GET", path: "/_matrix/client/v1/keys/device_signing/requests" },
    { method: "PUT", path: "/_matrix/client/v1/keys/device_signing/verify_accept" },
    { method: "POST", path: "/_matrix/client/v1/keys/device_signing/verify_cancel" },
    { method: "POST", path: "/_matrix/client/v1/keys/device_signing/verify_done" },
    { method: "POST", path: "/_matrix/client/v1/keys/device_signing/verify_key_agreement" },
    { method: "POST", path: "/_matrix/client/v1/keys/device_signing/verify_mac" },
    { method: "POST", path: "/_matrix/client/v1/keys/device_signing/verify_start" },
    { method: "POST", path: "/_matrix/client/v1/keys/qr_code/scan" },
    { method: "GET", path: "/_matrix/client/v1/keys/qr_code/show" },
    { method: "POST", path: "/_matrix/client/v1/keys/verification/request" },
    { method: "GET", path: "/_matrix/client/v1/keys/verification/{transaction_id}" },
    { method: "POST", path: "/_matrix/client/v1/keys/verification/{transaction_id}/cancel" },
    { method: "GET", path: "/_matrix/client/v3/keys/device_signing/requests" },
    { method: "PUT", path: "/_matrix/client/v3/keys/device_signing/verify_accept" },
    { method: "POST", path: "/_matrix/client/v3/keys/device_signing/verify_cancel" },
    { method: "POST", path: "/_matrix/client/v3/keys/device_signing/verify_done" },
    { method: "POST", path: "/_matrix/client/v3/keys/device_signing/verify_key_agreement" },
    { method: "POST", path: "/_matrix/client/v3/keys/device_signing/verify_mac" },
    { method: "POST", path: "/_matrix/client/v3/keys/device_signing/verify_start" },
    { method: "POST", path: "/_matrix/client/v3/keys/qr_code/scan" },
    { method: "GET", path: "/_matrix/client/v3/keys/qr_code/show" },
    { method: "POST", path: "/_matrix/client/v3/keys/verification/request" },
    { method: "GET", path: "/_matrix/client/v3/keys/verification/{transaction_id}" },
    { method: "POST", path: "/_matrix/client/v3/keys/verification/{transaction_id}/cancel" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `VERIFICATION_ROUTES`. */
export type VerificationRoute = (typeof VERIFICATION_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type VerificationMethod = VerificationRoute["method"];

/** Path templates referenced by this module. */
export type VerificationPath = VerificationRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type VerificationReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${VerificationReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type VerificationPathPattern = VerificationReplaceBraces<VerificationPath>;
