/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/federation.json
 */

import { FEDERATION_ROUTES } from "./route-table";

export const FEDERATION_ROUTES_ENTRY_COUNT = 52 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _FederationEntryCountAssertion: 52 = FEDERATION_ROUTES.length;
void _FederationEntryCountAssertion;

export const FEDERATION_ROUTES_STATUS_SCENARIOS = [
] as const;

export type FederationStatusScenario = (typeof FEDERATION_ROUTES_STATUS_SCENARIOS)[number];

export const FEDERATION_ROUTES_ERROR_SCENARIOS = [
] as const;

export type FederationErrorScenario = (typeof FEDERATION_ROUTES_ERROR_SCENARIOS)[number];

export const FEDERATION_ROUTES_ERRCODES = [
] as const;

export type FederationErrcode = (typeof FEDERATION_ROUTES_ERRCODES)[number];
