// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/federation.md

// ─── Federation Version ──────────────────────────────────────

/** Response from GET /_matrix/federation/v1/version */
export interface FederationVersionResponse {
    /** Server version info */
    server: {
        /** Server version string */
        version?: string;
        /** Server name */
        name?: string;
    };
}

// ─── Federation Ping ─────────────────────────────────────────

/** Response from federation ping / status check */
export interface FederationPingResponse {
    /** Whether the server is online */
    online: boolean;
    /** Timestamp of last successful connection (ms) */
    last_successful_connect?: number;
    /** Latency in ms */
    latency?: number;
}

// ─── Federation Queue Status ─────────────────────────────────

/** Federation destination server info */
export interface FederationServer {
    /** Server name (e.g. "matrix.org") */
    serverName: string;
    /** Timestamp when the server was added (ms) */
    addedAt?: number;
    /** Reason for adding */
    reason?: string;
}

/** Federation server status */
export interface FederationStatus {
    /** Whether the server is online */
    online: boolean;
    /** Timestamp of last successful connection (ms) */
    lastSuccessfulConnect?: number;
    /** Latency in ms */
    latency?: number;
}

// ─── Federation Blacklist ────────────────────────────────────

/** A single blacklist entry */
export interface FederationBlacklistEntry {
    /** Server name that is blacklisted */
    serverName: string;
    /** Reason for blacklisting */
    reason?: string;
    /** Timestamp when the entry was added (ms) */
    addedAt: number;
    /** User ID who added the entry */
    addedBy?: string;
}

/** Response from GET /federation/blacklist */
export interface FederationBlacklistResponse {
    /** List of blacklist entries */
    blacklist?: FederationBlacklistEntry[];
}

// ─── Federation Public Rooms ─────────────────────────────────

/** Response from GET /_matrix/federation/v1/publicRooms */
export interface FederationPublicRoomsResponse {
    /** Chunk of room entries */
    chunk: unknown[];
    /** Token for the next batch */
    next_batch?: string;
    /** Token for the previous batch */
    prev_batch?: string;
}

// ─── Federation Query Directory ──────────────────────────────

/** Response from GET /_matrix/federation/v1/query/directory */
export interface FederationDirectoryResponse {
    /** Room ID resolved from the alias */
    room_id: string;
    /** List of servers that know about this room */
    servers: string[];
}
