/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Federation 模块契约
 * Source:        docs/api-contract/generated/modules/federation.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  ef9bd5d4d22c35afba65b2b5452278f6a0a28115
 */

/** Routes served by the synapse-rust `federation` module. */
export const FEDERATION_ROUTES = [
    { method: "GET", path: "/_matrix/federation/v1" },
    { method: "GET", path: "/_matrix/federation/v1/backfill/{room_id}" },
    { method: "GET", path: "/_matrix/federation/v1/event/{event_id}" },
    { method: "GET", path: "/_matrix/federation/v1/event_auth" },
    { method: "PUT", path: "/_matrix/federation/v1/exchange_third_party_invite/{room_id}" },
    { method: "GET", path: "/_matrix/federation/v1/get_event_auth/{room_id}/{event_id}" },
    { method: "GET", path: "/_matrix/federation/v1/get_joining_rules/{room_id}" },
    { method: "POST", path: "/_matrix/federation/v1/get_missing_events/{room_id}" },
    { method: "GET", path: "/_matrix/federation/v1/hierarchy/{room_id}" },
    { method: "PUT", path: "/_matrix/federation/v1/invite/{room_id}/{event_id}" },
    { method: "POST", path: "/_matrix/federation/v1/keys/claim" },
    { method: "POST", path: "/_matrix/federation/v1/keys/query" },
    { method: "POST", path: "/_matrix/federation/v1/keys/upload" },
    { method: "PUT", path: "/_matrix/federation/v1/knock/{room_id}/{user_id}" },
    { method: "GET", path: "/_matrix/federation/v1/make_join/{room_id}/{user_id}" },
    { method: "GET", path: "/_matrix/federation/v1/make_leave/{room_id}/{user_id}" },
    { method: "GET", path: "/_matrix/federation/v1/media/download/{server_name}/{media_id}" },
    { method: "GET", path: "/_matrix/federation/v1/media/thumbnail/{server_name}/{media_id}" },
    { method: "GET", path: "/_matrix/federation/v1/members/{room_id}" },
    { method: "GET", path: "/_matrix/federation/v1/members/{room_id}/joined" },
    { method: "GET", path: "/_matrix/federation/v1/openid/userinfo" },
    { method: "GET", path: "/_matrix/federation/v1/publicRooms" },
    { method: "POST", path: "/_matrix/federation/v1/publicRooms" },
    { method: "GET", path: "/_matrix/federation/v1/query/auth" },
    { method: "GET", path: "/_matrix/federation/v1/query/destination" },
    { method: "GET", path: "/_matrix/federation/v1/query/directory" },
    { method: "GET", path: "/_matrix/federation/v1/query/directory/room/{room_id}" },
    { method: "GET", path: "/_matrix/federation/v1/query/profile" },
    { method: "GET", path: "/_matrix/federation/v1/query/profile/{user_id}" },
    { method: "GET", path: "/_matrix/federation/v1/room/{room_id}/{event_id}" },
    { method: "GET", path: "/_matrix/federation/v1/room_auth/{room_id}" },
    { method: "PUT", path: "/_matrix/federation/v1/send/{txn_id}" },
    { method: "PUT", path: "/_matrix/federation/v1/send_join/{room_id}/{event_id}" },
    { method: "PUT", path: "/_matrix/federation/v1/send_leave/{room_id}/{event_id}" },
    { method: "GET", path: "/_matrix/federation/v1/state/{room_id}" },
    { method: "GET", path: "/_matrix/federation/v1/state_ids/{room_id}" },
    { method: "POST", path: "/_matrix/federation/v1/thirdparty/invite" },
    { method: "GET", path: "/_matrix/federation/v1/timestamp_to_event/{room_id}" },
    { method: "GET", path: "/_matrix/federation/v1/user/devices/{user_id}" },
    { method: "POST", path: "/_matrix/federation/v1/user/keys/claim" },
    { method: "POST", path: "/_matrix/federation/v1/user/keys/query" },
    { method: "POST", path: "/_matrix/federation/v1/user/keys/upload" },
    { method: "GET", path: "/_matrix/federation/v1/version" },
    { method: "PUT", path: "/_matrix/federation/v2/invite/{room_id}/{event_id}" },
    { method: "POST", path: "/_matrix/federation/v2/key/clone" },
    { method: "GET", path: "/_matrix/federation/v2/query/{server_name}/{key_id}" },
    { method: "PUT", path: "/_matrix/federation/v2/send_join/{room_id}/{event_id}" },
    { method: "PUT", path: "/_matrix/federation/v2/send_leave/{room_id}/{event_id}" },
    { method: "GET", path: "/_matrix/federation/v2/server" },
    { method: "POST", path: "/_matrix/federation/v2/user/keys/query" },
    { method: "GET", path: "/_matrix/key/v2/query/{server_name}/{key_id}" },
    { method: "GET", path: "/_matrix/key/v2/server" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `FEDERATION_ROUTES`. */
export type FederationRoute = (typeof FEDERATION_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type FederationMethod = FederationRoute["method"];

/** Path templates referenced by this module. */
export type FederationPath = FederationRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type FederationReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${FederationReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type FederationPathPattern = FederationReplaceBraces<FederationPath>;
