/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Reactions
 * Source:        docs/api-contract/generated/modules/reactions.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  b3c5153fc5fa969a2caa04d8e506b18655b349a6
 */

/** Routes served by the synapse-rust `reactions` module. */
export const REACTIONS_ROUTES = [
    { method: "PUT", path: "/_matrix/client/r0/rooms/{room_id}/send/m.reaction/{txn_id}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/send/m.reaction/{txn_id}" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `REACTIONS_ROUTES`. */
export type ReactionsRoute = (typeof REACTIONS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type ReactionsMethod = ReactionsRoute["method"];

/** Path templates referenced by this module. */
export type ReactionsPath = ReactionsRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type ReactionsReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${ReactionsReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type ReactionsPathPattern = ReactionsReplaceBraces<ReactionsPath>;
