/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { FRIEND_ROUTES } from "./route-table";

export const FRIEND_ROUTES_ENTRY_COUNT = 64 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _FriendEntryCountAssertion: 64 = FRIEND_ROUTES.length;
void _FriendEntryCountAssertion;

export const FRIEND_ROUTES_STATUS_SCENARIOS = [
] as const;

export type FriendStatusScenario = (typeof FRIEND_ROUTES_STATUS_SCENARIOS)[number];

export const FRIEND_ROUTES_ERROR_SCENARIOS = [
] as const;

export type FriendErrorScenario = (typeof FRIEND_ROUTES_ERROR_SCENARIOS)[number];

export const FRIEND_ROUTES_ERRCODES = [
] as const;

export type FriendErrcode = (typeof FRIEND_ROUTES_ERRCODES)[number];
