// Auto-generated by contract:codegen. Do not edit manually.

/** A friend entry in the friend list. */
export interface FriendDto {
    user_id: string;
    reason?: string;
    since?: number;
    display_name?: string;
    displayname?: string;
    username?: string;
    avatar_url?: string;
    note?: string;
    presence?: string;
    online?: boolean;
    last_active_ts?: number;
    last_seen_ts?: number;
    added_ts?: number;
    status?: "favorite" | "normal" | "blocked" | "hidden" | string;
    dm_room_id?: string;
    dm_room_active?: boolean;
    dm_room_state?: string;
    dm_room_updated_ts?: number;
    dm_room_affected_user_id?: string;
    dm_room_changed_by?: string;
    dm_room_reason?: string;
}

/** A friend request (incoming or outgoing). */
export interface FriendRequestDto {
    user_id: string;
    reason?: string;
    status: "pending" | "accepted" | "rejected" | "cancelled";
    timestamp?: number;
    display_name?: string;
    displayname?: string;
    avatar_url?: string;
    message?: string;
    direction?: "incoming" | "outgoing";
    request_id?: string;
}

/** GET /_matrix/client/v3/friends response. */
export interface FriendListResponse {
    room_id?: string;
    total?: number;
    friends?: FriendDto[];
}

/** GET /_matrix/client/v1/friends/request/received or /friends/requests/incoming response. */
export interface FriendRequestsResponse {
    requests?: FriendRequestDto[];
}

/** POST /_matrix/client/v1/friends/request response. */
export interface SendFriendRequestResponse {
    request_id?: string;
    status?: string;
}

/** POST /_matrix/client/v1/friends/request/{userId}/accept response. */
export interface AcceptFriendRequestResponse {
    room_id?: string;
}

/** GET /_matrix/client/v3/friends/check/{userId} response. */
export interface FriendshipCheckResponse {
    user_id: string;
    is_friend: boolean;
    are_friends: boolean;
}

/** GET /_matrix/client/v1/friends/{userId}/status response. */
export interface FriendStatusInfoResponse {
    user_id: string;
    status: string;
    is_friend?: boolean;
    are_friends?: boolean;
}

/** GET /_matrix/client/v3/friends/search response. */
export interface FriendSearchResponse {
    results?: FriendSearchResultDto[];
    count?: number;
    mode?: string;
    limited?: boolean;
    retry_after_seconds?: number;
}

/** A single search result from friend search. */
export interface FriendSearchResultDto {
    user_id: string;
    username?: string;
    displayname?: string;
    avatar_url?: string;
    presence?: string;
    online?: boolean;
    last_active_ts?: number;
    last_seen_ts?: number;
    created_ts?: number;
    match_score?: number;
    match_type?: string;
}

/** A friend group. */
export interface FriendGroupDto {
    id: string;
    name: string;
    members: string[];
    created_at?: number;
    updated_ts?: number;
}

/** GET /_matrix/client/v1/friends/groups response. */
export interface FriendGroupsResponse {
    groups?: FriendGroupDto[];
}

/** POST /_matrix/client/v1/friends/groups response (created group). */
export interface CreateFriendGroupResponse {
    id: string;
    name: string;
    members?: string[];
    created_at?: number;
    updated_ts?: number;
}

/** GET /_matrix/client/v1/friends/suggestions response. */
export interface FriendSuggestionsResponse {
    suggestions?: FriendDto[];
    total?: number;
}
