/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Friend 模块契约
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       29 (既有条目 ∪ ledger 清单 ∪ ROUTE_CONTRACT.md，按 (method, path) 去重)
 */

/** Routes served by the synapse-rust `friend` module (mirrored from the backend contract). */
export const FRIEND_ROUTES = [
    { method: "DELETE", path: "/_matrix/vendor/v1/friends/groups/{group_id}" },
    { method: "DELETE", path: "/_matrix/vendor/v1/friends/groups/{group_id}/remove/{user_id}" },
    { method: "DELETE", path: "/_matrix/vendor/v1/friends/{user_id}" },
    { method: "GET", path: "/_matrix/vendor/v1/friends" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/check/{user_id}" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/dm/{user_id}" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/groups" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/groups/{group_id}/friends" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/request/received" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/requests/incoming" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/requests/outgoing" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/search" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/suggestions" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/{user_id}/groups" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/{user_id}/info" },
    { method: "GET", path: "/_matrix/vendor/v1/friends/{user_id}/status" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/groups/{group_id}/add/{user_id}" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/request" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/request/{user_id}/accept" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/request/{user_id}/cancel" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/request/{user_id}/reject" },
    { method: "PUT", path: "/_matrix/vendor/v1/friends/groups/{group_id}/name" },
    { method: "PUT", path: "/_matrix/vendor/v1/friends/{user_id}/displayname" },
    { method: "PUT", path: "/_matrix/vendor/v1/friends/{user_id}/note" },
    { method: "POST", path: "/_matrix/vendor/v1/friends" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/dm/{user_id}" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/groups" },
    { method: "POST", path: "/_matrix/vendor/v1/friends/search" },
    { method: "PUT", path: "/_matrix/vendor/v1/friends/{user_id}/status" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `FRIEND_ROUTES`. */
export type FriendRoute = (typeof FRIEND_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type FriendMethod = FriendRoute["method"];

/** Path templates referenced by this module. */
export type FriendPath = FriendRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type FriendReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${FriendReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type FriendPathPattern = FriendReplaceBraces<FriendPath>;
