/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Friend 模块契约
 * Source:        docs/api-contract/generated/modules/friend_room.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  861502da33164d008ef8ebecb8a87245a47ab5e0
 */

/** Routes served by the synapse-rust `friend_room` module. */
export const FRIEND_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/friends/check/{user_id}" },
    { method: "GET", path: "/_matrix/client/r0/friends/groups" },
    { method: "POST", path: "/_matrix/client/r0/friends/groups" },
    { method: "DELETE", path: "/_matrix/client/r0/friends/groups/{group_id}" },
    { method: "POST", path: "/_matrix/client/r0/friends/groups/{group_id}/add/{user_id}" },
    { method: "GET", path: "/_matrix/client/r0/friends/groups/{group_id}/friends" },
    { method: "PUT", path: "/_matrix/client/r0/friends/groups/{group_id}/name" },
    { method: "DELETE", path: "/_matrix/client/r0/friends/groups/{group_id}/remove/{user_id}" },
    { method: "POST", path: "/_matrix/client/r0/friends/request" },
    { method: "GET", path: "/_matrix/client/r0/friends/request/received" },
    { method: "POST", path: "/_matrix/client/r0/friends/request/{user_id}/accept" },
    { method: "POST", path: "/_matrix/client/r0/friends/request/{user_id}/cancel" },
    { method: "POST", path: "/_matrix/client/r0/friends/request/{user_id}/reject" },
    { method: "GET", path: "/_matrix/client/r0/friends/requests/incoming" },
    { method: "GET", path: "/_matrix/client/r0/friends/requests/outgoing" },
    { method: "GET", path: "/_matrix/client/r0/friends/search" },
    { method: "GET", path: "/_matrix/client/r0/friends/suggestions" },
    { method: "DELETE", path: "/_matrix/client/r0/friends/{user_id}" },
    { method: "PUT", path: "/_matrix/client/r0/friends/{user_id}/displayname" },
    { method: "GET", path: "/_matrix/client/r0/friends/{user_id}/groups" },
    { method: "GET", path: "/_matrix/client/r0/friends/{user_id}/info" },
    { method: "PUT", path: "/_matrix/client/r0/friends/{user_id}/note" },
    { method: "GET", path: "/_matrix/client/r0/friends/{user_id}/status" },
    { method: "PUT", path: "/_matrix/client/r0/friends/{user_id}/status" },
    { method: "GET", path: "/_matrix/client/r0/friendships" },
    { method: "POST", path: "/_matrix/client/r0/friendships" },
    { method: "GET", path: "/_matrix/client/v1/friends" },
    { method: "POST", path: "/_matrix/client/v1/friends" },
    { method: "GET", path: "/_matrix/client/v1/friends/check/{user_id}" },
    { method: "GET", path: "/_matrix/client/v1/friends/groups" },
    { method: "POST", path: "/_matrix/client/v1/friends/groups" },
    { method: "DELETE", path: "/_matrix/client/v1/friends/groups/{group_id}" },
    { method: "POST", path: "/_matrix/client/v1/friends/groups/{group_id}/add/{user_id}" },
    { method: "GET", path: "/_matrix/client/v1/friends/groups/{group_id}/friends" },
    { method: "PUT", path: "/_matrix/client/v1/friends/groups/{group_id}/name" },
    { method: "DELETE", path: "/_matrix/client/v1/friends/groups/{group_id}/remove/{user_id}" },
    { method: "POST", path: "/_matrix/client/v1/friends/request" },
    { method: "GET", path: "/_matrix/client/v1/friends/request/received" },
    { method: "POST", path: "/_matrix/client/v1/friends/request/{user_id}/accept" },
    { method: "POST", path: "/_matrix/client/v1/friends/request/{user_id}/cancel" },
    { method: "POST", path: "/_matrix/client/v1/friends/request/{user_id}/reject" },
    { method: "GET", path: "/_matrix/client/v1/friends/requests/incoming" },
    { method: "GET", path: "/_matrix/client/v1/friends/requests/outgoing" },
    { method: "GET", path: "/_matrix/client/v1/friends/search" },
    { method: "POST", path: "/_matrix/client/v1/friends/search" },
    { method: "GET", path: "/_matrix/client/v1/friends/suggestions" },
    { method: "DELETE", path: "/_matrix/client/v1/friends/{user_id}" },
    { method: "PUT", path: "/_matrix/client/v1/friends/{user_id}/displayname" },
    { method: "GET", path: "/_matrix/client/v1/friends/{user_id}/groups" },
    { method: "GET", path: "/_matrix/client/v1/friends/{user_id}/info" },
    { method: "PUT", path: "/_matrix/client/v1/friends/{user_id}/note" },
    { method: "GET", path: "/_matrix/client/v1/friends/{user_id}/status" },
    { method: "PUT", path: "/_matrix/client/v1/friends/{user_id}/status" },
    { method: "GET", path: "/_matrix/client/v3/friends" },
    { method: "POST", path: "/_matrix/client/v3/friends" },
    { method: "GET", path: "/_matrix/client/v3/friends/requests/incoming" },
    { method: "GET", path: "/_matrix/client/v3/friends/requests/outgoing" },
    { method: "GET", path: "/_matrix/client/v3/friends/search" },
    { method: "POST", path: "/_matrix/client/v3/friends/search" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `FRIEND_ROUTES`. */
export type FriendRoute = (typeof FRIEND_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type FriendMethod = FriendRoute["method"];

/** Path templates referenced by this module. */
export type FriendPath = FriendRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type FriendReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${FriendReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type FriendPathPattern = FriendReplaceBraces<FriendPath>;
