/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/media.json
 */

import { MEDIA_ROUTES } from "./route-table";

export const MEDIA_ROUTES_ENTRY_COUNT = 32 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _MediaEntryCountAssertion: 32 = MEDIA_ROUTES.length;
void _MediaEntryCountAssertion;

export const MEDIA_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "上传 body 为空等参数错误" },
    { status: 401, note: "需用户认证的接口未登录" },
    { status: 409, note: "具名上传使用了已存在 ID" },
    { status: 404, note: "媒体不存在" },
] as const;

export type MediaStatusScenario = (typeof MEDIA_ROUTES_STATUS_SCENARIOS)[number];

export const MEDIA_ROUTES_ERROR_SCENARIOS = [
] as const;

export type MediaErrorScenario = (typeof MEDIA_ROUTES_ERROR_SCENARIOS)[number];

export const MEDIA_ROUTES_ERRCODES = [
] as const;

export type MediaErrcode = (typeof MEDIA_ROUTES_ERRCODES)[number];
