// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/media.md

// ─── Upload ───────────────────────────────────────────────────

/** Upload options */
export interface UploadRequest {
    /** File name (optional) */
    name?: string;
    /** MIME content type (optional) */
    type?: string;
}

/** Response from POST /_matrix/media/v3/upload */
export interface UploadResponse {
    /** MXC URI of the uploaded content */
    content_uri: string;
}

// ─── Media Config ─────────────────────────────────────────────

/** Response from GET /_matrix/media/v3/config */
export interface MediaConfig {
    /** Maximum upload size in bytes */
    "m.upload.size"?: number;
}

// ─── URL Preview ──────────────────────────────────────────────

/** Response from GET /_matrix/media/v3/preview_url */
export interface UrlPreview {
    /** Previewed URL */
    url?: string;
    /** Page title */
    title?: string;
    /** Page description */
    description?: string;
    /** Preview image URL */
    image_url?: string;
    /** Image MXC URI */
    image?: string;
    /** OpenGraph image URL */
    og_image?: string;
    /** Matrix image reference */
    "matrix:image"?: string;
}

// ─── Download Options ─────────────────────────────────────────

/** Options for constructing a media download URL */
export interface MediaDownloadUrlOptions {
    /** Filename to suggest in the Content-Disposition header */
    filename?: string;
    /** Whether to allow non-MXC direct links */
    allowDirectLinks?: boolean;
    /** Whether to allow server redirects */
    allowRedirects?: boolean;
    /** Whether to use authenticated media endpoints */
    useAuthentication?: boolean;
    /** Media API version to use */
    version?: "v1" | "v3" | "r1";
}

// ─── Thumbnail Options ────────────────────────────────────────

/** Options for constructing a media thumbnail URL */
export interface MediaThumbnailUrlOptions {
    /** Desired thumbnail width in pixels */
    width?: number;
    /** Desired thumbnail height in pixels */
    height?: number;
    /** Thumbnail resizing method: "crop" or "scale" */
    method?: "crop" | "scale";
    /** Whether to allow non-MXC direct links */
    allowDirectLinks?: boolean;
    /** Whether to allow server redirects */
    allowRedirects?: boolean;
    /** Whether to use authenticated media endpoints */
    useAuthentication?: boolean;
    /** Whether to return animated thumbnails */
    animated?: boolean;
}
