/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/rendezvous.json
 */

import { RENDEZVOUS_ROUTES } from "./route-table";

export const RENDEZVOUS_ROUTES_ENTRY_COUNT = 6 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _RendezvousEntryCountAssertion: 6 = RENDEZVOUS_ROUTES.length;
void _RendezvousEntryCountAssertion;

export const RENDEZVOUS_ROUTES_STATUS_SCENARIOS = [
] as const;

export type RendezvousStatusScenario = (typeof RENDEZVOUS_ROUTES_STATUS_SCENARIOS)[number];

export const RENDEZVOUS_ROUTES_ERROR_SCENARIOS = [
    { scenario: "更新为 connected 时缺少访问令牌", httpOrErrcode: "401 / M_MISSING_TOKEN", sdkErrorType: "AuthError", handling: "更新为 connected 时缺少访问令牌" },
    { scenario: "无效的访问令牌", httpOrErrcode: "401 / M_UNKNOWN_TOKEN", sdkErrorType: "AuthError", handling: "无效的访问令牌" },
    { scenario: "缺少或提供了错误的 rendezvous key", httpOrErrcode: "401 / M_UNAUTHORIZED", sdkErrorType: "AuthError", handling: "缺少或提供了错误的 rendezvous key" },
    { scenario: "已绑定会话被其他用户越权访问", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "已绑定会话被其他用户越权访问" },
    { scenario: "会话不存在或已过期", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "会话不存在或已过期" },
    { scenario: "会话已过期", httpOrErrcode: "410 / M_RENDEZVOUS_EXPIRED", sdkErrorType: "ApiError", handling: "会话已过期" },
    { scenario: "会话已取消", httpOrErrcode: "410 / M_RENDEZVOUS_CANCELLED", sdkErrorType: "ApiError", handling: "会话已取消" },
] as const;

export type RendezvousErrorScenario = (typeof RENDEZVOUS_ROUTES_ERROR_SCENARIOS)[number];

export const RENDEZVOUS_ROUTES_ERRCODES = [
    { errcode: "M_MISSING_TOKEN", httpStatus: "401", note: "更新为 connected 时缺少访问令牌" },
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "无效的访问令牌" },
    { errcode: "M_UNAUTHORIZED", httpStatus: "401", note: "缺少或提供了错误的 rendezvous key" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "已绑定会话被其他用户越权访问" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "会话不存在或已过期" },
    { errcode: "M_RENDEZVOUS_EXPIRED", httpStatus: "410", note: "会话已过期" },
    { errcode: "M_RENDEZVOUS_CANCELLED", httpStatus: "410", note: "会话已取消" },
] as const;

export type RendezvousErrcode = (typeof RENDEZVOUS_ROUTES_ERRCODES)[number];
