/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Rendezvous
 * Source:        docs/api-contract/generated/modules/rendezvous.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  c2e43304843f9460bc5d88d93b708016306d97f1
 */

/** Routes served by the synapse-rust `rendezvous` module. */
export const RENDEZVOUS_ROUTES = [
    { method: "POST", path: "/_matrix/client/v1/rendezvous" },
    { method: "DELETE", path: "/_matrix/client/v1/rendezvous/{session_id}" },
    { method: "GET", path: "/_matrix/client/v1/rendezvous/{session_id}" },
    { method: "PUT", path: "/_matrix/client/v1/rendezvous/{session_id}" },
    { method: "GET", path: "/_matrix/client/v1/rendezvous/{session_id}/messages" },
    { method: "POST", path: "/_matrix/client/v1/rendezvous/{session_id}/messages" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `RENDEZVOUS_ROUTES`. */
export type RendezvousRoute = (typeof RENDEZVOUS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type RendezvousMethod = RendezvousRoute["method"];

/** Path templates referenced by this module. */
export type RendezvousPath = RendezvousRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type RendezvousReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${RendezvousReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type RendezvousPathPattern = RendezvousReplaceBraces<RendezvousPath>;
