/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/room.json
 */

import { ROOM_ROUTES } from "./route-table";

export const ROOM_ROUTES_ENTRY_COUNT = 134 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _RoomEntryCountAssertion: 134 = ROOM_ROUTES.length;
void _RoomEntryCountAssertion;

export const ROOM_ROUTES_STATUS_SCENARIOS = [
] as const;

export type RoomStatusScenario = (typeof ROOM_ROUTES_STATUS_SCENARIOS)[number];

export const ROOM_ROUTES_ERROR_SCENARIOS = [
] as const;

export type RoomErrorScenario = (typeof ROOM_ROUTES_ERROR_SCENARIOS)[number];

export const ROOM_ROUTES_ERRCODES = [
] as const;

export type RoomErrcode = (typeof ROOM_ROUTES_ERRCODES)[number];
