// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/room.md

// ─── Room Event Types ─────────────────────────────────────────

/** A room event (message or similar) */
export interface RoomEvent {
    /** Event content */
    content: Record<string, unknown>;
    /** Event type */
    type: string;
    /** Event ID */
    event_id: string;
    /** Sender user ID */
    sender: string;
    /** Origin server timestamp (ms) */
    origin_server_ts: number;
    /** Room ID (optional in some contexts) */
    room_id?: string;
    /** Unsigned data (e.g. redaction info) */
    unsigned?: Record<string, unknown>;
}

/** A state event with state_key */
export interface RoomStateEvent extends RoomEvent {
    /** State key (empty string for default) */
    state_key: string;
    /** Previous content (for redacted/updated state) */
    prev_content?: Record<string, unknown>;
}

// ─── Room Info Responses ──────────────────────────────────────

/** Response from GET /rooms/{roomId}/version */
export interface RoomVersionResponse {
    /** Room version string (e.g. "10") */
    room_version: string;
}

/** Response from GET /rooms/{roomId}/capabilities */
export interface RoomCapabilitiesResponse {
    /** Room capabilities map */
    capabilities: Record<string, unknown>;
}

/** Response from GET /rooms/{roomId}/metadata */
export interface RoomMetadataResponse {
    /** Room ID */
    room_id: string;
    /** Room name */
    name?: string;
    /** Room topic */
    topic?: string;
    /** Room avatar MXC URI */
    avatar_url?: string;
    /** Join rule */
    join_rule?: string;
    /** History visibility */
    history_visibility?: string;
    /** Guest access setting */
    guest_access?: string;
    /** Creation timestamp */
    created_ts?: number;
}

// ─── Room Lifecycle ───────────────────────────────────────────

/** Request body for POST /createRoom */
export interface CreateRoomRequest {
    /** Room visibility: "public" or "private" */
    visibility?: "public" | "private";
    /** Room alias localpart */
    room_alias_name?: string;
    /** Room name */
    name?: string;
    /** Room topic */
    topic?: string;
    /** Room version */
    room_version?: string;
    /** Power level content override */
    power_level_content_override?: Record<string, unknown>;
    /** Preset: "private_chat", "trusted_private_chat", or "public_chat" */
    preset?: "private_chat" | "trusted_private_chat" | "public_chat";
    /** Initial state events */
    initial_state?: Array<{
        type: string;
        state_key?: string;
        content: Record<string, unknown>;
    }>;
    /** Invitee user IDs */
    invite?: string[];
    /** Invite via 3PID */
    invite_3pid?: Array<{
        id_server: string;
        id_access_token: string;
        medium: string;
        address: string;
    }>;
    /** Creation content */
    creation_content?: Record<string, unknown>;
    /** Whether this is a direct message room */
    is_direct?: boolean;
    /** Room predecessor */
    predecessor?: {
        room_id: string;
        event_id: string;
    };
    /** Space parent */
    space?: string;
}

/** Response from POST /createRoom */
export interface CreateRoomResponse {
    /** Created room ID */
    room_id: string;
}

/** Request body for POST /join/{roomIdOrAlias} */
export interface JoinRoomRequest {
    /** Third-party signed invite */
    third_party_signed?: {
        sender: string;
        mixid: string;
        signed: {
            mxid: string;
            signatures: Record<string, Record<string, string>>;
            token: string;
        };
    };
}

/** Response from POST /join/{roomIdOrAlias} */
export interface JoinRoomResponse {
    /** Joined room ID (may differ from alias) */
    room_id: string;
}

/** Request body for POST /knock/{roomIdOrAlias} */
export interface KnockRoomRequest {
    /** Reason for knocking */
    reason?: string;
}

/** Response from POST /knock/{roomIdOrAlias} */
export interface KnockRoomResponse {
    room_id: string;
}

// ─── Members ──────────────────────────────────────────────────

/** A room member in a joined members response */
export interface RoomMember {
    /** Display name */
    display_name?: string;
    /** Avatar URL */
    avatar_url?: string;
}

/** Response from GET /rooms/{roomId}/members */
export interface GetMembersResponse {
    /** List of member state events */
    chunk: RoomStateEvent[];
}

/** Response from GET /rooms/{roomId}/joined_members */
export interface JoinedMembersResponse {
    /** Map from user ID → member info */
    joined: Record<string, RoomMember>;
}

// ─── Messages ─────────────────────────────────────────────────

/** Response from GET /rooms/{roomId}/messages */
export interface GetMessagesResponse {
    /** Message events */
    chunk: RoomEvent[];
    /** Pagination start token */
    start: string;
    /** Pagination end token (absent at start of timeline) */
    end?: string;
    /** State events at start of chunk */
    state?: RoomStateEvent[];
}

/** Response from PUT /rooms/{roomId}/send/{eventType}/{txnId} */
export interface SendEventResponse {
    /** Event ID of the sent event */
    event_id: string;
    /** Room ID (optional) */
    room_id?: string;
}

/** Response from GET /rooms/{roomId}/event/{eventId} */
export interface GetEventResponse extends RoomEvent {}

/** Response from GET /rooms/{roomId}/context/{eventId} */
export interface EventContextResponse {
    /** The requested event */
    event: RoomEvent;
    /** Events before the requested event */
    events_before: RoomEvent[];
    /** Events after the requested event */
    events_after: RoomEvent[];
    /** Pagination start token */
    start: string;
    /** Pagination end token */
    end: string;
    /** State events at the requested event */
    state: RoomStateEvent[];
}

// ─── Room Actions ─────────────────────────────────────────────

/** Request body for POST /rooms/{roomId}/invite */
export interface InviteRequest {
    /** User ID to invite */
    user_id: string;
    /** Reason for the invite */
    reason?: string;
}

/** Request body for POST /rooms/{roomId}/kick */
export interface KickRequest {
    /** User ID to kick */
    user_id: string;
    /** Reason for the kick */
    reason?: string;
}

/** Request body for POST /rooms/{roomId}/ban */
export interface BanRequest {
    /** User ID to ban */
    user_id: string;
    /** Reason for the ban */
    reason?: string;
}

/** Request body for POST /rooms/{roomId}/unban */
export interface UnbanRequest {
    /** User ID to unban */
    user_id: string;
}

/** Request body for PUT /rooms/{roomId}/redact/{eventId}/{txnId} */
export interface RedactEventRequest {
    /** Reason for redaction */
    reason?: string;
}

/** Request body for POST /rooms/{roomId}/upgrade */
export interface UpgradeRoomRequest {
    /** New room version */
    new_version: string;
    /** Additional creators to add to the new room */
    additional_creators?: string[];
}

/** Response from POST /rooms/{roomId}/upgrade */
export interface UpgradeRoomResponse {
    /** Replacement room ID */
    replacement_room: string;
}

/** Request body for POST /rooms/{roomId}/report */
export interface ReportRoomRequest {
    /** Reason for the report */
    reason: string;
}

// ─── Room Directory ───────────────────────────────────────────

/** Response from GET /directory/list/room/{roomId} */
export interface RoomDirectoryVisibilityResponse {
    /** Visibility: "public" or "private" */
    visibility: "public" | "private";
}

/** Request body for PUT /directory/list/room/{roomId} */
export interface SetRoomDirectoryVisibilityRequest {
    visibility: "public" | "private";
}

/** Response from GET /directory/room/{roomAlias} */
export interface RoomIdForAliasResponse {
    /** Room ID */
    room_id: string;
    /** Candidate servers for the room */
    servers: string[];
}

/** Request body for PUT /directory/room/{roomAlias} */
export interface CreateAliasRequest {
    /** Room ID to map the alias to */
    room_id: string;
}

/** Response from GET /rooms/{roomId}/aliases */
export interface LocalAliasesResponse {
    /** List of local aliases */
    aliases: string[];
}

// ─── Room Hierarchy ───────────────────────────────────────────

/** A room in the hierarchy */
export interface RoomHierarchyRoom {
    room_id: string;
    name?: string;
    topic?: string;
    avatar_url?: string;
    join_rule?: string;
    room_type?: string;
    num_joined_members?: number;
    children_state?: RoomStateEvent[];
}

/** Response from GET /rooms/{roomId}/hierarchy */
export interface RoomHierarchyResponse {
    /** Rooms in the hierarchy */
    rooms: RoomHierarchyRoom[];
    /** Next batch token */
    next_batch?: string;
}

// ─── Tags ─────────────────────────────────────────────────────

/** Tag metadata */
export interface TagMetadata {
    /** Order of the tag (floating point) */
    order?: number;
}

/** Tags for a room */
export interface TagsResponse {
    tags: Record<string, TagMetadata>;
}

// ─── Guest Access ─────────────────────────────────────────────

/** Request body for PUT /rooms/{roomId}/guest_access */
export interface GuestAccessRequest {
    /** Guest access setting */
    guest_access: "can_join" | "forbidden";
}
