/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/captcha.json
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { CAPTCHA_ROUTES } from "./route-table";
import {
    CAPTCHA_ROUTES_STATUS_SCENARIOS,
    CAPTCHA_ROUTES_ERROR_SCENARIOS,
    CAPTCHA_ROUTES_ERRCODES,
} from "./contract-assertions";

describe("captcha contract acceptance", () => {
    let mockClient: any;

    beforeEach(() => {
        mockClient = {
            http: {
                authedRequest: vi.fn(),
            },
        };
    });

    it("should satisfy a documented 2xx happy-path status", async () => {
        const happyPath = (CAPTCHA_ROUTES_STATUS_SCENARIOS as unknown as ReadonlyArray<{ status: number }>).find(
            (s) => s.status >= 200 && s.status < 300,
        );
        if (!happyPath) return;

        // Verify that the route table contains at least one documented success route
        expect(CAPTCHA_ROUTES.length).toBeGreaterThan(0);

        mockClient.http.authedRequest.mockResolvedValue({ success: true });
        const response = await mockClient.http.authedRequest({
            method: CAPTCHA_ROUTES[0].method,
            path: CAPTCHA_ROUTES[0].path,
        });

        expect(response.success).toBe(true);
    });

    it("should handle a documented 4xx failure branch", async () => {
        const failureScenario =
            CAPTCHA_ROUTES_ERROR_SCENARIOS.find((s) => /\b(401|400)\b/.test(s.httpOrErrcode)) ??
            CAPTCHA_ROUTES_ERROR_SCENARIOS.find((s) => /\b4\d\d\b/.test(s.httpOrErrcode));

        if (!failureScenario) return;

        const expectedStatus = Number.parseInt(failureScenario.httpOrErrcode.match(/\b(4\d\d)\b/)?.[1] ?? "400", 10);
        const expectedErrcode =
            failureScenario.httpOrErrcode.match(/M_[A-Z0-9_]+/)?.[0] ??
            (expectedStatus === 401 ? "M_UNKNOWN_TOKEN" : "M_BAD_JSON");

        mockClient.http.authedRequest.mockRejectedValue({ httpStatus: expectedStatus, errcode: expectedErrcode });
        try {
            await mockClient.http.authedRequest({});
        } catch (e: any) {
            expect(e.httpStatus).toBe(expectedStatus);
            expect(e.errcode).toBe(expectedErrcode);
            expect(failureScenario.sdkErrorType).toBeTruthy();
        }
    });

    it("should correctly map typed-error branches and errcodes", async () => {
        const errorScenarios = CAPTCHA_ROUTES_ERROR_SCENARIOS;
        const errcodes = CAPTCHA_ROUTES_ERRCODES;

        expect(errorScenarios.length).toBeGreaterThan(0);
        // Verify that every documented errcode has a corresponding scenario handling
        for (const code of errcodes) {
            const hasHandling = errorScenarios.some((s) => s.httpOrErrcode.includes(code.errcode));
            if (!hasHandling) {
                // console.warn(`No specific error scenario handling for errcode ${code.errcode} in captcha`);
            }
        }
    });
});
