/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/captcha.md
 */

/**
 * DTO snippets extracted from the contract doc for `captcha`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface CaptchaRequestDto {
    session: string;
}

export interface CaptchaResponseDto {
    captcha_url: string;
}

export interface CaptchaAdminResponseDto {
    cleaned: number;
}
