// Auto-generated by contract:codegen. Do not edit manually.

/** POST /_matrix/client/v3/register/captcha/send response. */
export interface CaptchaSendResponseDto {
    captcha_id: string;
    expires_in: number;
    captcha_type: string;
}

/** POST /_matrix/client/v3/register/captcha/send request body. */
export interface CaptchaSendRequestDto {
    captcha_type: string;
    target: string;
    template_name?: string;
}

/** POST /_matrix/client/v3/register/captcha/verify response. */
export interface CaptchaVerifyResponseDto {
    verified: boolean;
}

/** POST /_matrix/client/v3/register/captcha/verify request body. */
export interface CaptchaVerifyRequestDto {
    captcha_id: string;
    code: string;
}

/** GET /_matrix/client/v3/register/captcha/status response. */
export interface CaptchaStatusResponseDto {
    captcha_id: string;
    captcha_type: string;
    target: string;
    status: string;
    attempt_count: number;
    max_attempts: number;
    expires_at: number;
    created_at: number;
}

/** POST /_synapse/admin/v1/captcha/cleanup response. */
export interface CaptchaCleanupResponseDto {
    cleaned_count: number;
    message: string;
}
