/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        CAPTCHA
 * Source:        docs/api-contract/generated/modules/captcha.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  18d2793ec6cb6cd2ded0ee49dbd9ba022a5a6b54
 */

/** Routes served by the synapse-rust `captcha` module. */
export const CAPTCHA_ROUTES = [
    { method: "POST", path: "/_matrix/client/r0/register/captcha/send" },
    { method: "GET", path: "/_matrix/client/r0/register/captcha/status" },
    { method: "POST", path: "/_matrix/client/r0/register/captcha/verify" },
    { method: "POST", path: "/_matrix/client/v3/register/captcha/send" },
    { method: "GET", path: "/_matrix/client/v3/register/captcha/status" },
    { method: "POST", path: "/_matrix/client/v3/register/captcha/verify" },
    { method: "POST", path: "/_synapse/admin/v1/captcha/cleanup" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `CAPTCHA_ROUTES`. */
export type CaptchaRoute = (typeof CAPTCHA_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type CaptchaMethod = CaptchaRoute["method"];

/** Path templates referenced by this module. */
export type CaptchaPath = CaptchaRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type CaptchaReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${CaptchaReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type CaptchaPathPattern = CaptchaReplaceBraces<CaptchaPath>;
