/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/thread.json
 */

import { THREAD_ROUTES } from "./route-table";

export const THREAD_ROUTES_ENTRY_COUNT = 21 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _ThreadEntryCountAssertion: 21 = THREAD_ROUTES.length;
void _ThreadEntryCountAssertion;

export const THREAD_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 204, note: "删除线程成功且无响应体" },
    { status: 400, note: "room_id 缺失、查询参数错误或请求体字段不完整" },
    { status: 401, note: "需认证接口缺少或使用无效令牌" },
    { status: 404, note: "线程不存在" },
    { status: 500, note: "存储层或 service 层内部错误" },
] as const;

export type ThreadStatusScenario = (typeof THREAD_ROUTES_STATUS_SCENARIOS)[number];

export const THREAD_ROUTES_ERROR_SCENARIOS = [
] as const;

export type ThreadErrorScenario = (typeof THREAD_ROUTES_ERROR_SCENARIOS)[number];

export const THREAD_ROUTES_ERRCODES = [
] as const;

export type ThreadErrcode = (typeof THREAD_ROUTES_ERRCODES)[number];
