// Auto-generated by contract:codegen. Do not edit manually.

/** Summary of a thread as returned by list/detail endpoints. */
export interface ThreadSummaryDto {
    id: number;
    room_id: string;
    thread_id: string;
    root_event_id: string;
    root_sender: string;
    root_content: Record<string, unknown>;
    root_origin_server_ts: number;
    latest_event_id: string | null;
    latest_sender: string | null;
    latest_content: Record<string, unknown> | null;
    latest_origin_server_ts: number | null;
    reply_count: number;
    participants: unknown;
    is_frozen: boolean;
    created_ts: number;
    updated_ts: number;
}

/** Thread read receipt. */
export interface ThreadReadReceiptDto {
    id: number;
    room_id: string;
    thread_id: string;
    user_id: string;
    last_read_event_id: string | null;
    last_read_ts: number;
    unread_count: number;
    updated_ts: number;
}

/** Thread subscription. */
export interface ThreadSubscriptionDto {
    id: number;
    room_id: string;
    thread_id: string;
    user_id: string;
    notification_level: string;
    is_muted: boolean;
    subscribed_ts: number;
    updated_ts: number;
}

/** A single thread reply. */
export interface ThreadReplyDto {
    event_id: string;
    thread_id: string;
    room_id: string;
    sender: string;
    content: Record<string, unknown>;
    origin_server_ts: number;
    in_reply_to_event_id: string | null;
    is_edited: boolean;
    is_redacted: boolean;
}

/** Thread root event in detail view. */
export interface ThreadRootDto {
    id: number;
    room_id: string;
    root_event_id: string;
    sender: string;
    thread_id: string | null;
    reply_count: number;
    last_reply_event_id: string | null;
    last_reply_sender: string | null;
    last_reply_ts: number | null;
    participants: unknown;
    is_fetched: boolean;
    created_ts: number;
    updated_ts: number | null;
}

/** POST /_matrix/client/v1/threads response — thread creation result. */
export interface ThreadCreateDto {
    thread_id: string | null;
    root_event_id: string;
    room_id: string;
    sender: string;
    reply_count: number;
    last_reply_event_id: string | null;
    last_reply_sender: string | null;
    last_reply_ts: number | null;
    participants: unknown;
    is_fetched: boolean;
    created_ts: number;
}

/** POST /_matrix/client/v1/threads request params. */
export interface ThreadCreateParamsDto {
    room_id?: string;
    root_event_id: string;
    content?: Record<string, unknown>;
    origin_server_ts?: number;
}

/** POST /_matrix/client/v1/rooms/{roomId}/threads/{threadId}/replies request params. */
export interface ThreadReplyCreateParamsDto {
    event_id: string;
    root_event_id: string;
    content: Record<string, unknown>;
    in_reply_to_event_id?: string;
    origin_server_ts?: number;
}

/** GET /_matrix/client/v1/threads or /rooms/{roomId}/threads response. */
export interface ThreadListResponseDto {
    threads: ThreadSummaryDto[];
    next_batch: string | null;
    total: number;
}

/** GET /_matrix/client/v1/rooms/{roomId}/threads/{threadId} response. */
export interface ThreadDetailResponseDto {
    root: ThreadRootDto;
    replies: ThreadReplyDto[];
    reply_count: number;
    participants: string[];
    summary: ThreadSummaryDto | null;
    user_receipt: ThreadReadReceiptDto | null;
    user_subscription: ThreadSubscriptionDto | null;
}

/** GET /_matrix/client/v1/threads/unread response. */
export interface ThreadUnreadResponseDto {
    threads: ThreadReadReceiptDto[];
    total_unread: number;
    total_threads: number;
}

/** GET /_matrix/client/v1/threads/subscribed response. */
export interface SubscribedThreadsResponseDto {
    threads: ThreadSummaryDto[];
    subscribed: ThreadSubscriptionDto[];
}

/** Legacy thread list chunk item (v3 endpoint). */
export interface ThreadLegacyChunkItemDto {
    event_id: string;
    sender: string;
    content: Record<string, unknown>;
    origin_server_ts: number;
}

/** Legacy thread search response (v3 endpoint). */
export interface ThreadLegacySearchResponseDto {
    chunk: ThreadLegacyChunkItemDto[];
    next_batch: string | null;
}

/** GET /_matrix/client/v1/rooms/{roomId}/threads/{threadId}/stats response. */
export interface ThreadStatisticsDto {
    id: number;
    room_id: string;
    thread_id: string;
    total_replies: number;
    total_participants: number;
    total_edits: number;
    total_redactions: number;
    first_reply_ts: number | null;
    last_reply_ts: number | null;
    avg_reply_time_ms: number | null;
    created_ts: number;
    updated_ts: number;
}

/** Query parameters for thread list endpoints. */
export interface ThreadListQueryDto {
    limit?: number;
    from?: string;
    includeAll?: boolean;
}

/** Query parameters for thread search. */
export interface ThreadSearchQueryDto {
    q: string;
    limit?: number;
}

/** Query parameters for thread replies. */
export interface ThreadRepliesQueryDto {
    limit?: number;
    from?: string;
}

/** Query parameters for thread detail. */
export interface ThreadDetailQueryDto {
    includeReplies?: boolean;
    replyLimit?: number;
}
