/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/dm.json
 */

import { DM_ROUTES } from "./route-table";

export const DM_ROUTES_ENTRY_COUNT = 8 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _DmEntryCountAssertion: 8 = DM_ROUTES.length;
void _DmEntryCountAssertion;

export const DM_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "请求参数不合法" },
    { status: 401, note: "Token 无效或缺失" },
    { status: 404, note: "房间不是私聊或找不到对端用户" },
] as const;

export type DmStatusScenario = (typeof DM_ROUTES_STATUS_SCENARIOS)[number];

export const DM_ROUTES_ERROR_SCENARIOS = [
    { scenario: "未认证或 token 失效", httpOrErrcode: "401 / M_UNKNOWN_TOKEN", sdkErrorType: "AuthError", handling: "引导重新登录或刷新凭据，不重试业务请求" },
    { scenario: "目标资源不存在", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "视为业务态失败，提示房间或用户不存在" },
    { scenario: "参数不合法", httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "修正请求参数后重试" },
    { scenario: "限流或短暂服务异常", httpOrErrcode: "429 / M_LIMIT_EXCEEDED，5xx", sdkErrorType: "RetryableError", handling: "使用退避重试，保留幂等保护" },
    { scenario: "其他 API 错误", httpOrErrcode: "其他 4xx/5xx", sdkErrorType: "ApiError", handling: "按 code 与 statusCode 做兜底分支" },
] as const;

export type DmErrorScenario = (typeof DM_ROUTES_ERROR_SCENARIOS)[number];

export const DM_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "access token 无效、过期或缺失" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "私聊房间、对端用户或映射记录不存在" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "请求体结构不符合接口要求" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "参数类型或取值非法" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "触发限流，需延迟重试" },
] as const;

export type DmErrcode = (typeof DM_ROUTES_ERRCODES)[number];
