// Auto-generated by contract:codegen. Do not edit manually.

/** Options for creating a DM room. */
export interface CreateDmOptionsDto {
    userIds: string[];
    invite?: boolean;
    name?: string;
    topic?: string;
    isEncrypted?: boolean;
}

/** DM room information. */
export interface DmRoomInfoDto {
    roomId: string;
    inviter?: string;
    invitees: string[];
    name?: string;
    avatarUrl?: string;
    lastMessage?: DmLastMessage;
    unreadCount?: number;
}

/** Last message in a DM room. */
export interface DmLastMessage {
    content: string;
    timestamp: number;
    sender: string;
}

/** m.direct account data mapping: userId → room IDs. */
export interface DirectRoomsMapDto {
    [userId: string]: string[];
}

/** POST /_matrix/client/v3/create_dm response. */
export interface CreateDmRoomResponseDto {
    room_id: string;
}

/** POST /_matrix/client/v3/create_dm request options. */
export interface CreateDmRoomOptionsDto {
    name?: string;
    topic?: string;
    invite?: string[];
    visibility?: "private" | "public";
}

/** GET /_matrix/client/v3/direct response. */
export interface DirectRoomsResponseDto {
    rooms: DirectRoomsMapDto;
}

/** GET /_matrix/client/v3/rooms/{roomId}/dm response. */
export interface DmRoomCheckResponseDto {
    room_id: string;
    "m.direct": boolean;
}

/** GET /_matrix/client/v3/rooms/{roomId}/dm/partner response. */
export interface DmPartnerResponseDto {
    room_id: string;
    user_id: string;
    display_name: string;
    avatar_url: string;
}

/** PUT /_matrix/client/v3/direct/{roomId} response. */
export interface UpdateDirectRoomResponseDto {
    room_id: string;
    users: string[];
    direct_map: DirectRoomsMapDto;
    updated_ts: number;
}

/** PUT /_matrix/client/v3/direct/{roomId} request options. */
export interface UpdateDirectRoomOptionsDto {
    userIds?: string[];
    content?: Record<string, unknown>;
}
