/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        DM 模块契约
 * Source:        docs/api-contract/generated/modules/dm.json
 * Ledger schema: 1
 * Source profile: all
 */

/** Routes served by the synapse-rust `dm` module. */
export const DM_ROUTES = [
    { method: "POST", path: "/_matrix/client/r0/create_dm" },
    { method: "GET", path: "/_matrix/client/r0/direct" },
    { method: "PUT", path: "/_matrix/client/r0/direct/{room_id}" },
    { method: "POST", path: "/_matrix/client/v3/create_dm" },
    { method: "GET", path: "/_matrix/client/v3/direct" },
    { method: "PUT", path: "/_matrix/client/v3/direct/{room_id}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/dm" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/dm/partner" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `DM_ROUTES`. */
export type DmRoute = (typeof DM_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type DmMethod = DmRoute["method"];

/** Path templates referenced by this module. */
export type DmPath = DmRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
type DmReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${DmReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type DmPathPattern = DmReplaceBraces<DmPath>;
