/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Telemetry
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       6 (authoritative set mirrored from the backend contract)
 */

/** Routes served by the synapse-rust `telemetry` module (mirrored from the backend contract). */
export const TELEMETRY_ROUTES = [
    { method: "GET", path: "/_synapse/admin/v1/telemetry/alerts" },
    { method: "POST", path: "/_synapse/admin/v1/telemetry/alerts/{alert_id}/ack" },
    { method: "GET", path: "/_synapse/admin/v1/telemetry/attributes" },
    { method: "GET", path: "/_synapse/admin/v1/telemetry/health" },
    { method: "GET", path: "/_synapse/admin/v1/telemetry/metrics" },
    { method: "GET", path: "/_synapse/admin/v1/telemetry/status" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `TELEMETRY_ROUTES`. */
export type TelemetryRoute = (typeof TELEMETRY_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type TelemetryMethod = TelemetryRoute["method"];

/** Path templates referenced by this module. */
export type TelemetryPath = TelemetryRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type TelemetryReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${TelemetryReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type TelemetryPathPattern = TelemetryReplaceBraces<TelemetryPath>;
