/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/typing.json
 */

import { TYPING_ROUTES } from "./route-table";

export const TYPING_ROUTES_ENTRY_COUNT = 5 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _TypingEntryCountAssertion: 5 = TYPING_ROUTES.length;
void _TypingEntryCountAssertion;

export const TYPING_ROUTES_STATUS_SCENARIOS = [
    { status: 400, note: "M_INVALID_PARAM | 参数无效" },
    { status: 401, note: "M_UNAUTHORIZED | 未认证" },
    { status: 403, note: "M_FORBIDDEN | 非房间成员或尝试更新他人状态" },
    { status: 404, note: "M_NOT_FOUND | 房间不存在" },
    { status: 202, note: "初版 | -" },
    { status: 202, note: "补充 TypingManager 人工封装对齐说明与测试口径 | 文档与实际实现同步" },
] as const;

export type TypingStatusScenario = (typeof TYPING_ROUTES_STATUS_SCENARIOS)[number];

export const TYPING_ROUTES_ERROR_SCENARIOS = [
    { scenario: "参数无效", httpOrErrcode: "400 / M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "参数无效" },
    { scenario: "未认证", httpOrErrcode: "401 / M_UNAUTHORIZED", sdkErrorType: "AuthError", handling: "未认证" },
    { scenario: "非房间成员或尝试更新他人状态", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "非房间成员或尝试更新他人状态" },
    { scenario: "房间不存在", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "房间不存在" },
] as const;

export type TypingErrorScenario = (typeof TYPING_ROUTES_ERROR_SCENARIOS)[number];

export const TYPING_ROUTES_ERRCODES = [
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "参数无效" },
    { errcode: "M_UNAUTHORIZED", httpStatus: "401", note: "未认证" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "非房间成员或尝试更新他人状态" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "房间不存在" },
] as const;

export type TypingErrcode = (typeof TYPING_ROUTES_ERRCODES)[number];
