/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/search.md
 */

/**
 * DTO snippets extracted from the contract doc for `search`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface SearchResultEvent {
    event_id: string;
    type: string;
    content: Record<string, unknown>;
    sender: string;
    origin_server_ts: number;
    room_id: string;
    state_key?: string;
}

export interface SearchRoomEventsResponse {
    search_categories: {
        room_events?: {
            count: number;
            results: Array<{
                rank?: number;
                result: SearchResultEvent;
                context?: {
                    events_before: SearchResultEvent[];
                    events_after: SearchResultEvent[];
                    profile_info?: Record<string, { displayname?: string; avatar_url?: string }>;
                };
            }>;
            next_batch?: string;
            highlights?: string[];
        };
        users?: {
            results: Array<{
                user_id: string;
                display_name?: string;
                avatar_url?: string;
            }>;
            limited?: boolean;
        };
    };
}

export interface SearchRecipientsOrRoomsResult {
    user_id?: string;
    room_id?: string;
    display_name?: string;
    avatar_url?: string;
}

export interface SearchRecipientsOrRoomsResponse {
    results: SearchRecipientsOrRoomsResult[];
    count: number;
    next_batch: string | null;
}
