/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        搜索契约
 * Source:        docs/api-contract/generated/modules/search.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  b3c5153fc5fa969a2caa04d8e506b18655b349a6
 */

/** Routes served by the synapse-rust `search` module. */
export const SEARCH_ROUTES = [
    { method: "POST", path: "/_matrix/client/r0/search" },
    { method: "POST", path: "/_matrix/client/r0/search_recipients" },
    { method: "POST", path: "/_matrix/client/r0/search_rooms" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/context/{event_id}" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/hierarchy" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/timestamp_to_event" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/context/{event_id}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/hierarchy" },
    { method: "POST", path: "/_matrix/client/v3/search" },
    { method: "POST", path: "/_matrix/client/v3/search_recipients" },
    { method: "POST", path: "/_matrix/client/v3/search_rooms" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `SEARCH_ROUTES`. */
export type SearchRoute = (typeof SEARCH_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type SearchMethod = SearchRoute["method"];

/** Path templates referenced by this module. */
export type SearchPath = SearchRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type SearchReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${SearchReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type SearchPathPattern = SearchReplaceBraces<SearchPath>;
