// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/sliding-sync.md

// ─── Sliding Sync Request ────────────────────────────────────

/** Room subscription controls which events are returned */
export interface SlidingSyncRoomSubscription {
    /** Required state events to return, e.g. [["m.room.name", ""]] */
    required_state?: string[][];
    /** Maximum number of timeline events per room */
    timeline_limit?: number;
    /** Include old rooms in the subscription */
    include_old_rooms?: SlidingSyncRoomSubscription;
}

/** Filter for a sliding sync list */
export interface SlidingSyncFilter {
    /** Filter for DM rooms */
    is_dm?: boolean;
    /** Filter for encrypted rooms */
    is_encrypted?: boolean;
    /** Filter for invited rooms */
    is_invite?: boolean;
    /** Filter by room name substring */
    room_name_like?: string;
    /** Include only these room types */
    room_types?: string[];
    /** Exclude these room types */
    not_room_types?: string[];
    /** Include rooms in these spaces */
    spaces?: string[];
    /** Include rooms with these tags */
    tags?: string[];
    /** Exclude rooms with these tags */
    not_tags?: string[];
}

/** A single list in a sliding sync request */
export interface SlidingSyncList {
    /** Ranges of indices to return, e.g. [[0, 10], [20, 30]] */
    ranges: number[][];
    /** Sort order, e.g. ["by_recency", "by_name"] */
    sort?: string[];
    /** Filters to apply */
    filters?: SlidingSyncFilter;
    /** Required state events to return */
    required_state?: string[][];
    /** Maximum number of timeline events */
    timeline_limit?: number;
    /** Whether to slowly get all rooms */
    slow_get_all_rooms?: boolean;
}

/** Complete sliding sync request body */
export interface SlidingSyncRequest {
    /** List subscriptions keyed by list ID */
    lists?: Record<string, SlidingSyncList>;
    /** Room IDs to unsubscribe from */
    unsubscribe_rooms?: string[];
    /** Room subscriptions keyed by room ID */
    room_subscriptions?: Record<string, SlidingSyncRoomSubscription>;
    /** Extension data (e.g. to-device, e2ee, account_data) */
    extensions?: Record<string, object>;
    /** Transaction ID for idempotency */
    txn_id?: string;
}

// ─── Sliding Sync Response ───────────────────────────────────

/** Hero user in sliding sync response (MSC4186 format) */
export interface SlidingSyncHero {
    /** User ID */
    user_id: string;
    /** Display name */
    displayname?: string;
    /** Avatar URL */
    avatar_url?: string;
}

/** Room data in a sliding sync response */
export interface SlidingSyncRoom {
    /** Room name override */
    name?: string;
    /** Required state events */
    required_state?: Array<{
        type: string;
        state_key: string;
        content: Record<string, unknown>;
        sender?: string;
        event_id?: string;
        origin_server_ts?: number;
    }>;
    /** Timeline events */
    timeline?: Array<{
        type: string;
        content: Record<string, unknown>;
        sender?: string;
        event_id?: string;
        origin_server_ts?: number;
    }>;
    /** Hero users */
    heroes?: SlidingSyncHero[];
    /** Notification count */
    notification_count?: number;
    /** Highlight count */
    highlight_count?: number;
    /** Joined member count */
    joined_count?: number;
    /** Invited member count */
    invited_count?: number;
    /** Invite state events */
    invite_state?: Array<{
        type: string;
        state_key: string;
        content: Record<string, unknown>;
        sender?: string;
    }>;
    /** Whether this is the initial data for the room */
    initial?: boolean;
    /** Whether the timeline is limited */
    limited?: boolean;
    /** Whether the room is a DM */
    is_dm?: boolean;
    /** Previous batch token for back-pagination */
    prev_batch?: string | null;
    /** Number of live timeline events */
    num_live?: number;
    /** Bump stamp for sorting */
    bump_stamp?: number;
}

/** Complete sliding sync response */
export interface SlidingSyncResponse {
    /** Position token for the next request */
    pos: string;
    /** Transaction ID echoed from the request */
    txn_id?: string;
    /** List responses keyed by list ID */
    lists: Record<string, {
        /** Total count of rooms matching the list filter */
        count: number;
    }>;
    /** Room data keyed by room ID */
    rooms: Record<string, SlidingSyncRoom>;
    /** Extension response data */
    extensions: Record<string, object>;
}

// ─── Sliding Sync Extension ──────────────────────────────────

/** Extension state: when to invoke the extension response handler */
export type SlidingSyncExtensionState = "preprocess" | "postprocess";

/** Generic extension interface for sliding sync */
export interface SlidingSyncExtension<Req extends object, Res extends object> {
    /** Extension name (key under "extensions" in request body) */
    name(): string;
    /** Build the request payload for this extension */
    onRequest(isInitial: boolean): Promise<Req>;
    /** Handle the response payload for this extension */
    onResponse(data: Res): Promise<void>;
    /** When to invoke the response handler */
    when(): SlidingSyncExtensionState;
}
