/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Sliding Sync 契约
 * Source:        docs/api-contract/generated/modules/sliding_sync.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  c2e43304843f9460bc5d88d93b708016306d97f1
 */

/** Routes served by the synapse-rust `sliding_sync` module. */
export const SLIDING_SYNC_ROUTES = [
    { method: "POST", path: "/_matrix/client/unstable/org.matrix.msc3575/sync" },
    { method: "POST", path: "/_matrix/client/unstable/org.matrix.simplified_msc3575/sync" },
    { method: "POST", path: "/_matrix/client/v1/sync" },
    { method: "POST", path: "/_matrix/client/v4/sync" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `SLIDING_SYNC_ROUTES`. */
export type SlidingSyncRoute = (typeof SLIDING_SYNC_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type SlidingSyncMethod = SlidingSyncRoute["method"];

/** Path templates referenced by this module. */
export type SlidingSyncPath = SlidingSyncRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type SlidingSyncReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${SlidingSyncReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type SlidingSyncPathPattern = SlidingSyncReplaceBraces<SlidingSyncPath>;
