/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/app_service.json
 */

import { APP_SERVICE_ROUTES } from "./route-table";

export const APP_SERVICE_ROUTES_ENTRY_COUNT = 25 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _AppServiceEntryCountAssertion: 25 = APP_SERVICE_ROUTES.length;
void _AppServiceEntryCountAssertion;

export const APP_SERVICE_ROUTES_STATUS_SCENARIOS = [
    { status: 202, note: "初版 | -" },
] as const;

export type AppServiceStatusScenario = (typeof APP_SERVICE_ROUTES_STATUS_SCENARIOS)[number];

export const APP_SERVICE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type AppServiceErrorScenario = (typeof APP_SERVICE_ROUTES_ERROR_SCENARIOS)[number];

export const APP_SERVICE_ROUTES_ERRCODES = [
] as const;

export type AppServiceErrcode = (typeof APP_SERVICE_ROUTES_ERRCODES)[number];
