/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Application Service
 * Source:        docs/api-contract/generated/modules/app_service.json
 * Ledger schema: 1
 * Source profile: all
 */

/** Routes served by the synapse-rust `app_service` module. */
export const APP_SERVICE_ROUTES = [
    { method: "POST", path: "/_matrix/app/v1/ping" },
    { method: "GET", path: "/_matrix/app/v1/rooms/{alias}" },
    { method: "PUT", path: "/_matrix/app/v1/transactions/{as_id}/{txn_id}" },
    { method: "GET", path: "/_matrix/app/v1/users/{user_id}" },
    { method: "GET", path: "/_matrix/app/v1/{as_id}" },
    { method: "GET", path: "/_matrix/client/v1/user/{user_id}/appservice" },
    { method: "GET", path: "/_matrix/client/v3/appservice/alias" },
    { method: "GET", path: "/_matrix/client/v3/appservice/user" },
    { method: "GET", path: "/_synapse/admin/v1/appservices" },
    { method: "POST", path: "/_synapse/admin/v1/appservices" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/query/alias" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/query/user" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/statistics" },
    { method: "DELETE", path: "/_synapse/admin/v1/appservices/{as_id}" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/{as_id}" },
    { method: "PUT", path: "/_synapse/admin/v1/appservices/{as_id}" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/{as_id}/events" },
    { method: "POST", path: "/_synapse/admin/v1/appservices/{as_id}/events" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/{as_id}/namespaces" },
    { method: "POST", path: "/_synapse/admin/v1/appservices/{as_id}/ping" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/{as_id}/state" },
    { method: "POST", path: "/_synapse/admin/v1/appservices/{as_id}/state" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/{as_id}/state/{state_key}" },
    { method: "GET", path: "/_synapse/admin/v1/appservices/{as_id}/users" },
    { method: "POST", path: "/_synapse/admin/v1/appservices/{as_id}/users" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `APP_SERVICE_ROUTES`. */
export type AppServiceRoute = (typeof APP_SERVICE_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type AppServiceMethod = AppServiceRoute["method"];

/** Path templates referenced by this module. */
export type AppServicePath = AppServiceRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type AppServiceReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${AppServiceReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type AppServicePathPattern = AppServiceReplaceBraces<AppServicePath>;
