/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/push_notification.json
 */

import { NOTIFICATIONS_ROUTES } from "./route-table";

export const NOTIFICATIONS_ROUTES_ENTRY_COUNT = 9 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _NotificationsEntryCountAssertion: 9 = NOTIFICATIONS_ROUTES.length;
void _NotificationsEntryCountAssertion;

export const NOTIFICATIONS_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "请求成功" },
    { status: 400, note: "分页参数或过滤条件不合法" },
    { status: 401, note: "Token 无效或缺失" },
    { status: 403, note: "无权查看通知流" },
    { status: 404, note: "分页锚点或关联事件不存在" },
    { status: 429, note: "触发限流" },
] as const;

export type NotificationsStatusScenario = (typeof NOTIFICATIONS_ROUTES_STATUS_SCENARIOS)[number];

export const NOTIFICATIONS_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "未认证或 token 失效",
        httpOrErrcode: "401 / M_UNKNOWN_TOKEN",
        sdkErrorType: "AuthError",
        handling: "引导重新登录",
    },
    {
        scenario: "查询参数不合法",
        httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM",
        sdkErrorType: "ApiError",
        handling: "修正 from、limit、only 后重试",
    },
    {
        scenario: "权限不足",
        httpOrErrcode: "403 / M_FORBIDDEN",
        sdkErrorType: "ApiError",
        handling: "提示用户当前账号无权访问通知历史",
    },
    {
        scenario: "分页锚点或关联数据不存在",
        httpOrErrcode: "404 / M_NOT_FOUND",
        sdkErrorType: "NotFoundError",
        handling: "清空本地分页游标并重新拉取第一页",
    },
    {
        scenario: "限流或短暂服务异常",
        httpOrErrcode: "429 / M_LIMIT_EXCEEDED",
        sdkErrorType: "RetryableError",
        handling: "使用退避重试",
    },
    {
        scenario: "其他 API 错误",
        httpOrErrcode: "其他 4xx/5xx",
        sdkErrorType: "ApiError",
        handling: "按 code 与 statusCode 做兜底处理",
    },
] as const;

export type NotificationsErrorScenario = (typeof NOTIFICATIONS_ROUTES_ERROR_SCENARIOS)[number];

export const NOTIFICATIONS_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "access token 无效、过期或缺失" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "通知查询参数结构不符合接口要求" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "limit、from 或 only 参数非法" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "无权读取通知历史" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "分页游标或关联通知事件不存在" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "通知查询触发限流" },
] as const;

export type NotificationsErrcode = (typeof NOTIFICATIONS_ROUTES_ERRCODES)[number];
