/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/push_notification.json
 */

import { NOTIFICATIONS_ROUTES } from "./route-table";

export const NOTIFICATIONS_ROUTES_ENTRY_COUNT = 9 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _NotificationsEntryCountAssertion: 9 = NOTIFICATIONS_ROUTES.length;
void _NotificationsEntryCountAssertion;

export const NOTIFICATIONS_ROUTES_STATUS_SCENARIOS = [
] as const;

export type NotificationsStatusScenario = (typeof NOTIFICATIONS_ROUTES_STATUS_SCENARIOS)[number];

export const NOTIFICATIONS_ROUTES_ERROR_SCENARIOS = [
] as const;

export type NotificationsErrorScenario = (typeof NOTIFICATIONS_ROUTES_ERROR_SCENARIOS)[number];

export const NOTIFICATIONS_ROUTES_ERRCODES = [
] as const;

export type NotificationsErrcode = (typeof NOTIFICATIONS_ROUTES_ERRCODES)[number];
