/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/notifications.md
 */

/**
 * DTO snippets extracted from the contract doc for `push_notification`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface NotificationEvent {
    event_id: string;
    type: string;
    content: Record<string, unknown>;
    sender: string;
    origin_server_ts: number;
    room_id?: string;
    state_key?: string;
}

export interface NotificationAction {
    /** Action type: "notify", "dont_notify", "coalesce", or a tweak object */
    set_tweak?: string;
    value?: unknown;
    [key: string]: unknown;
}

export interface INotificationsResponse {
    next_token?: string;
    notifications: Array<{
        actions: NotificationAction[];
        event: NotificationEvent;
        profile_tag?: string;
        read: boolean;
        room_id: string;
        ts: number;
    }>;
}
