/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        通知契约
 * Source:        docs/api-contract/generated/modules/push_notification.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  f282009ea36a63cacdd12770d441b2a2a655d082
 */

/** Routes served by the synapse-rust `push_notification` module. */
export const NOTIFICATIONS_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/push/devices" },
    { method: "POST", path: "/_matrix/client/r0/push/devices" },
    { method: "DELETE", path: "/_matrix/client/r0/push/devices/{device_id}" },
    { method: "GET", path: "/_matrix/client/r0/push/rules" },
    { method: "POST", path: "/_matrix/client/r0/push/rules" },
    { method: "DELETE", path: "/_matrix/client/r0/push/rules/{scope}/{kind}/{rule_id}" },
    { method: "POST", path: "/_matrix/client/r0/push/send" },
    { method: "POST", path: "/_synapse/admin/v1/push/cleanup" },
    { method: "POST", path: "/_synapse/admin/v1/push/process" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `NOTIFICATIONS_ROUTES`. */
export type NotificationsRoute = (typeof NOTIFICATIONS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type NotificationsMethod = NotificationsRoute["method"];

/** Path templates referenced by this module. */
export type NotificationsPath = NotificationsRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type NotificationsReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${NotificationsReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type NotificationsPathPattern = NotificationsReplaceBraces<NotificationsPath>;
