/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { BURN_AFTER_READ_ROUTES } from "./route-table";

export const BURN_AFTER_READ_ROUTES_ENTRY_COUNT = 14 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _BurnAfterReadEntryCountAssertion: 14 = BURN_AFTER_READ_ROUTES.length;
void _BurnAfterReadEntryCountAssertion;

export const BURN_AFTER_READ_ROUTES_STATUS_SCENARIOS = [
    { status: 202, note: "按后端真实 7 条路由重写字段、返回体与覆盖率口径，并补充 SDK 路径绑定说明 | 修复长期文档漂移" },
    { status: 202, note: "初版 | -" },
] as const;

export type BurnAfterReadStatusScenario = (typeof BURN_AFTER_READ_ROUTES_STATUS_SCENARIOS)[number];

export const BURN_AFTER_READ_ROUTES_ERROR_SCENARIOS = [
] as const;

export type BurnAfterReadErrorScenario = (typeof BURN_AFTER_READ_ROUTES_ERROR_SCENARIOS)[number];

export const BURN_AFTER_READ_ROUTES_ERRCODES = [
] as const;

export type BurnAfterReadErrcode = (typeof BURN_AFTER_READ_ROUTES_ERRCODES)[number];
