/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Burn After Read
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       14 (authoritative set mirrored from the backend contract)
 */

/** Routes served by the synapse-rust `burn-after-read` module (mirrored from the backend contract). */
export const BURN_AFTER_READ_ROUTES = [
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/burn" },
    { method: "PUT", path: "/_matrix/client/v1/rooms/{room_id}/burn" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/burn/pending" },
    { method: "DELETE", path: "/_matrix/client/v1/rooms/{room_id}/burn/{event_id}" },
    { method: "POST", path: "/_matrix/client/v1/rooms/{room_id}/burn/{event_id}" },
    { method: "PUT", path: "/_matrix/client/v1/user/burn/config" },
    { method: "GET", path: "/_matrix/client/v1/user/burn/stats" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/burn" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/burn" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/burn/pending" },
    { method: "DELETE", path: "/_matrix/client/v3/rooms/{room_id}/burn/{event_id}" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/burn/{event_id}" },
    { method: "PUT", path: "/_matrix/client/v3/user/burn/config" },
    { method: "GET", path: "/_matrix/client/v3/user/burn/stats" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `BURN_AFTER_READ_ROUTES`. */
export type BurnAfterReadRoute = (typeof BURN_AFTER_READ_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type BurnAfterReadMethod = BurnAfterReadRoute["method"];

/** Path templates referenced by this module. */
export type BurnAfterReadPath = BurnAfterReadRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type BurnAfterReadReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${BurnAfterReadReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type BurnAfterReadPathPattern = BurnAfterReadReplaceBraces<BurnAfterReadPath>;
