// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/room-summary.md

// ─── Room Summary Info ───────────────────────────────────────

/** Hero user displayed in room summary */
export interface RoomSummaryHero {
    /** User ID */
    user_id: string;
    /** Display name */
    display_name?: string;
    /** Avatar URL (mxc://) */
    avatar_url?: string;
}

/** Full room summary */
export interface RoomSummaryInfo {
    /** Room ID */
    room_id: string;
    /** Room type (e.g. "m.space") */
    room_type?: string;
    /** Room name */
    name?: string;
    /** Room topic */
    topic?: string;
    /** Avatar URL (mxc://) */
    avatar_url?: string;
    /** Canonical alias */
    canonical_alias?: string;
    /** Join rule */
    join_rule: string;
    /** History visibility */
    history_visibility: string;
    /** Guest access setting */
    guest_access: string;
    /** Whether the room is a DM */
    is_direct: boolean;
    /** Whether the room is a space */
    is_space: boolean;
    /** Whether the room is encrypted */
    is_encrypted: boolean;
    /** Total member count */
    member_count: number;
    /** Joined member count */
    joined_member_count: number;
    /** Invited member count */
    invited_member_count: number;
    /** Hero users for the room */
    heroes: RoomSummaryHero[];
    /** Timestamp of the last event (ms) */
    last_event_ts?: number;
    /** Timestamp of the last message (ms) */
    last_message_ts?: number;
}

// ─── Room Summary Member ─────────────────────────────────────

/** Room member in summary */
export interface RoomSummaryMember {
    /** User ID */
    user_id: string;
    /** Display name */
    display_name?: string;
    /** Avatar URL (mxc://) */
    avatar_url?: string;
    /** Membership state */
    membership: string;
    /** Whether this user is a hero */
    is_hero: boolean;
}

// ─── Room Summary Update ─────────────────────────────────────

/** Options for querying room summaries */
export interface RoomSummaryOptions {
    /** Maximum number of results */
    limit?: number;
    /** Filter by max joined members */
    maxJoinedMembers?: number;
    /** Only suggested rooms */
    suggested?: boolean;
    /** Include all fields in response */
    includeAllFields?: boolean;
}

/** Room statistics */
export interface RoomStats {
    /** Room ID */
    room_id: string;
    /** Total number of events */
    total_events: number;
    /** Total number of state events */
    total_state_events: number;
    /** Total number of messages */
    total_messages: number;
    /** Total number of media items */
    total_media: number;
    /** Storage size in bytes */
    storage_size: number;
}

/** Room summary list response */
export interface RoomSummaryListResponse {
    /** Summaries (alias: summaries) */
    summaries?: RoomSummaryInfo[];
    /** Summaries (alias: rooms) */
    rooms?: RoomSummaryInfo[];
    /** Summaries (alias: chunk) */
    chunk?: RoomSummaryInfo[];
    /** Token for the next page */
    next_batch?: string;
}

/** Room summary state entry */
export interface RoomSummaryState {
    /** Event type */
    event_type: string;
    /** State key */
    state_key: string;
    /** Event ID */
    event_id: string;
    /** Event content */
    content: Record<string, unknown>;
}

/** Room metadata */
export interface RoomMetadata {
    /** Room ID */
    room_id: string;
    /** Room name */
    name?: string;
    /** Room topic */
    topic?: string;
    /** Avatar URL */
    avatar_url?: string;
    /** Canonical alias */
    canonical_alias?: string;
    /** Room version */
    room_version?: string;
    /** Whether the room is a DM */
    is_direct?: boolean;
    /** Whether the room is a space */
    is_space?: boolean;
    /** Whether the room is encrypted */
    is_encrypted?: boolean;
    /** Encryption algorithm */
    encryption?: string;
    /** Whether the room is public */
    is_public?: boolean;
    /** Join rule */
    join_rule?: string;
    /** Guest access */
    guest_access?: string;
    /** History visibility */
    history_visibility?: string;
    /** Member count */
    member_count?: number;
    /** Creation timestamp (ms) */
    created_at?: number;
    /** Creator user ID */
    creator?: string;
}

/** Unread count result */
export interface UnreadCountResult {
    /** Notification count */
    notification_count: number;
    /** Highlight count */
    highlight_count: number;
    /** Room ID */
    room_id?: string;
    /** Unread notifications count */
    unread_notifications?: number;
    /** Unread highlight count */
    unread_highlight_count?: number;
    /** Unread thread messages count */
    unread_thread_messages?: number;
}
