/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Room Summary 模块契约
 * Source:        docs/api-contract/generated/modules/room_summary.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  ef9bd5d4d22c35afba65b2b5452278f6a0a28115
 */

/** Routes served by the synapse-rust `room_summary` module. */
export const ROOM_SUMMARY_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/rooms/{room_id}/summary" },
    { method: "GET", path: "/_matrix/client/r0/rooms/{room_id}/summary/members" },
    { method: "GET", path: "/_matrix/client/r0/rooms/{room_id}/summary/state" },
    { method: "GET", path: "/_matrix/client/r0/rooms/{room_id}/summary/stats" },
    { method: "DELETE", path: "/_matrix/client/v3/rooms/{room_id}/summary" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/summary" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/summary" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/summary" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/summary/heroes/recalculate" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/summary/members" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/summary/members" },
    { method: "DELETE", path: "/_matrix/client/v3/rooms/{room_id}/summary/members/{user_id}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/summary/members/{user_id}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/summary/state" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/summary/state/{event_type}/{state_key}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/summary/state/{event_type}/{state_key}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/summary/stats" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/summary/stats/recalculate" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/summary/sync" },
    { method: "POST", path: "/_matrix/client/v3/rooms/{room_id}/summary/unread/clear" },
    { method: "GET", path: "/_synapse/room_summary/v1/summaries" },
    { method: "POST", path: "/_synapse/room_summary/v1/summaries" },
    { method: "POST", path: "/_synapse/room_summary/v1/updates/process" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `ROOM_SUMMARY_ROUTES`. */
export type RoomSummaryRoute = (typeof ROOM_SUMMARY_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type RoomSummaryMethod = RoomSummaryRoute["method"];

/** Path templates referenced by this module. */
export type RoomSummaryPath = RoomSummaryRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type RoomSummaryReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${RoomSummaryReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type RoomSummaryPathPattern = RoomSummaryReplaceBraces<RoomSummaryPath>;
