/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/admin.json
 */

import { ADMIN_ROUTES } from "./route-table";

export const ADMIN_ROUTES_ENTRY_COUNT = 142 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _AdminEntryCountAssertion: 142 = ADMIN_ROUTES.length;
void _AdminEntryCountAssertion;

export const ADMIN_ROUTES_STATUS_SCENARIOS = [
] as const;

export type AdminStatusScenario = (typeof ADMIN_ROUTES_STATUS_SCENARIOS)[number];

export const ADMIN_ROUTES_ERROR_SCENARIOS = [
] as const;

export type AdminErrorScenario = (typeof ADMIN_ROUTES_ERROR_SCENARIOS)[number];

export const ADMIN_ROUTES_ERRCODES = [
] as const;

export type AdminErrcode = (typeof ADMIN_ROUTES_ERRCODES)[number];
