/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/admin.md
 *
 * All types have been consolidated into ../types.ts.
 * This file re-exports them for backward compatibility.
 */

export type {
    AdminRoomVersionResponse,
    AdminRoomBlockStatus,
    AdminEventContextEvent,
    AdminEventContext,
    AdminForwardExtremity,
    AdminTokenSync,
    AdminRoomSearchResult,
    AdminRoomListing,
    AdminRoomListings,
    AdminFederationCacheEntry,
    AdminFederationCache,
    AdminFederationDestinationRoom,
    AdminFederationDestinationRooms,
    AdminAccountDetails,
    AdminRegisterResult,
    AdminReport,
    AdminReportPage,
    AdminModuleInfo,
    AdminModulePage,
    AdminModuleLog,
    AdminModuleLogPage,
    AdminAccountValidityInfo,
    AdminPasswordAuthProvider,
    AdminPasswordAuthProviderPage,
    AdminPresenceRoute,
    AdminPresenceRoutePage,
    AdminMediaCallback,
    AdminMediaCallbackPage,
    AdminRateLimitCallback,
    AdminRateLimitCallbackPage,
    AdminAccountDataCallback,
    AdminAccountDataCallbackPage,
    AdminInviteList,
    AdminJitsiConfig,
    AdminPurgeHistoryResult,
    AdminShutdownRoomResult,
    AdminBackupInfo,
    AdminBackupPage,
    AdminExperimentalFeatures,
} from "../types";
