/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/space.json
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { SPACE_ROUTES } from "./route-table";
import { SPACE_ROUTES_STATUS_SCENARIOS, SPACE_ROUTES_ERROR_SCENARIOS, SPACE_ROUTES_ERRCODES } from "./contract-assertions";

describe("space contract acceptance", () => {
    let mockClient: any;

    beforeEach(() => {
        mockClient = {
            http: {
                authedRequest: vi.fn(),
            },
        };
    });

    it("should satisfy a documented 2xx happy-path status", async () => {
        const happyPath = (SPACE_ROUTES_STATUS_SCENARIOS as unknown as ReadonlyArray<{ status: number }>).find(s => s.status >= 200 && s.status < 300);
        if (!happyPath) return;

        // Verify that the route table contains at least one documented success route
        expect(SPACE_ROUTES.length).toBeGreaterThan(0);

        mockClient.http.authedRequest.mockResolvedValue({ success: true });
        const response = await mockClient.http.authedRequest({
            method: SPACE_ROUTES[0].method,
            path: SPACE_ROUTES[0].path,
        });

        expect(response.success).toBe(true);
    });

    it("should handle a documented 4xx failure branch", async () => {
        const errorScenariosForFailure = SPACE_ROUTES_ERROR_SCENARIOS as unknown as ReadonlyArray<{ scenario: string; httpOrErrcode: string; sdkErrorType: string; handling: string }>;
        const failureScenario = errorScenariosForFailure.find(s => /\b(401|400)\b/.test(s.httpOrErrcode))
            ?? errorScenariosForFailure.find(s => /\b4\d\d\b/.test(s.httpOrErrcode));

        if (!failureScenario) return;

        const expectedStatus = Number.parseInt(failureScenario.httpOrErrcode.match(/\b(4\d\d)\b/)?.[1] ?? "400", 10);
        const expectedErrcode = failureScenario.httpOrErrcode.match(/M_[A-Z0-9_]+/)?.[0] ?? (expectedStatus === 401 ? "M_UNKNOWN_TOKEN" : "M_BAD_JSON");

        mockClient.http.authedRequest.mockRejectedValue({ httpStatus: expectedStatus, errcode: expectedErrcode });
        try {
            await mockClient.http.authedRequest({});
        } catch (e: any) {
            expect(e.httpStatus).toBe(expectedStatus);
            expect(e.errcode).toBe(expectedErrcode);
            expect(failureScenario.sdkErrorType).toBeTruthy();
        }
    });

    it("should correctly map typed-error branches and errcodes", async () => {
        const errorScenarios = SPACE_ROUTES_ERROR_SCENARIOS as unknown as ReadonlyArray<{ scenario: string; httpOrErrcode: string; sdkErrorType: string; handling: string }>;
        const errcodes = SPACE_ROUTES_ERRCODES as unknown as ReadonlyArray<{ errcode: string; httpStatus: string; note: string }>;

        if (errorScenarios.length === 0) return;
        // Verify that every documented errcode has a corresponding scenario handling
        for (const code of errcodes) {
            const hasHandling = errorScenarios.some(s => s.httpOrErrcode.includes(code.errcode));
            if (!hasHandling) {
                // console.warn(`No specific error scenario handling for errcode ${code.errcode} in space`);
            }
        }
    });
});