/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { SPACE_ROUTES } from "./route-table";

export const SPACE_ROUTES_ENTRY_COUNT = 72 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _SpaceEntryCountAssertion: 72 = SPACE_ROUTES.length;
void _SpaceEntryCountAssertion;

export const SPACE_ROUTES_STATUS_SCENARIOS = [
] as const;

export type SpaceStatusScenario = (typeof SPACE_ROUTES_STATUS_SCENARIOS)[number];

export const SPACE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type SpaceErrorScenario = (typeof SPACE_ROUTES_ERROR_SCENARIOS)[number];

export const SPACE_ROUTES_ERRCODES = [
] as const;

export type SpaceErrcode = (typeof SPACE_ROUTES_ERRCODES)[number];
