// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/space.md

// ─── Space Info ──────────────────────────────────────────────

/** Space information */
export interface SpaceInfo {
    /** Space ID (same as the associated room ID) */
    space_id: string;
    /** Room ID this space is associated with */
    room_id: string;
    /** Space name */
    name?: string;
    /** Space topic / description */
    topic?: string;
    /** Avatar URL (mxc://) */
    avatar_url?: string;
    /** Creator user ID */
    creator?: string;
    /** Join rule */
    join_rule?: string;
    /** Visibility ("public" or "private") */
    visibility?: string;
    /** Whether the space is publicly visible */
    is_public?: boolean;
    /** Creation timestamp (ms) */
    created_ts?: number;
    /** Last update timestamp (ms) */
    updated_ts?: number;
    /** Parent space ID */
    parent_space_id?: string;
}

// ─── Space Child ─────────────────────────────────────────────

/** A child room in a space */
export interface SpaceChild {
    /** Space ID the child belongs to */
    space_id: string;
    /** Child room ID */
    room_id: string;
    /** Servers that can be used to join the room */
    via_servers: string[];
    /** User who added the child */
    sender?: string;
    /** Whether the child is suggested */
    is_suggested?: boolean;
    /** Timestamp when the child was added (ms) */
    added_ts?: number;
    /** Ordering string */
    order?: string;
}

// ─── Space Member ────────────────────────────────────────────

/** A member of a space */
export interface SpaceMember {
    /** Space ID */
    space_id: string;
    /** User ID */
    user_id: string;
    /** Membership state */
    membership?: string;
    /** Timestamp when the user joined (ms) */
    joined_ts?: number;
}

// ─── Space Hierarchy ─────────────────────────────────────────

/** Request parameters for space hierarchy queries */
export interface SpaceHierarchyRequest {
    /** Maximum number of results */
    limit?: number;
    /** Pagination token from a previous request */
    from?: string;
    /** Only return suggested rooms */
    suggested_only?: boolean;
    /** Maximum depth of the hierarchy tree */
    max_depth?: number;
}

/** A page of space hierarchy results */
export interface SpaceHierarchyResponse {
    /** Rooms in the hierarchy */
    rooms?: unknown[];
    /** Token for the next page */
    next_batch?: string;
}

// ─── Space Summary ───────────────────────────────────────────

/** Request parameters for space summary queries */
export interface SpaceSummaryRequest {
    /** Maximum number of results */
    limit?: number;
    /** Pagination token */
    from?: string;
    /** Only return suggested rooms */
    suggested_only?: boolean;
    /** Maximum depth */
    max_depth?: number;
    /** Remote server to query */
    server?: string;
    /** Search term */
    search_term?: string;
}

// ─── Space List ──────────────────────────────────────────────

/** Response from listing spaces */
export interface SpaceListResponse {
    /** Spaces (alias: chunk) */
    chunk?: SpaceInfo[];
    /** Spaces (alias: spaces) */
    spaces?: SpaceInfo[];
    /** Spaces (alias: rooms) */
    rooms?: SpaceInfo[];
    /** Token for the next page */
    next_batch?: string;
    /** Token for the previous page */
    prev_batch?: string;
    /** Estimated total room count */
    total_room_count_estimate?: number;
}

// ─── Space Statistics ────────────────────────────────────────

/** Space statistics */
export interface SpaceStatistics {
    /** Total number of spaces */
    total_spaces?: number;
    /** Number of public spaces */
    public_spaces?: number;
    /** Number of private spaces */
    private_spaces?: number;
    /** Number of joined spaces */
    joined_spaces?: number;
}

// ─── Space Create / Update ───────────────────────────────────

/** Request body for creating a space */
export interface CreateSpaceRequest {
    /** Room ID to associate with the space (required) */
    room_id: string;
    /** Space name */
    name?: string;
    /** Space topic */
    topic?: string;
    /** Avatar URL */
    avatar_url?: string;
    /** Join rule */
    join_rule?: string;
    /** Visibility */
    visibility?: "public" | "private";
    /** Whether the space is public */
    is_public?: boolean;
    /** Parent space ID */
    parent_space_id?: string;
}

/** Request body for updating a space */
export interface UpdateSpaceRequest {
    /** Space name */
    name?: string;
    /** Space topic */
    topic?: string;
    /** Avatar URL */
    avatar_url?: string;
    /** Join rule */
    join_rule?: string;
    /** Visibility */
    visibility?: "public" | "private";
    /** Whether the space is public */
    is_public?: boolean;
}

// ─── Add Child ───────────────────────────────────────────────

/** Request body for adding a child room to a space */
export interface AddChildRequest {
    /** Child room ID (required) */
    room_id: string;
    /** Servers that can be used to join the room */
    via_servers?: string[];
    /** Whether the child is suggested */
    suggested?: boolean;
}
