/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/moderation.json
 */

import { MODERATION_ROUTES } from "./route-table";

export const MODERATION_ROUTES_ENTRY_COUNT = 8 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _ModerationEntryCountAssertion: 8 = MODERATION_ROUTES.length;
void _ModerationEntryCountAssertion;

export const MODERATION_ROUTES_STATUS_SCENARIOS = [
    { status: 400, note: "M_INVALID_PARAM | 参数无效" },
    { status: 401, note: "M_UNAUTHORIZED | 未认证" },
    { status: 403, note: "M_FORBIDDEN | 非房间成员" },
    { status: 404, note: "M_NOT_FOUND | 事件或房间不存在" },
    { status: 429, note: "M_LIMIT_EXCEEDED | 举报频率过高" },
    { status: 202, note: "初版 | -" },
    { status: 202, note: "修正文档中遗漏的房间级举报封装状态 | 覆盖率从 75% 更新为 100%" },
] as const;

export type ModerationStatusScenario = (typeof MODERATION_ROUTES_STATUS_SCENARIOS)[number];

export const MODERATION_ROUTES_ERROR_SCENARIOS = [
    { scenario: "参数无效", httpOrErrcode: "400 / M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "参数无效" },
    { scenario: "未认证", httpOrErrcode: "401 / M_UNAUTHORIZED", sdkErrorType: "AuthError", handling: "未认证" },
    { scenario: "非房间成员", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "非房间成员" },
    { scenario: "事件或房间不存在", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "事件或房间不存在" },
    { scenario: "举报频率过高", httpOrErrcode: "429 / M_LIMIT_EXCEEDED", sdkErrorType: "RetryableError", handling: "举报频率过高" },
] as const;

export type ModerationErrorScenario = (typeof MODERATION_ROUTES_ERROR_SCENARIOS)[number];

export const MODERATION_ROUTES_ERRCODES = [
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "参数无效" },
    { errcode: "M_UNAUTHORIZED", httpStatus: "401", note: "未认证" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "非房间成员" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "事件或房间不存在" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "举报频率过高" },
] as const;

export type ModerationErrcode = (typeof MODERATION_ROUTES_ERRCODES)[number];
