/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { E2EE_ROUTES } from "./route-table";

export const E2EE_ROUTES_ENTRY_COUNT = 57 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _E2eeEntryCountAssertion: 57 = E2EE_ROUTES.length;
void _E2eeEntryCountAssertion;

export const E2EE_ROUTES_STATUS_SCENARIOS = [
] as const;

export type E2eeStatusScenario = (typeof E2EE_ROUTES_STATUS_SCENARIOS)[number];

export const E2EE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type E2eeErrorScenario = (typeof E2EE_ROUTES_ERROR_SCENARIOS)[number];

export const E2EE_ROUTES_ERRCODES = [
] as const;

export type E2eeErrcode = (typeof E2EE_ROUTES_ERRCODES)[number];
