/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/e2ee_routes.json
 */

import { E2EE_ROUTES } from "./route-table";

export const E2EE_ROUTES_ENTRY_COUNT = 51 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _E2eeEntryCountAssertion: 51 = E2EE_ROUTES.length;
void _E2eeEntryCountAssertion;

export const E2EE_ROUTES_STATUS_SCENARIOS = [
] as const;

export type E2eeStatusScenario = (typeof E2EE_ROUTES_STATUS_SCENARIOS)[number];

export const E2EE_ROUTES_ERROR_SCENARIOS = [
    { scenario: "缺少访问令牌", httpOrErrcode: "401 / M_MISSING_TOKEN", sdkErrorType: "AuthError", handling: "缺少访问令牌" },
    { scenario: "无效的访问令牌", httpOrErrcode: "401 / M_UNKNOWN_TOKEN", sdkErrorType: "AuthError", handling: "无效的访问令牌" },
    { scenario: "资源不存在", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "资源不存在" },
    { scenario: "签名无效", httpOrErrcode: "400 / M_INVALID_SIGNATURE", sdkErrorType: "ApiError", handling: "签名无效" },
] as const;

export type E2eeErrorScenario = (typeof E2EE_ROUTES_ERROR_SCENARIOS)[number];

export const E2EE_ROUTES_ERRCODES = [
    { errcode: "M_MISSING_TOKEN", httpStatus: "401", note: "缺少访问令牌" },
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "无效的访问令牌" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "资源不存在" },
    { errcode: "M_INVALID_SIGNATURE", httpStatus: "400", note: "签名无效" },
] as const;

export type E2eeErrcode = (typeof E2EE_ROUTES_ERRCODES)[number];
