// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/e2ee.md

// ─── Keys Upload ───────────────────────────────────────────────

/** Device key data uploaded via POST /keys/upload */
export interface DeviceKeyData {
    user_id?: string;
    device_id?: string;
    algorithms?: string[];
    keys?: Record<string, string>;
    signatures?: Record<string, Record<string, string>>;
}

/** Request body for POST /keys/upload */
export interface UploadKeysRequest {
    /** Device identity keys (optional on subsequent uploads) */
    device_keys?: DeviceKeyData;
    /** One-time keys to upload */
    one_time_keys?: Record<string, Record<string, string>>;
}

/** Response from POST /keys/upload */
export interface UploadKeysResponse {
    /** Counts of one-time keys currently stored on the server */
    one_time_key_counts: Record<string, number>;
}

// ─── Keys Query ────────────────────────────────────────────────

/** Request body for POST /keys/query */
export interface QueryKeysRequest {
    /** Map from user ID to list of device IDs to query. Empty list = all devices. */
    device_keys: Record<string, string[]>;
    /** Timeout in milliseconds (optional) */
    timeout?: number;
    /** Asymmetric device key token (optional) */
    token?: string;
}

/** Cross-signing key structure returned in query responses */
export interface CrossSigningKey {
    user_id?: string;
    usage?: string[];
    keys?: Record<string, string>;
    signatures?: Record<string, Record<string, string>>;
}

/** Response from POST /keys/query */
export interface QueryKeysResponse {
    /** Device keys per user per device */
    device_keys: Record<string, Record<string, DeviceKeyData>>;
    /** Map of request_id → error object for failed queries */
    failures: Record<string, { error?: string; message?: string }>;
    /** User master cross-signing keys */
    master_keys: Record<string, CrossSigningKey>;
    /** User self-signing keys */
    self_signing_keys: Record<string, CrossSigningKey>;
    /** User-signing keys (only for the requesting user) */
    user_signing_keys: Record<string, CrossSigningKey>;
}

// ─── Keys Claim ────────────────────────────────────────────────

/** Request body for POST /keys/claim */
export interface ClaimKeysRequest {
    /** Map from user ID → device ID → algorithm + key ID */
    one_time_keys: Record<string, Record<string, string>>;
    /** Timeout in milliseconds (optional) */
    timeout?: number;
}

/** Response from POST /keys/claim */
export interface ClaimKeysResponse {
    /** Claimed one-time keys: user → device → key_id → key data */
    one_time_keys: Record<string, Record<string, Record<string, Record<string, string>>>>;
    /** Map of request_id → error object for failed claims */
    failures: Record<string, { error?: string; message?: string }>;
}

// ─── Key Changes ───────────────────────────────────────────────

/** Response from GET /keys/changes */
export interface KeyChangesResponse {
    /** User IDs whose device lists have changed */
    changed: string[];
    /** User IDs who are no longer tracked */
    left: string[];
}

// ─── Send To Device ────────────────────────────────────────────

/** Messages payload for PUT /sendToDevice/{eventType}/{txnId} */
export type SendToDeviceMessages = Record<string, Record<string, import("../../models/event").IContent>>;

/** Request body for PUT /sendToDevice/{eventType}/{txnId} */
export interface SendToDeviceRequest {
    messages: SendToDeviceMessages;
}

// ─── Signatures ────────────────────────────────────────────────

/** Request body for POST /keys/signatures (and /keys/signatures/upload) */
export interface UploadSignaturesRequest {
    /** Map of user ID → device ID/key ID → signature data */
    [userId: string]: Record<string, Record<string, unknown>>;
}

/** Response from POST /keys/signatures */
export interface UploadSignaturesResponse {
    /** Map of key identifier → failure detail, empty on full success */
    failures: Record<string, Record<string, unknown>>;
}

// ─── Device Signing ────────────────────────────────────────────

/** Request body for POST /keys/device_signing/upload */
export interface UploadDeviceSigningRequest {
    /** Master cross-signing key */
    master_key?: CrossSigningKey;
    /** Self-signing key */
    self_signing_key?: CrossSigningKey;
    /** User-signing key */
    user_signing_key?: CrossSigningKey;
    /** UIA auth dict (required when replacing existing keys) */
    auth?: {
        type: string;
        session?: string;
        [key: string]: unknown;
    };
}

// ─── Room Key Request ──────────────────────────────────────────

/** Request body for POST /room_keys/request */
export interface RoomKeyRequestRequest {
    /** "request" or "cancel_request" */
    action: "request" | "cancel_request";
    /** Device ID making the request */
    requesting_device_id: string;
    /** Unique request ID */
    request_id: string;
    /** Room ID for the requested key */
    room_id?: string;
    /** Session ID for the requested key */
    session_id?: string;
    /** Encryption algorithm */
    algorithm?: string;
    /** List of devices to forward the key to */
    devices?: Array<{
        user_id: string;
        device_id: string;
    }>;
}

// ─── Device Verification (v3-only) ────────────────────────────

/** Request body for POST /device_verification/request */
export interface DeviceVerificationRequest {
    /** User ID initiating verification */
    user_id?: string;
    /** New device ID (for new device verification) */
    new_device_id?: string;
    /** Existing device ID (for existing device verification) */
    device_id?: string;
    /** Verification method (e.g. "m.sas.v1") */
    method?: string;
}

/** Response from POST /device_verification/respond */
export interface DeviceVerificationResponse {
    /** Whether the verification was successful */
    success: boolean;
    /** Trust level assigned after verification */
    trust_level: "verified" | "cross_signed" | "unverified" | "unknown";
    /** @deprecated Use success instead */
    transaction_id?: string;
    /** @deprecated Use success instead */
    state?: string;
    /** @deprecated Not returned by backend */
    device_id?: string;
    /** @deprecated Use success instead */
    verified?: boolean;
}

/** Response from GET /device_verification/status/{token} */
export interface DeviceVerificationStatusResponse {
    /** Request token for the verification */
    request_token: string;
    /** Verification token */
    token: string;
    /** Current status of the verification */
    status: "pending" | "accepted" | "rejected" | "expired";
    /** Timestamp when the verification request expires */
    expires_at: number;
    /** Available verification methods */
    methods_available: string[];
    /** @deprecated Use status instead */
    state?: "pending" | "verified" | "cancelled" | "expired";
    /** @deprecated Not returned by backend */
    device_id?: string;
    /** @deprecated Not returned by backend */
    requested_ts?: number;
    /** @deprecated Not returned by backend */
    completed_ts?: number;
}

// ─── Device Trust (v3-only) ───────────────────────────────────

/** Single device trust entry */
export interface DeviceTrustEntry {
    device_id: string;
    user_id?: string;
    trust_level?: "verified" | "cross_signed" | "unverified" | "unknown";
    display_name?: string;
    last_seen_ts?: number;
    last_seen_ip?: string;
}

/** Response from GET /device_trust */
export interface DeviceTrustListResponse {
    devices: DeviceTrustEntry[];
}

/** Response from GET /device_trust/{deviceId} */
export interface DeviceTrustResponse {
    device_id: string;
    trust_level: "verified" | "cross_signed" | "unverified" | "unknown";
    display_name?: string;
    last_seen_ts?: number;
    last_seen_ip?: string;
}

// ─── Security Summary (v3-only) ───────────────────────────────

/** Response from GET /security/summary */
export interface SecuritySummaryResponse {
    /** Number of verified devices */
    verified_devices: number;
    /** Number of unverified devices */
    unverified_devices: number;
    /** Number of blocked devices */
    blocked_devices: number;
    /** Whether cross-signing master key is set up */
    has_cross_signing_master: boolean;
    /** Security score (0-100) */
    security_score: number;
    /** List of security recommendations */
    recommendations: string[];
    /** @deprecated Use has_cross_signing_master instead */
    cross_signing_setup?: boolean;
    /** @deprecated Use blocked_devices count or recommendations instead */
    key_backup_configured?: boolean;
    /** @deprecated Not returned by backend */
    backed_up_sessions?: number;
    /** @deprecated Not returned by backend */
    total_sessions?: number;
}

// ─── Secure Backup (v3-only) ──────────────────────────────────

/** Request body for POST /keys/backup/secure */
export interface SecurityBackupCreateRequest {
    /** Backup algorithm (e.g. "m.megolm_backup.v1.curve25519-aes-sha2") */
    algorithm?: string;
    /** Algorithm-specific auth data */
    auth_data?: Record<string, unknown>;
    /** Passphrase for the backup */
    passphrase?: string;
}

/** Response from POST /keys/backup/secure */
export interface SecurityBackupCreateResponse {
    /** Unique backup identifier */
    backup_id: string;
    /** Version of the created backup */
    version: string;
    /** Algorithm used */
    algorithm: string;
    /** Algorithm-specific auth data */
    auth_data: Record<string, unknown>;
    /** Number of keys currently stored in this backup */
    key_count: number;
}

/** Single backup entry in the backup list */
export interface SecurityBackupEntry {
    /** Unique backup identifier */
    backup_id: string;
    /** Version of the backup */
    version: string;
    /** Algorithm used */
    algorithm: string;
    /** Algorithm-specific auth data */
    auth_data: Record<string, unknown>;
}

/** Response from GET /keys/backup/secure */
export interface SecurityBackupListResponse {
    /** Backups keyed by backup_id */
    [backup_id: string]: SecurityBackupEntry;
}

/** Response from GET /keys/backup/secure/{backupId} */
export interface SecurityBackupGetResponse {
    version: string;
    algorithm: string;
    auth_data?: Record<string, unknown>;
    count?: number;
    etag?: string;
}

/** Request body for POST /keys/backup/secure/{backupId}/keys */
export interface SecureBackupStoreKeysRequest {
    /** Encrypted key data to store */
    keys: Record<string, Record<string, unknown>>;
}

/** Response from POST /keys/backup/secure/{backupId}/keys */
export interface SecureBackupStoreKeysResponse {
    /** Number of keys stored */
    count: number;
    /** ETag of the backup after storing */
    etag: string;
}

/** Request body for POST /keys/backup/secure/{backupId}/restore */
export interface SecureBackupRestoreRequest {
    /** Optional list of room IDs to limit restore scope */
    rooms?: string[];
    /** Passphrase for decryption */
    passphrase?: string;
    /** Key for decryption */
    key?: string;
}

/** Response from POST /keys/backup/secure/{backupId}/restore */
export interface SecureBackupRestoreResponse {
    /** Number of keys recovered */
    recovered_keys: number;
    /** Total keys in backup */
    total_keys: number;
}

/** Request body for POST /keys/backup/secure/{backupId}/verify */
export interface SecureBackupVerifyRequest {
    /** Passphrase to verify */
    passphrase?: string;
    /** Key to verify */
    key?: string;
}

/** Response from POST /keys/backup/secure/{backupId}/verify */
export interface SecureBackupVerifyResponse {
    /** Whether the passphrase/key is valid */
    valid: boolean;
    /** Algorithm of the backup */
    algorithm?: string;
}

// ─── Device List Update ───────────────────────────────────────

/** Request body for POST /keys/device_list/update */
export interface DeviceListUpdateRequest {
    /** User IDs whose device lists should be refreshed */
    users: string[];
}

/** Response from POST /keys/device_list/update */
export interface DeviceListUpdateResponse {
    /** Updated device list changes */
    changed?: string[];
    /** Users no longer tracked */
    left?: string[];
}

// ─── Room Key Distribution ────────────────────────────────────

/** Response from GET /rooms/{roomId}/keys/distribution */
export interface RoomKeyDistributionResponse {
    room_id: string;
    /** Devices that have the key */
    devices?: Array<{
        user_id: string;
        device_id: string;
    }>;
    /** Distribution status */
    status?: string;
}
