/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        E2EE
 * Source:        docs/api-contract/generated/modules/e2ee.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  861502da33164d008ef8ebecb8a87245a47ab5e0
 */

/** Routes served by the synapse-rust `e2ee` module. */
export const E2EE_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/keys/changes" },
    { method: "POST", path: "/_matrix/client/r0/keys/claim" },
    { method: "POST", path: "/_matrix/client/r0/keys/device_list/update" },
    { method: "POST", path: "/_matrix/client/r0/keys/device_signing/upload" },
    { method: "POST", path: "/_matrix/client/r0/keys/query" },
    { method: "POST", path: "/_matrix/client/r0/keys/signatures" },
    { method: "POST", path: "/_matrix/client/r0/keys/signatures/upload" },
    { method: "POST", path: "/_matrix/client/r0/keys/upload" },
    { method: "GET", path: "/_matrix/client/r0/room_keys/request" },
    { method: "POST", path: "/_matrix/client/r0/room_keys/request" },
    { method: "DELETE", path: "/_matrix/client/r0/room_keys/request/{request_id}" },
    { method: "GET", path: "/_matrix/client/r0/rooms/{room_id}/keys/distribution" },
    { method: "POST", path: "/_matrix/client/r0/sendToDevice/{event_type}/{transaction_id}" },
    { method: "PUT", path: "/_matrix/client/r0/sendToDevice/{event_type}/{transaction_id}" },
    { method: "GET", path: "/_matrix/client/v1/keys/changes" },
    { method: "POST", path: "/_matrix/client/v1/keys/claim" },
    { method: "POST", path: "/_matrix/client/v1/keys/device_list/update" },
    { method: "POST", path: "/_matrix/client/v1/keys/device_signing/upload" },
    { method: "POST", path: "/_matrix/client/v1/keys/query" },
    { method: "POST", path: "/_matrix/client/v1/keys/signatures" },
    { method: "POST", path: "/_matrix/client/v1/keys/signatures/upload" },
    { method: "POST", path: "/_matrix/client/v1/keys/upload" },
    { method: "GET", path: "/_matrix/client/v1/room_keys/request" },
    { method: "POST", path: "/_matrix/client/v1/room_keys/request" },
    { method: "DELETE", path: "/_matrix/client/v1/room_keys/request/{request_id}" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/keys/distribution" },
    { method: "POST", path: "/_matrix/client/v1/sendToDevice/{event_type}/{transaction_id}" },
    { method: "PUT", path: "/_matrix/client/v1/sendToDevice/{event_type}/{transaction_id}" },
    { method: "GET", path: "/_matrix/client/v3/device_trust" },
    { method: "GET", path: "/_matrix/client/v3/device_trust/{device_id}" },
    { method: "POST", path: "/_matrix/client/v3/device_verification/request" },
    { method: "POST", path: "/_matrix/client/v3/device_verification/respond" },
    { method: "GET", path: "/_matrix/client/v3/device_verification/status/{token}" },
    { method: "GET", path: "/_matrix/client/v3/keys/backup/secure" },
    { method: "POST", path: "/_matrix/client/v3/keys/backup/secure" },
    { method: "DELETE", path: "/_matrix/client/v3/keys/backup/secure/{backup_id}" },
    { method: "GET", path: "/_matrix/client/v3/keys/backup/secure/{backup_id}" },
    { method: "POST", path: "/_matrix/client/v3/keys/backup/secure/{backup_id}/keys" },
    { method: "POST", path: "/_matrix/client/v3/keys/backup/secure/{backup_id}/restore" },
    { method: "POST", path: "/_matrix/client/v3/keys/backup/secure/{backup_id}/verify" },
    { method: "GET", path: "/_matrix/client/v3/keys/changes" },
    { method: "POST", path: "/_matrix/client/v3/keys/claim" },
    { method: "POST", path: "/_matrix/client/v3/keys/device_list/update" },
    { method: "POST", path: "/_matrix/client/v3/keys/device_signing/upload" },
    { method: "POST", path: "/_matrix/client/v3/keys/query" },
    { method: "POST", path: "/_matrix/client/v3/keys/signatures" },
    { method: "POST", path: "/_matrix/client/v3/keys/signatures/upload" },
    { method: "POST", path: "/_matrix/client/v3/keys/upload" },
    { method: "GET", path: "/_matrix/client/v3/room_keys/request" },
    { method: "POST", path: "/_matrix/client/v3/room_keys/request" },
    { method: "DELETE", path: "/_matrix/client/v3/room_keys/request/{request_id}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/keys/distribution" },
    { method: "GET", path: "/_matrix/client/v3/security/summary" },
    { method: "POST", path: "/_matrix/client/v3/sendToDevice/{event_type}/{transaction_id}" },
    { method: "PUT", path: "/_matrix/client/v3/sendToDevice/{event_type}/{transaction_id}" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `E2EE_ROUTES`. */
export type E2eeRoute = (typeof E2EE_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type E2eeMethod = E2eeRoute["method"];

/** Path templates referenced by this module. */
export type E2eePath = E2eeRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type E2eeReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${E2eeReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type E2eePathPattern = E2eeReplaceBraces<E2eePath>;
