/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/event_report.json
 */

import { EVENT_REPORT_ROUTES } from "./route-table";

export const EVENT_REPORT_ROUTES_ENTRY_COUNT = 19 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _EventReportEntryCountAssertion: 19 = EVENT_REPORT_ROUTES.length;
void _EventReportEntryCountAssertion;

export const EVENT_REPORT_ROUTES_STATUS_SCENARIOS = [
    { status: 202, note: "初版 | -" },
] as const;

export type EventReportStatusScenario = (typeof EVENT_REPORT_ROUTES_STATUS_SCENARIOS)[number];

export const EVENT_REPORT_ROUTES_ERROR_SCENARIOS = [
] as const;

export type EventReportErrorScenario = (typeof EVENT_REPORT_ROUTES_ERROR_SCENARIOS)[number];

export const EVENT_REPORT_ROUTES_ERRCODES = [
] as const;

export type EventReportErrcode = (typeof EVENT_REPORT_ROUTES_ERRCODES)[number];
