/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Event Report
 * Source:        docs/api-contract/generated/modules/event_report.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  c2e43304843f9460bc5d88d93b708016306d97f1
 */

/** Routes served by the synapse-rust `event_report` module. */
export const EVENT_REPORT_ROUTES = [
    { method: "GET", path: "/_synapse/admin/v1/event_reports" },
    { method: "POST", path: "/_synapse/admin/v1/event_reports" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/count" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/event/{event_id}" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/rate_limit/{user_id}" },
    { method: "POST", path: "/_synapse/admin/v1/event_reports/rate_limit/{user_id}/block" },
    { method: "POST", path: "/_synapse/admin/v1/event_reports/rate_limit/{user_id}/unblock" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/reporter/{reporter_user_id}" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/room/{room_id}" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/stats" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/status/{status}" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/status/{status}/count" },
    { method: "DELETE", path: "/_synapse/admin/v1/event_reports/{id}" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/{id}" },
    { method: "PUT", path: "/_synapse/admin/v1/event_reports/{id}" },
    { method: "POST", path: "/_synapse/admin/v1/event_reports/{id}/dismiss" },
    { method: "POST", path: "/_synapse/admin/v1/event_reports/{id}/escalate" },
    { method: "GET", path: "/_synapse/admin/v1/event_reports/{id}/history" },
    { method: "POST", path: "/_synapse/admin/v1/event_reports/{id}/resolve" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `EVENT_REPORT_ROUTES`. */
export type EventReportRoute = (typeof EVENT_REPORT_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type EventReportMethod = EventReportRoute["method"];

/** Path templates referenced by this module. */
export type EventReportPath = EventReportRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type EventReportReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${EventReportReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type EventReportPathPattern = EventReportReplaceBraces<EventReportPath>;
