/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/external_service.json
 */

import { EXTERNAL_SERVICE_ROUTES } from "./route-table";

export const EXTERNAL_SERVICE_ROUTES_ENTRY_COUNT = 10 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _ExternalServiceEntryCountAssertion: 10 = EXTERNAL_SERVICE_ROUTES.length;
void _ExternalServiceEntryCountAssertion;

export const EXTERNAL_SERVICE_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "查询、健康检查或 Webhook 处理成功" },
    { status: 201, note: "外部服务创建成功" },
    { status: 204, note: "外部服务删除成功" },
    { status: 400, note: "服务类型、Webhook 配置或请求体格式非法" },
    { status: 401, note: "管理员凭据缺失，或 Webhook 服务签名/凭据无效" },
    { status: 403, note: "当前账号或服务无权访问目标端点" },
    { status: 404, note: "服务实例不存在" },
    { status: 202, note: "初版 | -" },
    {
        status: 202,
        note: "按 synapse-rust 路由与 SDK 实现修正端点清单、覆盖率和已知差异 | 覆盖率从 0% 修正为 85.7%，明确 Webhook 不纳入 SDK 统计",
    },
] as const;

export type ExternalServiceStatusScenario = (typeof EXTERNAL_SERVICE_ROUTES_STATUS_SCENARIOS)[number];

export const EXTERNAL_SERVICE_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "管理员或服务凭据无效",
        httpOrErrcode: "401 / M_UNKNOWN_TOKEN",
        sdkErrorType: "AuthError",
        handling: "检查管理员登录态或服务侧签名配置",
    },
    {
        scenario: "服务配置不合法",
        httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM",
        sdkErrorType: "ApiError",
        handling: "修正 type、url、config 或 webhook 请求体",
    },
    {
        scenario: "权限不足",
        httpOrErrcode: "403 / M_FORBIDDEN",
        sdkErrorType: "ApiError",
        handling: "确认管理员权限或服务绑定关系",
    },
    {
        scenario: "服务不存在",
        httpOrErrcode: "404 / M_NOT_FOUND",
        sdkErrorType: "NotFoundError",
        handling: "刷新服务列表并核对 as_id/service_id",
    },
] as const;

export type ExternalServiceErrorScenario = (typeof EXTERNAL_SERVICE_ROUTES_ERROR_SCENARIOS)[number];

export const EXTERNAL_SERVICE_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "管理员凭据或服务签名无效" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "外部服务请求体结构不合法" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "as_id、service_id 或服务配置参数非法" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "当前账号或服务无权访问目标端点" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "目标外部服务不存在" },
] as const;

export type ExternalServiceErrcode = (typeof EXTERNAL_SERVICE_ROUTES_ERRCODES)[number];
