/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { EXTERNAL_SERVICE_ROUTES } from "./route-table";

export const EXTERNAL_SERVICE_ROUTES_ENTRY_COUNT = 18 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _ExternalServiceEntryCountAssertion: 18 = EXTERNAL_SERVICE_ROUTES.length;
void _ExternalServiceEntryCountAssertion;

export const EXTERNAL_SERVICE_ROUTES_STATUS_SCENARIOS = [
    { status: 202, note: "初版 | -" },
] as const;

export type ExternalServiceStatusScenario = (typeof EXTERNAL_SERVICE_ROUTES_STATUS_SCENARIOS)[number];

export const EXTERNAL_SERVICE_ROUTES_ERROR_SCENARIOS = [
] as const;

export type ExternalServiceErrorScenario = (typeof EXTERNAL_SERVICE_ROUTES_ERROR_SCENARIOS)[number];

export const EXTERNAL_SERVICE_ROUTES_ERRCODES = [
] as const;

export type ExternalServiceErrcode = (typeof EXTERNAL_SERVICE_ROUTES_ERRCODES)[number];
