/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { SYNC_ROUTES } from "./route-table";

export const SYNC_ROUTES_ENTRY_COUNT = 10 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _SyncEntryCountAssertion: 10 = SYNC_ROUTES.length;
void _SyncEntryCountAssertion;

export const SYNC_ROUTES_STATUS_SCENARIOS = [
    { status: 357, note: "POST /sync" },
    { status: 200, note: "请求成功" },
    { status: 400, note: "参数错误" },
    { status: 401, note: "Token 无效或缺失" },
    { status: 429, note: "长轮询或同步请求被限流" },
] as const;

export type SyncStatusScenario = (typeof SYNC_ROUTES_STATUS_SCENARIOS)[number];

export const SYNC_ROUTES_ERROR_SCENARIOS = [
] as const;

export type SyncErrorScenario = (typeof SYNC_ROUTES_ERROR_SCENARIOS)[number];

export const SYNC_ROUTES_ERRCODES = [
] as const;

export type SyncErrcode = (typeof SYNC_ROUTES_ERRCODES)[number];
