/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/sync.md
 */

/**
 * DTO snippets extracted from the contract doc for `sync`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export type SyncContractDtoPlaceholder = never;
