// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/sync.md

// ─── Sync Request ─────────────────────────────────────────────

/** Query parameters for GET /sync */
export interface SyncRequest {
    /** Filter ID or filter JSON */
    filter?: string;
    /** Whether to return full state (for initial sync) */
    full_state?: boolean;
    /** Set presence instead of marking the user as online */
    set_presence?: string;
    /** Timeout in milliseconds for long-polling */
    timeout?: number;
    /** Token from the previous sync response */
    since?: string;
}

// ─── Sync Response ────────────────────────────────────────────

/** Response from GET /sync */
export interface SyncResponse {
    /** Token for the next sync request */
    next_batch: string;
    /** Room data grouped by membership */
    rooms?: SyncRooms;
    /** Presence updates */
    presence?: SyncPresence;
    /** Global account data */
    account_data?: SyncAccountData;
    /** To-device messages */
    to_device?: SyncToDevice;
    /** Device list changes */
    device_lists?: SyncDeviceLists;
    /** One-time key counts */
    device_one_time_keys_count?: Record<string, number>;
    /** Unused fallback key types */
    device_unused_fallback_key_types?: string[];
}

// ─── Rooms ────────────────────────────────────────────────────

/** Room data grouped by membership category */
export interface SyncRooms {
    /** Joined rooms */
    join?: Record<string, SyncJoinedRoom>;
    /** Invited rooms */
    invite?: Record<string, SyncInvitedRoom>;
    /** Left rooms */
    leave?: Record<string, SyncLeftRoom>;
    /** Knocked rooms */
    knock?: Record<string, SyncKnockedRoom>;
}

/** A joined room in the sync response */
export interface SyncJoinedRoom {
    /** Room summary */
    summary?: SyncRoomSummary;
    /** State events (current or after timeline) */
    state?: SyncState;
    /** Room timeline */
    timeline: SyncTimeline;
    /** Ephemeral events (typing, receipts) */
    ephemeral?: SyncEphemeral;
    /** Room account data */
    account_data?: SyncAccountData;
    /** Unread notification counts */
    unread_notifications?: SyncUnreadNotifications;
    /** Unread thread notification counts */
    unread_thread_notifications?: Record<string, SyncUnreadNotifications>;
}

/** An invited room in the sync response */
export interface SyncInvitedRoom {
    /** Stripped state from the invite */
    invite_state: SyncInviteState;
}

/** A left room in the sync response */
export interface SyncLeftRoom {
    /** State events */
    state?: SyncState;
    /** Room timeline */
    timeline: SyncTimeline;
    /** Room account data */
    account_data?: SyncAccountData;
}

/** A knocked room in the sync response */
export interface SyncKnockedRoom {
    /** Stripped state from the knock */
    knock_state: SyncKnockState;
}

// ─── Room Summary ─────────────────────────────────────────────

/** Room summary (optimised representation of room state) */
export interface SyncRoomSummary {
    /** Heroes (users) for the room */
    "m.heroes"?: string[];
    /** Number of joined members */
    "m.joined_member_count"?: number;
    /** Number of invited members */
    "m.invited_member_count"?: number;
}

// ─── State ────────────────────────────────────────────────────

/** A batch of state events */
export interface SyncState {
    /** List of state events */
    events: SyncStateEvent[];
}

/** A state event in the sync response */
export interface SyncStateEvent {
    /** Event content */
    content: Record<string, unknown>;
    /** Event type */
    type: string;
    /** Event ID */
    event_id: string;
    /** Sender user ID */
    sender: string;
    /** Origin server timestamp (ms) */
    origin_server_ts: number;
    /** State key */
    state_key: string;
    /** Previous content (for redacted/updated state) */
    prev_content?: Record<string, unknown>;
    /** Unsigned data */
    unsigned?: Record<string, unknown>;
}

// ─── Timeline ─────────────────────────────────────────────────

/** Room timeline in the sync response */
export interface SyncTimeline {
    /** Timeline events (messages and state) */
    events: SyncTimelineEvent[];
    /** Whether the timeline is limited (gap in history) */
    limited?: boolean;
    /** Pagination token for backfilling (null at start) */
    prev_batch: string | null;
}

/** A timeline event in the sync response */
export interface SyncTimelineEvent {
    /** Event content */
    content: Record<string, unknown>;
    /** Event type */
    type: string;
    /** Event ID */
    event_id: string;
    /** Sender user ID */
    sender: string;
    /** Origin server timestamp (ms) */
    origin_server_ts: number;
    /** Room ID (optional in some contexts) */
    room_id?: string;
    /** Unsigned data */
    unsigned?: Record<string, unknown>;
}

// ─── Ephemeral ────────────────────────────────────────────────

/** Ephemeral events (not stored in room state) */
export interface SyncEphemeral {
    /** Ephemeral events (typing, receipts) */
    events: SyncMinimalEvent[];
}

// ─── Presence ─────────────────────────────────────────────────

/** Presence updates in the sync response */
export interface SyncPresence {
    /** Presence events */
    events: SyncMinimalEvent[];
}

// ─── Account Data ─────────────────────────────────────────────

/** Account data in the sync response */
export interface SyncAccountData {
    /** Account data events */
    events: SyncMinimalEvent[];
}

/** A minimal event (content + type only) */
export interface SyncMinimalEvent {
    /** Event content */
    content: Record<string, unknown>;
    /** Event type */
    type: string;
    /** Room ID (optional) */
    room_id?: string;
    /** Unsigned data */
    unsigned?: Record<string, unknown>;
}

// ─── Invite State ─────────────────────────────────────────────

/** Stripped state from an invite */
export interface SyncInviteState {
    /** Stripped state events */
    events: SyncStrippedState[];
}

/** A stripped state event (no event_id, no origin_server_ts) */
export interface SyncStrippedState {
    /** Event content */
    content: Record<string, unknown>;
    /** State key */
    state_key: string;
    /** Event type */
    type: string;
    /** Sender user ID */
    sender: string;
}

// ─── Knock State ──────────────────────────────────────────────

/** Stripped state from a knock */
export interface SyncKnockState {
    /** Stripped state events */
    events: SyncStrippedState[];
}

// ─── To-Device ────────────────────────────────────────────────

/** To-device messages in the sync response */
export interface SyncToDevice {
    /** To-device events */
    events: SyncToDeviceEvent[];
}

/** A to-device event */
export interface SyncToDeviceEvent {
    /** Event content */
    content: Record<string, unknown>;
    /** Sender user ID */
    sender: string;
    /** Event type */
    type: string;
}

// ─── Device Lists ─────────────────────────────────────────────

/** Device list changes in the sync response */
export interface SyncDeviceLists {
    /** User IDs whose devices have changed */
    changed?: string[];
    /** User IDs who are no longer tracked */
    left?: string[];
}

// ─── Unread Notifications ─────────────────────────────────────

/** Unread notification counts for a room */
export interface SyncUnreadNotifications {
    /** Number of highlighted notifications */
    highlight_count?: number;
    /** Number of total notifications */
    notification_count?: number;
}
