/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Sync 模块契约
 * Source:        docs/api-contract/generated/modules/sync.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  f282009ea36a63cacdd12770d441b2a2a655d082
 */

/** Routes served by the synapse-rust `sync` module. */
export const SYNC_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/events" },
    { method: "GET", path: "/_matrix/client/r0/joined_rooms" },
    { method: "GET", path: "/_matrix/client/r0/sync" },
    { method: "GET", path: "/_matrix/client/v3/events" },
    { method: "GET", path: "/_matrix/client/v3/joined_rooms" },
    { method: "GET", path: "/_matrix/client/v3/my_rooms" },
    { method: "GET", path: "/_matrix/client/v3/sync" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `SYNC_ROUTES`. */
export type SyncRoute = (typeof SYNC_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type SyncMethod = SyncRoute["method"];

/** Path templates referenced by this module. */
export type SyncPath = SyncRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type SyncReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${SyncReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type SyncPathPattern = SyncReplaceBraces<SyncPath>;
