/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/feature-flags.md
 */

/**
 * DTO snippets extracted from the contract doc for `feature-flags`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface FeatureFlagsResponse {
    flags: Array<{
        name: string;
        enabled: boolean;
        description: string;
        created_ts: number;
        updated_ts: number;
    }>;
}

export interface FeatureFlag {
    name: string;
    enabled: boolean;
    description: string;
    created_ts: number;
    updated_ts: number;
}

export interface FeatureFlagsRequestDto {
    enabled: boolean;
}

export type FeatureFlagsResponseDto = Record<string, never>;
