/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Feature Flags
 * Source:        docs/api-contract/generated/modules/feature_flags.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  ef9bd5d4d22c35afba65b2b5452278f6a0a28115
 */

/** Routes served by the synapse-rust `feature_flags` module. */
export const FEATURE_FLAGS_ROUTES = [
    { method: "GET", path: "/_synapse/admin/v1/feature-flags" },
    { method: "POST", path: "/_synapse/admin/v1/feature-flags" },
    { method: "GET", path: "/_synapse/admin/v1/feature-flags/{flag_key}" },
    { method: "PATCH", path: "/_synapse/admin/v1/feature-flags/{flag_key}" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `FEATURE_FLAGS_ROUTES`. */
export type FeatureFlagsRoute = (typeof FEATURE_FLAGS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type FeatureFlagsMethod = FeatureFlagsRoute["method"];

/** Path templates referenced by this module. */
export type FeatureFlagsPath = FeatureFlagsRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type FeatureFlagsReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${FeatureFlagsReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type FeatureFlagsPathPattern = FeatureFlagsReplaceBraces<FeatureFlagsPath>;
