/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/oidc.json
 */

import { OIDC_ROUTES } from "./route-table";

export const OIDC_ROUTES_ENTRY_COUNT = 16 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _OidcEntryCountAssertion: 16 = OIDC_ROUTES.length;
void _OidcEntryCountAssertion;

export const OIDC_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "查询或回调处理成功" },
    { status: 302, note: "重定向到 OIDC 提供方或登录完成后的目标地址" },
    { status: 400, note: "OIDC 未启用、缺少 code/state 或请求参数不合法" },
    { status: 401, note: "state 失效、会话过期或 PKCE 校验失败" },
    { status: 403, note: "OIDC 提供方拒绝授权或用户无权完成流程" },
    { status: 429, note: "触发限流" },
] as const;

export type OidcStatusScenario = (typeof OIDC_ROUTES_STATUS_SCENARIOS)[number];

export const OIDC_ROUTES_ERROR_SCENARIOS = [
    { scenario: "OIDC 状态失效或会话过期", httpOrErrcode: "401 / M_UNKNOWN_TOKEN", sdkErrorType: "AuthError", handling: "重新发起授权流程，不复用旧 state" },
    { scenario: "请求参数缺失或 OIDC 未启用", httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "检查 redirectUrl、code、state 与服务端开关" },
    { scenario: "授权被拒绝或回调校验失败", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "提示用户重新授权，必要时更换账号" },
    { scenario: "限流或短暂服务异常", httpOrErrcode: "429 / M_LIMIT_EXCEEDED", sdkErrorType: "RetryableError", handling: "使用退避重试" },
    { scenario: "其他 API 错误", httpOrErrcode: "其他 4xx/5xx", sdkErrorType: "ApiError", handling: "按 code 与 statusCode 做兜底处理" },
] as const;

export type OidcErrorScenario = (typeof OIDC_ROUTES_ERROR_SCENARIOS)[number];

export const OIDC_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "OIDC state 缺失、已过期或已被消费" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "回调参数结构不符合接口要求" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "redirectUrl、code、state 或 PKCE 参数非法" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "提供方拒绝授权或当前用户不允许完成绑定" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "OIDC 登录链路触发限流" },
] as const;

export type OidcErrcode = (typeof OIDC_ROUTES_ERRCODES)[number];
