// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/oidc.md

// ─── OIDC Discovery ───────────────────────────────────────────

/** OpenID Connect Discovery metadata (/.well-known/openid-configuration) */
export interface OidcWellKnownResponse {
    /** Issuer identifier */
    issuer: string;
    /** Authorization endpoint URL */
    authorization_endpoint: string;
    /** Token endpoint URL */
    token_endpoint: string;
    /** Userinfo endpoint URL (optional) */
    userinfo_endpoint?: string;
    /** JWKS URI for signing keys (optional) */
    jwks_uri?: string;
    /** Dynamic client registration endpoint (optional) */
    registration_endpoint?: string;
    /** Supported scopes */
    scopes_supported?: string[];
    /** Supported response types */
    response_types_supported?: string[];
    /** Supported code challenge methods */
    code_challenge_methods_supported?: string[];
    /** Revocation endpoint URL */
    revocation_endpoint?: string;
    /** Supported grant types */
    grant_types_supported?: string[];
    /** Account management URI (MSC4191) */
    account_management_uri?: string;
    /** Account management actions supported */
    account_management_actions_supported?: string[];
    /** Supported prompt values */
    prompt_values_supported?: string[];
    /** Device authorization endpoint (MSC4341) */
    device_authorization_endpoint?: string;
}

// ─── OIDC JWKS ────────────────────────────────────────────────

/** JSON Web Key Set */
export interface OidcJwks {
    /** List of JWK keys */
    keys: Array<{
        /** Key type (e.g. "RSA") */
        kty: string;
        /** Key ID */
        kid: string;
        /** Key usage (e.g. "sig") */
        use?: string;
        /** Algorithm (e.g. "RS256") */
        alg?: string;
        /** RSA modulus (base64url) */
        n?: string;
        /** RSA exponent (base64url) */
        e?: string;
    }>;
}

// ─── OIDC Authorization ───────────────────────────────────────

/** Authorization parameters for GET /oidc/authorize */
export interface OidcAuthRequest {
    /** Client ID registered with the OP */
    client_id: string;
    /** Redirect URI after authorization */
    redirect_uri: string;
    /** Response type (typically "code") */
    response_type: string;
    /** Requested scopes (e.g. "openid") */
    scope: string;
    /** Opaque state parameter for CSRF protection */
    state?: string;
    /** Nonce for ID token validation */
    nonce?: string;
    /** PKCE code challenge */
    code_challenge?: string;
    /** PKCE code challenge method (e.g. "S256") */
    code_challenge_method?: string;
}

/** Response from GET /oidc/authorize */
export interface OidcAuthResponse {
    /** Redirect URL for the authorization flow */
    url?: string;
    /** Authorization code (if direct response) */
    code?: string;
}

// ─── OIDC Token ───────────────────────────────────────────────

/** Request body for POST /oidc/token */
export interface OidcTokenRequest {
    /** Grant type (e.g. "authorization_code", "refresh_token") */
    grant_type: string;
    /** Authorization code (for authorization_code grant) */
    code?: string;
    /** Redirect URI (must match the authorization request) */
    redirect_uri?: string;
    /** PKCE code verifier */
    code_verifier?: string;
    /** Refresh token (for refresh_token grant) */
    refresh_token?: string;
    /** Client ID */
    client_id?: string;
    /** Client secret (for confidential clients) */
    client_secret?: string;
}

/** Response from POST /oidc/token */
export interface OidcTokenResponse {
    /** Access token */
    access_token: string;
    /** Refresh token (optional, returned on first auth) */
    refresh_token?: string;
    /** ID token (JWT) */
    id_token?: string;
    /** Token type (typically "Bearer") */
    token_type: string;
    /** Token expiry in seconds */
    expires_in: number;
}

// ─── OIDC UserInfo ────────────────────────────────────────────

/** Response from GET /oidc/userinfo */
export interface OidcUserInfoResponse {
    /** Subject identifier */
    sub: string;
    /** User display name */
    name?: string;
    /** User avatar URL */
    picture?: string;
    /** User email */
    email?: string;
}

// ─── OIDC Client Registration ─────────────────────────────────

/** Request body for POST /oidc/register */
export interface OidcRegisterRequest {
    /** Client name */
    client_name?: string;
    /** Allowed redirect URIs */
    redirect_uris: string[];
    /** Allowed grant types */
    grant_types?: string[];
    /** Allowed response types */
    response_types?: string[];
    /** Token endpoint authentication method */
    token_endpoint_auth_method?: string;
}

/** Response from POST /oidc/register */
export interface OidcClientRegistration {
    /** Assigned client ID */
    client_id: string;
    /** Client secret (optional) */
    client_secret?: string;
    /** Client name */
    client_name?: string;
    /** Registered redirect URIs */
    redirect_uris: string[];
}

// ─── OIDC Login ───────────────────────────────────────────────

/** Request body for POST /oidc/login (built-in OIDC login) */
export interface OidcLoginRequest {
    /** Client ID */
    client_id: string;
    /** Redirect URI */
    redirect_uri: string;
    /** Requested scopes (default: "openid") */
    scope?: string;
    /** State parameter */
    state?: string;
    /** Nonce parameter */
    nonce?: string;
    /** PKCE code verifier */
    code_verifier?: string;
    /** Username for authentication */
    username: string;
    /** Password for authentication */
    password: string;
}

/** Response from POST /oidc/login */
export interface OidcLoginResponse {
    /** Authorization code */
    code: string;
}

// ─── OIDC Logout ──────────────────────────────────────────────

/** Request body for POST /oidc/logout */
export interface OidcLogoutRequest {
    /** Client ID initiating logout */
    client_id?: string;
    /** URI to redirect after logout */
    post_logout_redirect_uri?: string;
    /** ID token hint for logout */
    id_token_hint?: string;
}

// ─── OIDC Callback ────────────────────────────────────────────

/** Query parameters received on the OIDC callback */
export interface OidcCallbackRequest {
    /** Authorization code returned by the OP */
    code: string;
    /** State parameter (must match the original) */
    state: string;
}

// ─── SSO Redirect ─────────────────────────────────────────────

/** Response from GET /login/sso/redirect */
export interface SsoRedirectResponse {
    /** URL to redirect the user to */
    url: string;
}
