/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        OIDC 契约
 * Source:        docs/api-contract/generated/modules/oidc.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  4ea2cc71c82770204c71aba66cead18f43c74b8e
 */

/** Routes served by the synapse-rust `oidc` module. */
export const OIDC_ROUTES = [
    { method: "GET", path: "/.well-known/jwks.json" },
    { method: "GET", path: "/.well-known/openid-configuration" },
    { method: "GET", path: "/_matrix/client/r0/login/sso/redirect" },
    { method: "GET", path: "/_matrix/client/r0/login/sso/userinfo" },
    { method: "GET", path: "/_matrix/client/r0/oidc/authorize" },
    { method: "GET", path: "/_matrix/client/r0/oidc/callback" },
    { method: "POST", path: "/_matrix/client/r0/oidc/logout" },
    { method: "POST", path: "/_matrix/client/r0/oidc/token" },
    { method: "GET", path: "/_matrix/client/r0/oidc/userinfo" },
    { method: "GET", path: "/_matrix/client/v3/login/sso/redirect" },
    { method: "GET", path: "/_matrix/client/v3/login/sso/userinfo" },
    { method: "GET", path: "/_matrix/client/v3/oidc/authorize" },
    { method: "GET", path: "/_matrix/client/v3/oidc/callback" },
    { method: "POST", path: "/_matrix/client/v3/oidc/login" },
    { method: "POST", path: "/_matrix/client/v3/oidc/logout" },
    { method: "POST", path: "/_matrix/client/v3/oidc/token" },
    { method: "GET", path: "/_matrix/client/v3/oidc/userinfo" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `OIDC_ROUTES`. */
export type OidcRoute = (typeof OIDC_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type OidcMethod = OidcRoute["method"];

/** Path templates referenced by this module. */
export type OidcPath = OidcRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type OidcReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${OidcReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type OidcPathPattern = OidcReplaceBraces<OidcPath>;
