/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/key_backup.json
 */

import { KEY_BACKUP_ROUTES } from "./route-table";

export const KEY_BACKUP_ROUTES_ENTRY_COUNT = 132 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _KeyBackupEntryCountAssertion: 132 = KEY_BACKUP_ROUTES.length;
void _KeyBackupEntryCountAssertion;

export const KEY_BACKUP_ROUTES_STATUS_SCENARIOS = [
] as const;

export type KeyBackupStatusScenario = (typeof KEY_BACKUP_ROUTES_STATUS_SCENARIOS)[number];

export const KEY_BACKUP_ROUTES_ERROR_SCENARIOS = [
] as const;

export type KeyBackupErrorScenario = (typeof KEY_BACKUP_ROUTES_ERROR_SCENARIOS)[number];

export const KEY_BACKUP_ROUTES_ERRCODES = [
] as const;

export type KeyBackupErrcode = (typeof KEY_BACKUP_ROUTES_ERRCODES)[number];
