/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/openclaw.json
 */

import { OPENCLAW_ROUTES } from "./route-table";

export const OPENCLAW_ROUTES_ENTRY_COUNT = 23 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _OpenclawEntryCountAssertion: 23 = OPENCLAW_ROUTES.length;
void _OpenclawEntryCountAssertion;

export const OPENCLAW_ROUTES_STATUS_SCENARIOS = [
] as const;

export type OpenclawStatusScenario = (typeof OPENCLAW_ROUTES_STATUS_SCENARIOS)[number];

export const OPENCLAW_ROUTES_ERROR_SCENARIOS = [
] as const;

export type OpenclawErrorScenario = (typeof OPENCLAW_ROUTES_ERROR_SCENARIOS)[number];

export const OPENCLAW_ROUTES_ERRCODES = [
] as const;

export type OpenclawErrcode = (typeof OPENCLAW_ROUTES_ERRCODES)[number];
