/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        OpenClaw 契约
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       34 (authoritative set mirrored from the backend contract)
 */

/** Routes served by the synapse-rust `open-claw` module (mirrored from the backend contract). */
export const OPENCLAW_ROUTES = [
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/connections" },
    { method: "POST", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/connections" },
    { method: "DELETE", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/connections/{id}" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/connections/{id}" },
    { method: "PUT", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/connections/{id}" },
    { method: "POST", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/connections/{id}/test" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/conversations" },
    { method: "POST", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/conversations" },
    { method: "DELETE", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/conversations/{id}" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/conversations/{id}" },
    { method: "PUT", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/conversations/{id}" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/conversations/{id}/messages" },
    { method: "POST", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/conversations/{id}/messages" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/generations" },
    { method: "POST", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/generations" },
    { method: "DELETE", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/generations/{id}" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/generations/{id}" },
    { method: "DELETE", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/messages/{id}" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/roles" },
    { method: "POST", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/roles" },
    { method: "DELETE", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/roles/{id}" },
    { method: "GET", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/roles/{id}" },
    { method: "PUT", path: "/_matrix/client/unstable/org.synapse_rust.openclaw/roles/{id}" },
    { method: "DELETE", path: "/_matrix/client/v3/messages/{id}" },
    { method: "GET", path: "/_matrix/client/v3/connections" },
    { method: "GET", path: "/_matrix/client/v3/connections/{id}" },
    { method: "GET", path: "/_matrix/client/v3/conversations" },
    { method: "GET", path: "/_matrix/client/v3/conversations/{id}" },
    { method: "GET", path: "/_matrix/client/v3/conversations/{id}/messages" },
    { method: "GET", path: "/_matrix/client/v3/generations" },
    { method: "GET", path: "/_matrix/client/v3/generations/{id}" },
    { method: "GET", path: "/_matrix/client/v3/roles" },
    { method: "GET", path: "/_matrix/client/v3/roles/{id}" },
    { method: "POST", path: "/_matrix/client/v3/connections/{id}/test" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `OPENCLAW_ROUTES`. */
export type OpenclawRoute = (typeof OPENCLAW_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type OpenclawMethod = OpenclawRoute["method"];

/** Path templates referenced by this module. */
export type OpenclawPath = OpenclawRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type OpenclawReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${OpenclawReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type OpenclawPathPattern = OpenclawReplaceBraces<OpenclawPath>;
