/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/worker_body.json
 */

import { WORKER_BODY_ROUTES } from "./route-table";

export const WORKER_BODY_ROUTES_ENTRY_COUNT = 11 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _WorkerBodyEntryCountAssertion: 11 = WORKER_BODY_ROUTES.length;
void _WorkerBodyEntryCountAssertion;

export const WORKER_BODY_ROUTES_STATUS_SCENARIOS = [
    { status: 200, note: "命令完成或失败上报成功" },
    { status: 400, note: "command_id、请求体或完成结果非法" },
    { status: 401, note: "replication HTTP 凭据无效或缺失" },
    { status: 403, note: "当前 worker 凭据无权上报该命令" },
    { status: 404, note: "目标命令不存在" },
] as const;

export type WorkerBodyStatusScenario = (typeof WORKER_BODY_ROUTES_STATUS_SCENARIOS)[number];

export const WORKER_BODY_ROUTES_ERROR_SCENARIOS = [
    {
        scenario: "replication 凭据无效或缺失",
        httpOrErrcode: "401 / M_UNKNOWN_TOKEN",
        sdkErrorType: "AuthError",
        handling: "使用正确的 replication HTTP 鉴权重试上报",
    },
    {
        scenario: "command 上报参数或 body 非法",
        httpOrErrcode: "400 / M_BAD_JSON M_INVALID_PARAM",
        sdkErrorType: "ApiError",
        handling: "修正 command_id、结果体或错误体后重试",
    },
    {
        scenario: "当前 worker 无权操作该命令",
        httpOrErrcode: "403 / M_FORBIDDEN",
        sdkErrorType: "ApiError",
        handling: "检查 worker 身份与 replication 权限配置",
    },
    {
        scenario: "目标命令不存在",
        httpOrErrcode: "404 / M_NOT_FOUND",
        sdkErrorType: "NotFoundError",
        handling: "刷新命令列表并核对 command_id 后重试",
    },
] as const;

export type WorkerBodyErrorScenario = (typeof WORKER_BODY_ROUTES_ERROR_SCENARIOS)[number];

export const WORKER_BODY_ROUTES_ERRCODES = [
    { errcode: "M_UNKNOWN_TOKEN", httpStatus: "401", note: "replication HTTP 凭据无效、过期或缺失" },
    { errcode: "M_BAD_JSON", httpStatus: "400", note: "complete / fail 请求体结构不合法" },
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "command_id、结果体或错误信息参数非法" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "当前 worker 无权操作该命令" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "目标命令不存在" },
] as const;

export type WorkerBodyErrcode = (typeof WORKER_BODY_ROUTES_ERRCODES)[number];
