/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/synapse-rust/ROUTE_CONTRACT.md
 */

import { WORKER_BODY_ROUTES } from "./route-table";

export const WORKER_BODY_ROUTES_ENTRY_COUNT = 11 as const;

// Compile-time assertion: route-table length must stay aligned with the backend contract.
const _WorkerBodyEntryCountAssertion: 11 = WORKER_BODY_ROUTES.length;
void _WorkerBodyEntryCountAssertion;

export const WORKER_BODY_ROUTES_STATUS_SCENARIOS = [
] as const;

export type WorkerBodyStatusScenario = (typeof WORKER_BODY_ROUTES_STATUS_SCENARIOS)[number];

export const WORKER_BODY_ROUTES_ERROR_SCENARIOS = [
] as const;

export type WorkerBodyErrorScenario = (typeof WORKER_BODY_ROUTES_ERROR_SCENARIOS)[number];

export const WORKER_BODY_ROUTES_ERRCODES = [
] as const;

export type WorkerBodyErrcode = (typeof WORKER_BODY_ROUTES_ERRCODES)[number];
