// Auto-generated by contract:codegen. Do not edit manually.
// Source: docs/api-contract/worker-body.md

// ─── Worker Task ─────────────────────────────────────────────

/** Worker task info */
export interface WorkerTask {
    /** Task ID */
    task_id: string;
    /** Task type */
    task_type: string;
    /** Task status */
    status: string;
    /** Assigned worker ID, null if unassigned */
    assigned_worker_id: string | null;
}

// ─── Worker Task Result ──────────────────────────────────────

/** Command response received by a worker */
export interface WorkerCommandResponse {
    /** Unique command ID */
    command_id: string;
    /** Target worker ID */
    target_worker_id: string;
    /** Command type string */
    command_type: string;
    /** Command status */
    status: string;
    /** Timestamp when the command was created (ms) */
    created_ts: number;
}

/** Response from listing pending commands */
export interface PendingCommandsResponse {
    /** List of pending commands */
    commands: WorkerCommandResponse[];
}

// ─── Worker Heartbeat ────────────────────────────────────────

/** Request body for a worker heartbeat */
export interface WorkerHeartbeat {
    /** Current worker status string */
    status: string;
    /** Load statistics */
    load_stats?: Record<string, unknown>;
}

/** Request body for connecting a worker */
export interface WorkerConnectRequest {
    /** Worker address */
    address: string;
}

// ─── Worker Task Completion ──────────────────────────────────

/** Request body for completing a task */
export interface CompleteTaskRequest {
    /** Task result payload */
    result?: unknown;
}

/** Request body for failing a task */
export interface FailTaskRequest {
    /** Error message */
    error: string;
}

/** Request body for failing a command */
export interface FailCommandRequest {
    /** Error message */
    error: string;
}

// ─── Replication Position ────────────────────────────────────

/** Response from getting replication position */
export interface ReplicationPositionResponse {
    /** Current stream position */
    position?: number;
    /** Stream name */
    stream_name?: string;
    /** Worker ID */
    worker_id?: string;
}

/** Request body for updating replication position */
export interface UpdateReplicationPositionRequest {
    /** Stream name */
    stream_name: string;
    /** New position */
    position: number;
}
