/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Worker Body 契约
 * Source:        docs/api-contract/generated/modules/worker_body.json
 * Ledger schema: 1
 * Source profile: all
 * synapse-rust:  f282009ea36a63cacdd12770d441b2a2a655d082
 */

/** Routes served by the synapse-rust `worker_body` module. */
export const WORKER_BODY_ROUTES = [
    { method: "POST", path: "/_synapse/worker/v1/commands/{command_id}/complete" },
    { method: "POST", path: "/_synapse/worker/v1/commands/{command_id}/fail" },
    { method: "GET", path: "/_synapse/worker/v1/events" },
    { method: "GET", path: "/_synapse/worker/v1/replication/{worker_id}/position" },
    { method: "PUT", path: "/_synapse/worker/v1/replication/{worker_id}/{stream_name}" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/{task_id}/complete" },
    { method: "POST", path: "/_synapse/worker/v1/tasks/{task_id}/fail" },
    { method: "GET", path: "/_synapse/worker/v1/workers/{worker_id}/commands" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/connect" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/disconnect" },
    { method: "POST", path: "/_synapse/worker/v1/workers/{worker_id}/heartbeat" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `WORKER_BODY_ROUTES`. */
export type WorkerBodyRoute = (typeof WORKER_BODY_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type WorkerBodyMethod = WorkerBodyRoute["method"];

/** Path templates referenced by this module. */
export type WorkerBodyPath = WorkerBodyRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type WorkerBodyReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${WorkerBodyReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type WorkerBodyPathPattern = WorkerBodyReplaceBraces<WorkerBodyPath>;
