/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/generated/modules/key_rotation.json
 */

import { KEY_ROTATION_ROUTES } from "./route-table";

export const KEY_ROTATION_ROUTES_ENTRY_COUNT = 9 as const;

// Compile-time assertion: route-table length must stay aligned with the generated manifest.
const _KeyRotationEntryCountAssertion: 9 = KEY_ROTATION_ROUTES.length;
void _KeyRotationEntryCountAssertion;

export const KEY_ROTATION_ROUTES_STATUS_SCENARIOS = [
    { status: 400, note: "M_INVALID_PARAM | 参数无效" },
    { status: 401, note: "M_UNAUTHORIZED | 未认证" },
    { status: 403, note: "M_FORBIDDEN | 无权限操作" },
    { status: 404, note: "M_NOT_FOUND | 密钥不存在" },
    { status: 429, note: "M_LIMIT_EXCEEDED | 轮换频率过高" },
    { status: 202, note: "初版 | -" },
    { status: 202, note: "新增 KeyRotationManager SDK 封装并补齐单元测试 | SDK 封装覆盖率提升至 100%" },
    { status: 202, note: "修正类型定义以对齐后端实际响应 | 修正所有端点的请求/响应类型" },
] as const;

export type KeyRotationStatusScenario = (typeof KEY_ROTATION_ROUTES_STATUS_SCENARIOS)[number];

export const KEY_ROTATION_ROUTES_ERROR_SCENARIOS = [
    { scenario: "参数无效", httpOrErrcode: "400 / M_INVALID_PARAM", sdkErrorType: "ApiError", handling: "参数无效" },
    { scenario: "未认证", httpOrErrcode: "401 / M_UNAUTHORIZED", sdkErrorType: "AuthError", handling: "未认证" },
    { scenario: "无权限操作", httpOrErrcode: "403 / M_FORBIDDEN", sdkErrorType: "ApiError", handling: "无权限操作" },
    { scenario: "密钥不存在", httpOrErrcode: "404 / M_NOT_FOUND", sdkErrorType: "NotFoundError", handling: "密钥不存在" },
    { scenario: "轮换频率过高", httpOrErrcode: "429 / M_LIMIT_EXCEEDED", sdkErrorType: "RetryableError", handling: "轮换频率过高" },
] as const;

export type KeyRotationErrorScenario = (typeof KEY_ROTATION_ROUTES_ERROR_SCENARIOS)[number];

export const KEY_ROTATION_ROUTES_ERRCODES = [
    { errcode: "M_INVALID_PARAM", httpStatus: "400", note: "参数无效" },
    { errcode: "M_UNAUTHORIZED", httpStatus: "401", note: "未认证" },
    { errcode: "M_FORBIDDEN", httpStatus: "403", note: "无权限操作" },
    { errcode: "M_NOT_FOUND", httpStatus: "404", note: "密钥不存在" },
    { errcode: "M_LIMIT_EXCEEDED", httpStatus: "429", note: "轮换频率过高" },
] as const;

export type KeyRotationErrcode = (typeof KEY_ROTATION_ROUTES_ERRCODES)[number];
