/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 * Source: docs/api-contract/key-rotation.md
 *
 * NOTE: Updated to align with actual backend responses from
 * synapse-rust/src/web/routes/key_rotation.rs
 */

/**
 * DTO snippets extracted from the contract doc for `key_rotation`.
 * These declarations make prompt-reviewed request/response shapes importable from a stable path.
 */

export interface KeyRotationStatus {
    enabled: boolean;
    status: Record<string, unknown>;
    user_last_rotation: number | null;
}

export interface RotateKeyRequest {
    key_id?: string;
}

export interface RotateKeyResponse {
    success: boolean;
    message: string;
    has_new_key: boolean;
}

export interface KeyRotationHistoryEntry {
    key_id: string | null;
    rotated_ts: number | null;
}

export interface KeyRotationHistory {
    device_id: string;
    rotations: KeyRotationHistoryEntry[];
}

export interface RevokeKeyRequest {
    key_id: string;
    reason?: string;
}

export interface RevokeKeyResponse {
    success: boolean;
    revoked: number;
    message: string;
}

export interface UpdateRotationConfigRequest {
    enabled?: boolean;
    interval_ms?: number;
}

export interface UpdateRotationConfigResponse {
    enabled: boolean;
    interval_ms: number;
}

export interface KeyCheckResponse {
    needs_rotation: boolean;
    last_rotation: number | null;
    interval_ms: number;
}
