/*
 * AUTO-GENERATED by scripts/sdk-contract-codegen.mjs — DO NOT EDIT.
 * Regenerate via `pnpm run contract:codegen`.
 *
 * Module:        Relations
 * Source:        docs/synapse-rust/ROUTE_CONTRACT.md
 * Entries:       11 (authoritative set mirrored from the backend contract)
 */

/** Routes served by the synapse-rust `relations` module (mirrored from the backend contract). */
export const RELATIONS_ROUTES = [
    { method: "GET", path: "/_matrix/client/r0/rooms/{room_id}/aggregations/{event_id}/{rel_type}" },
    { method: "GET", path: "/_matrix/client/r0/rooms/{room_id}/relations/{event_id}/{rel_type}" },
    { method: "PUT", path: "/_matrix/client/r0/rooms/{room_id}/relations/{event_id}/{rel_type}/{txn_id}" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/aggregations/{event_id}/{rel_type}" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/relations/{event_id}" },
    { method: "GET", path: "/_matrix/client/v1/rooms/{room_id}/relations/{event_id}/{rel_type}" },
    { method: "PUT", path: "/_matrix/client/v1/rooms/{room_id}/relations/{event_id}/{rel_type}/{txn_id}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/aggregations/{event_id}/{rel_type}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/relations/{event_id}" },
    { method: "GET", path: "/_matrix/client/v3/rooms/{room_id}/relations/{event_id}/{rel_type}" },
    { method: "PUT", path: "/_matrix/client/v3/rooms/{room_id}/relations/{event_id}/{rel_type}/{txn_id}" },
] as const satisfies readonly { readonly method: string; readonly path: string }[];

/** Union of every (method, path) tuple in `RELATIONS_ROUTES`. */
export type RelationsRoute = (typeof RELATIONS_ROUTES)[number];

/** HTTP methods referenced by this module. */
export type RelationsMethod = RelationsRoute["method"];

/** Path templates referenced by this module. */
export type RelationsPath = RelationsRoute["path"];

/**
 * Recursively replace `{name}` placeholders with `${string}` so that
 * runtime template literals like ` `/friends/${userId}` ` satisfy this
 * type. Used by manager code that binds call sites to the ledger while
 * still interpolating path parameters.
 */
export type RelationsReplaceBraces<P extends string> =
    P extends `${infer A}{${infer ParamSegment}}${infer B}` ? ParamSegment extends string ? `${A}${string}${RelationsReplaceBraces<B>}` : never : P;

/** Broader path type that also accepts parametrised template literals. */
export type RelationsPathPattern = RelationsReplaceBraces<RelationsPath>;
